{
 "title": "StarRocks Overview Copy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "StarRocks_Prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{app_kubernetes_io_managed_by=\"kubeblocks\", apps_kubeblocks_io_component_name=~\"fe|be\"},namespace)"
    }
   },
   { "name": "feservice", "label": "FeServiceGroup", "query": "fe" },
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(up{apps_kubeblocks_io_component_name=\"$feservice\", namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "fe_master",
    "query": {
     "query": "label_values(node_info{namespace=\"$namespace\", type=\"is_master\", apps_kubeblocks_io_component_name=\"fe\"},instance)"
    }
   },
   {
    "name": "fe_instance",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\", apps_kubeblocks_io_component_name=\"$feservice\"},instance)"
    }
   },
   {
    "name": "instance",
    "label": "be/cn_instance",
    "query": {
     "query": "label_values(up{service=~\"be\", namespace=\"$namespace\"},instance)"
    }
   },
   { "name": "interval", "query": "1m,2m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Number",
   "type": "stat",
   "description": "Num of  StarRocks Clusters",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_info{type=\"is_master\", service=\"$feservice\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Frontends Status",
   "type": "timeseries",
   "description": "Dead Frontends will be shown as Colored points.\nIf all Frontends are alive, all points should be Green.",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(up{service=\"$feservice\", namespace=\"$namespace\"} == 0) +0",
     "legendFormat": "$cluster_name-{{instance}}: DEAD"
    },
    {
     "expr": "(up{service=\"$feservice\", namespace=\"$namespace\"} == 1) +0",
     "legendFormat": "$cluster_name-{{instance}}: ALIVE"
    }
   ]
  },
  {
   "title": "Backends status",
   "type": "timeseries",
   "description": "Dead Backends will be shown as Colored points.\nIf all Backends are alive, all points should be Green.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(up{service=~\"be|fe\", namespace=\"$namespace\"} == 0) +0",
     "legendFormat": "$cluster_name-{{instance}}: DEAD"
    },
    {
     "expr": "(up{service=~\"be|fe\", namespace=\"$namespace\"} == 1) +0",
     "legendFormat": "$cluster_name-{{instance}}: ALIVE"
    }
   ]
  },
  {
   "title": "Cluster FE JVM Heap Stat",
   "type": "timeseries",
   "description": "The JVM heap usage percent of each Frontend of each StarRocks cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_heap_size_bytes{service=\"$feservice\", namespace=\"$namespace\", type=\"used\"} * 100) by (instance) / sum(jvm_heap_size_bytes{service=\"$feservice\", namespace=\"$namespace\", type=\"max\"}) by (instance)",
     "legendFormat": "$cluster_name-{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster BE/CN CPU Idle",
   "type": "timeseries",
   "description": "The Backend CPU idle overview of each StarRocks cluster.\nThe detail Backend CPU idle info can be seen in 'BE/CN' section.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(starrocks_be_cpu{service=~\"be|fe\", namespace=\"$namespace\", mode=\"idle\"}[$interval]))) / (sum(rate(starrocks_be_cpu{service=~\"be|fe\", namespace=\"$namespace\"}[$interval])))",
     "legendFormat": "$cluster_name"
    }
   ]
  },
  {
   "title": "Cluster BE/CN Mem Stat",
   "type": "timeseries",
   "description": "The Backend memory usage overview of each StarRocks cluster.\nThe detail backend memory usage can be seen in 'BE/CN' section.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(starrocks_be_process_mem_bytes{service=~\"be|fe\", namespace=\"$namespace\"})",
     "legendFormat": "$cluster_name"
    }
   ]
  },
  {
   "title": "Cluster QPS Stat",
   "type": "timeseries",
   "description": "QPS statistic group by cluster.\nThe QPS of each cluster is the sum of all queries processed on all Frontends.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(starrocks_fe_query_total{service=\"$feservice\", namespace=\"$namespace\"}[$interval]))",
     "legendFormat": "$cluster_name"
    }
   ]
  },
  {
   "title": "[$cluster_name] Disk State",
   "type": "timeseries",
   "description": "The Disk state. GREEN point means this disk is ONLINE. RED point means this disk is OFFLINE",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(starrocks_be_disks_state{namespace=\"$namespace\", service=~\"be|fe\"} == 0)+0",
     "legendFormat": "{{instance}}: {{path}} OFFLINE"
    },
    {
     "expr": "(starrocks_be_disks_state{namespace=\"$namespace\", service=~\"be|fe\"} == 1)+0",
     "legendFormat": "{{instance}}: {{path}} ONLINE"
    }
   ]
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "cluster_name" },
  {
   "title": "[$cluster_name] FE Node",
   "type": "stat",
   "description": "Total Frontends node number",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\", service=\"$feservice\"})"
    }
   ]
  },
  {
   "title": "[$cluster_name]  FE Alive",
   "type": "stat",
   "description": "Total alive number of Frontends. Normally, it should be equal to the Total number of Frontends",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\", service=\"$feservice\"}==1)"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Node",
   "type": "stat",
   "description": "Total Backends node number",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\", service=~\"be|fe\"})"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Alive",
   "type": "stat",
   "description": "Total alive number of Backends. Normally, it should be equal to the Total number of Backends.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"$namespace\", service=~\"be|fe\"}==1)"
    }
   ]
  },
  {
   "title": "[$cluster_name] Used Capacity",
   "type": "stat",
   "description": "Total used disk capacity of all Backends.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(starrocks_be_disks_data_used_capacity{namespace=\"$namespace\", service=~\"be|fe\"})"
    }
   ]
  },
  {
   "title": "[$cluster_name] Total Capacity",
   "type": "stat",
   "description": "Total disk capacity of all Backends",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(starrocks_be_disks_total_capacity{namespace=\"$namespace\", service=~\"be|fe\"})"
    }
   ]
  },
  {
   "title": "[$cluster_name] Max Replayed journal id",
   "type": "timeseries",
   "description": "The max replayed meta data journal id on Frontends.\nNormally, all Frontends should be same on this metrics, or just slightly different for a short period.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "starrocks_fe_max_journal_id{namespace=\"$namespace\", service=\"$feservice\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Image counter",
   "type": "timeseries",
   "description": "The counter of meta data image generation on Master Frontend. And the counter of image successfully pushing to other Non-master Frontends.\nThese metrics is expected to increase at reasonable intervals. And normally, they should be equal.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "starrocks_fe_image_write{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "{{instance}}-generate"
    },
    {
     "expr": "starrocks_fe_image_push{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "{{instance}}-push"
    }
   ]
  },
  {
   "title": "[$cluster_name] BDBJE Write",
   "type": "timeseries",
   "description": "The left Y axes shows write latency of 99th. The right Y axes shows the write per seconds of journal.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "starrocks_fe_editlog_write_latency_ms{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-99th"
    },
    {
     "expr": "rate(starrocks_fe_edit_log_write{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}[$interval])",
     "legendFormat": "{{instance}}-rate"
    }
   ]
  },
  {
   "title": "[$cluster_name] Scheduling Tablets",
   "type": "timeseries",
   "description": "Number of tablets begin scheduled. These tablet may be in recovery process or balance process",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_scheduled_tablet_num{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "Scheduling tablet number"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN IO Util",
   "type": "timeseries",
   "description": "The max IO util of each Backend",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "starrocks_be_max_disk_io_util_percent{namespace=\"$namespace\", service=~\"be|fe\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Compaction Score",
   "type": "timeseries",
   "description": "The compaction score of each BE/CN",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "starrocks_fe_tablet_max_compaction_score{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Query Statistic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "[$cluster_name] RPS",
   "type": "timeseries",
   "description": "Requests per seconds on each Frontends.\nRequests include all requests sending to the Frontends.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(starrocks_fe_request_total{namespace=\"$namespace\", service=\"$feservice\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] QPS",
   "type": "timeseries",
   "description": "Queries per seconds on each Frontends.\nQueries only include Select requests.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(starrocks_fe_query_total{namespace=\"$namespace\", service=\"$feservice\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] 99th Latency",
   "type": "timeseries",
   "description": "99 quantiles of query latency on each Frontends.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(starrocks_fe_query_latency_ms{namespace=\"$namespace\", service=\"$feservice\", quantile=\"0.99\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] [$fe_instance] Query Percentile",
   "type": "timeseries",
   "description": "Left Y axes indicates 95 to 99 quantiles of query latency on each Frontends.\nRight Y axes indicates the query rate per 1 min.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "starrocks_fe_query_latency_ms{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "rate(starrocks_fe_query_latency_ms_count{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\"}[1m])",
     "legendFormat": "query rate"
    }
   ]
  },
  {
   "title": "[$cluster_name] Query Error [1m]",
   "type": "timeseries",
   "description": "Left Y axes indicates the accumulated  error queries number.\nRight Y axes indicates the error query rate per 1 min.\nNormally, the error query rate should be 0.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_query_err{namespace=\"$namespace\", service=\"$feservice\"}",
     "legendFormat": "Err Counter-{{instance}}"
    },
    {
     "expr": "rate(starrocks_fe_query_err{namespace=\"$namespace\", service=\"$feservice\"}[$interval])",
     "legendFormat": "Err Rate-{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Connections",
   "type": "timeseries",
   "description": "The connections' number to each Frontends.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_connection_total{namespace=\"$namespace\", service=\"$feservice\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "[$cluster_name] Mini Load Job",
   "type": "table",
   "description": "Statistic of Mini load jobs's num in each Load State.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"MINI\", instance=\"$fe_master\"}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Hadoop Load Job",
   "type": "table",
   "description": "Statistic of Hadoop load jobs's num in each Load State.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"HADOOP\", instance=\"$fe_master\"}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Broker Load Job",
   "type": "table",
   "description": "Statistic of Broker load jobs's num in each Load State.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\"}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Insert Load Job",
   "type": "table",
   "description": "Statistic of load jobs's num  in each Load State which is generated by Insert Stmt.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\"}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Mini load tendency",
   "type": "timeseries",
   "description": "The trend report of mini load job",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"MINI\", instance=\"$fe_master\", state=\"PENDING\"}",
     "legendFormat": "PENDING"
    },
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"MINI\", instance=\"$fe_master\", state=\"ETL\"}",
     "legendFormat": "ETL"
    },
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"MINI\", instance=\"$fe_master\", state=\"LOADING\"}",
     "legendFormat": "LOADING"
    }
   ]
  },
  {
   "title": "[$cluster_name] Hadoop load tendency",
   "type": "timeseries",
   "description": "The trend report of hadoop load job",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"HADOOP\", instance=\"$fe_master\", state=\"PENDING\"}",
     "legendFormat": "PENDING"
    },
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"HADOOP\", instance=\"$fe_master\", state=\"ETL\"}",
     "legendFormat": "ETL"
    },
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"HADOOP\", instance=\"$fe_master\", state=\"LOADING\"}",
     "legendFormat": "LOADING"
    }
   ]
  },
  {
   "title": "[$cluster_name] Broker load tendency",
   "type": "timeseries",
   "description": "The trend report of broker load job",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"PENDING\"}",
     "legendFormat": "PENDING"
    },
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"ETL\"}",
     "legendFormat": "ETL"
    },
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"BROKER\", instance=\"$fe_master\", state=\"LOADING\"}",
     "legendFormat": "LOADING"
    }
   ]
  },
  {
   "title": "[$cluster_name] Insert load tendency",
   "type": "timeseries",
   "description": "The trend report of insert load job",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"PENDING\"}",
     "legendFormat": "PENDING"
    },
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"ETL\"}",
     "legendFormat": "ETL"
    },
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", exported_job=\"load\", type=\"INSERT\", instance=\"$fe_master\", state=\"LOADING\"}",
     "legendFormat": "LOADING"
    }
   ]
  },
  {
   "title": "[$cluster_name] Load submit",
   "type": "timeseries",
   "description": "Show the counter of Load job submitted and Load job finished.\nThe two lines show be paralleled if the load submit is a routine operations.\nRight Y axes shows the submit rate of load job",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_load_add{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "{{instance}}-Submit"
    },
    {
     "expr": "starrocks_fe_load_finished{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "{{instance}}-Finished"
    },
    {
     "expr": "rate(starrocks_fe_load_add{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}[1h])",
     "legendFormat": "{{instance}}-Submit rate"
    }
   ]
  },
  {
   "title": "[$cluster_name] Schema Change Job",
   "type": "table",
   "description": "Number of running schema change jobs.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\", type=\"SCHEMA_CHANGE\"}",
     "legendFormat": "asds"
    }
   ]
  },
  {
   "title": "[$cluster_name] Report queue size",
   "type": "timeseries",
   "description": "Queue size of report in Master FE.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_report_queue_size{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "Report queue size"
    }
   ]
  },
  {
   "title": "[$cluster_name] Rollup Job",
   "type": "table",
   "description": "Number of running rollup jobs.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "starrocks_fe_job{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\", type=\"ROLLUP\"}"
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "[$cluster_name] Txn Begin/Success on FE",
   "type": "timeseries",
   "description": "Show the number and rate of txn begin and success",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "starrocks_fe_txn_begin{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "txn begin"
    },
    {
     "expr": "starrocks_fe_txn_success{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "txn success"
    },
    {
     "expr": "irate(starrocks_fe_txn_begin{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}[$interval])",
     "legendFormat": "txn begin rate"
    },
    {
     "expr": "irate(starrocks_fe_txn_success{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}[$interval])",
     "legendFormat": "txn success rate"
    }
   ]
  },
  {
   "title": "[$cluster_name] Txn Failed/Reject on FE",
   "type": "timeseries",
   "description": "Show the failed txn request. Including rejected request and failed txn",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 78 },
   "targets": [
    {
     "expr": "rate(starrocks_fe_txn_reject{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}[$interval])",
     "legendFormat": "txn reject rate"
    },
    {
     "expr": "rate(starrocks_fe_txn_failed{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}[$interval])",
     "legendFormat": "txn failed rate"
    }
   ]
  },
  {
   "title": "[$cluster_name] Publish Task on BE/CN",
   "type": "timeseries",
   "description": "The number of total publish task request and error rate.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"publish\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"publish\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Txn Requset on BE/CN",
   "type": "timeseries",
   "description": "Show the txn request on BE/CN",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(starrocks_be_txn_request{job=\"kubeblocks\", namespace=\"$namespace\", service=~\"be|fe\", type=\"begin\"})",
     "legendFormat": "begin"
    },
    {
     "expr": "sum(starrocks_be_txn_request{job=\"kubeblocks\", namespace=\"$namespace\", service=~\"be|fe\", type=\"exec\"})",
     "legendFormat": "exec"
    },
    {
     "expr": "sum(starrocks_be_txn_request{job=\"kubeblocks\", namespace=\"$namespace\", service=~\"be|fe\", type=\"commit\"})",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(starrocks_be_txn_request{job=\"kubeblocks\", namespace=\"$namespace\", service=~\"be|fe\", type=\"rollback\"})",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "[$cluster_name] Txn Load Bytes/Rows rate",
   "type": "timeseries",
   "description": "Left Y axes indicates the total received bytes rate of txn. Right Y axes indicates the loaded rows rate of txn.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 84 },
   "targets": [
    {
     "expr": "sum(rate(starrocks_be_stream_load{job=\"kubeblocks\", namespace=\"$namespace\", service=~\"be|fe\", type=\"receive_bytes\"}[$interval]))",
     "legendFormat": "bytes"
    },
    {
     "expr": "sum(rate(starrocks_be_stream_load{job=\"kubeblocks\", namespace=\"$namespace\", service=~\"be|fe\", type=\"load_rows\"}[$interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  { "title": "FE JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "[$cluster_name] [$fe_instance] JVM Heap",
   "type": "timeseries",
   "description": "JVM Heap usage of specified Frontend.\nLeft Y Axes shows the used/max heap size.\nRight Y Axes shows the used percentage.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "jvm_heap_size_bytes{instance=~\"$fe_instance\", namespace=\"$namespace\", service=\"$feservice\", type=\"used\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_heap_size_bytes{instance=~\"$fe_instance\", namespace=\"$namespace\", service=\"$feservice\", type=\"max\"}",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_heap_size_bytes{instance=~\"$fe_instance\", namespace=\"$namespace\", service=\"$feservice\", type=\"used\"}) * 100 / sum(jvm_heap_size_bytes{instance=~\"$fe_instance\", namespace=\"$namespace\", service=\"$feservice\", type=\"max\"})",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "[$cluster_name] [$fe_instance] JVM Non Heap",
   "type": "timeseries",
   "description": "JVM Non Heap usage of specified Frontend.\nLeft Y Axes shows the used/committed non heap size.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 93 },
   "targets": [
    {
     "expr": "jvm_non_heap_size_bytes{instance=~\"$fe_instance\", namespace=\"$namespace\", service=\"$feservice\", type=\"used\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_non_heap_size_bytes{instance=~\"$fe_instance\", namespace=\"$namespace\", service=\"$feservice\", type=\"committed\"}",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "[$cluster_name] [$fe_instance] JVM Direct Buffer",
   "type": "timeseries",
   "description": "JVM Direct buffer usage of specified Frontend.\nLeft Y Axes shows the used/capacity direct buffer size.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "jvm_direct_buffer_pool_size_bytes{instance=~\"$fe_instance\", namespace=\"$namespace\", service=\"$feservice\", type=\"used\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_direct_buffer_pool_size_bytes{instance=~\"$fe_instance\", namespace=\"$namespace\", service=\"$feservice\", type=\"capacity\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "[$cluster_name] JVM Threads",
   "type": "timeseries",
   "description": "Num of threads of FE JVM",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 93 },
   "targets": [
    {
     "expr": "jvm_thread{namespace=\"$namespace\", service=\"$feservice\", type=\"count\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] [$fe_instance] JVM Young",
   "type": "timeseries",
   "description": "JVM young generation usage of specified Frontend.\nLeft Y Axes shows the used/max young generation size.\nRight Y Axes shows the used percentage.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "jvm_young_size_bytes{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"used\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_young_size_bytes{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"max\"}",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_young_size_bytes{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"used\"}) * 100 / sum(jvm_young_size_bytes{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"max\"})",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "[$cluster_name] [$fe_instance] JVM Old",
   "type": "timeseries",
   "description": "JVM old generation usage of specified Frontend. Left Y Axes shows the used/max old generation size. Right Y Axes shows the used percentage.\nNormally, the usage percentage should be less than 80%.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 99 },
   "targets": [
    {
     "expr": "jvm_old_size_bytes{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"used\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_old_size_bytes{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"max\"}",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_old_size_bytes{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"used\"}) * 100 / sum(jvm_old_size_bytes{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"max\"})",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "[$cluster_name] [$fe_instance] JVM Young GC",
   "type": "timeseries",
   "description": "JVM young gc stat of specified Frontend. \nLeft Y Axes shows times of young gc.\nRight Y Axes shows the time cost of each young gc.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "jvm_young_gc{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"count\"}",
     "legendFormat": "count"
    },
    {
     "expr": "sum(jvm_young_gc{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"time\"}) / sum(jvm_young_gc{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"count\"})",
     "legendFormat": "avg time"
    }
   ]
  },
  {
   "title": "[$cluster_name] [$fe_instance] JVM Old GC",
   "type": "timeseries",
   "description": "JVM full gc stat of specified Frontend. \nLeft Y Axes shows times of full gc.\nRight Y Axes shows the time cost of each full gc.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 99 },
   "targets": [
    {
     "expr": "jvm_old_gc{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"count\"}",
     "legendFormat": "count"
    },
    {
     "expr": "sum(jvm_old_gc{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"time\"}) / sum(jvm_old_gc{namespace=\"$namespace\", service=\"$feservice\", instance=~\"$fe_instance\", type=\"count\"})",
     "legendFormat": "avg time"
    }
   ]
  },
  { "title": "BE/CN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "[$cluster_name] BE/CN CPU Idle",
   "type": "timeseries",
   "description": "CPU idle stat of Backends.\nLow means CPU is busy.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "(sum(rate(starrocks_be_cpu{namespace=\"$namespace\", service=~\"be|fe\", mode=\"idle\"}[$interval])) by (instance)) / (sum(rate(starrocks_be_cpu{namespace=\"$namespace\", service=~\"be|fe\"}[$interval])) by (instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Mem",
   "type": "timeseries",
   "description": "Memory usage of Backends.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "starrocks_be_process_mem_bytes{namespace=\"$namespace\", service=~\"be|fe\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Net send/receive bytes",
   "type": "timeseries",
   "description": "Network send(Left Y)/receive(Right Y) bytes rate of all device except 'lo'",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "irate(starrocks_be_network_send_bytes{namespace=\"$namespace\", service=~\"be|fe\", device!=\"lo\"}[$interval])",
     "legendFormat": "{{instance}}-{{device}}-send"
    },
    {
     "expr": "irate(starrocks_be_network_receive_bytes{namespace=\"$namespace\", service=~\"be|fe\", device!=\"lo\"}[$interval])",
     "legendFormat": "{{instance}}-{{device}}-receive"
    }
   ]
  },
  {
   "title": "[$cluster_name] Disk Usage",
   "type": "timeseries",
   "description": "Disk capacity usage of Backends",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 115 },
   "targets": [
    {
     "expr": "(SUM(starrocks_be_disks_total_capacity{namespace=\"$namespace\", service=~\"be|fe\"}) by (instance, path) - SUM(starrocks_be_disks_avail_capacity{namespace=\"$namespace\", service=~\"be|fe\"}) by (instance, path)) / SUM(starrocks_be_disks_total_capacity{namespace=\"$namespace\", service=~\"be|fe\"}) by (instance, path)",
     "legendFormat": "{{instance}}:{{path}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Tablet Distribution",
   "type": "timeseries",
   "description": "Number of tablets of each Backends",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 115 },
   "targets": [
    {
     "expr": "starrocks_fe_tablet_num{namespace=\"$namespace\", service=\"$feservice\", instance=\"$fe_master\"}",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN FD count",
   "type": "timeseries",
   "description": "The file descriptor usage of Backends. Left Y axes shows the used fd num. Right Y axes shows the soft limit open file number.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "starrocks_be_process_fd_num_used{namespace=\"$namespace\", service=~\"be|fe\"}",
     "legendFormat": "{{instance}}-used"
    },
    {
     "expr": "starrocks_be_process_fd_num_limit_soft{namespace=\"$namespace\", service=~\"be|fe\"}",
     "legendFormat": "{{instance}}-soft limit"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN thread num",
   "type": "timeseries",
   "description": "The thread number of Backends",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 122 },
   "targets": [
    {
     "expr": "starrocks_be_process_thread_num{namespace=\"$namespace\", service=~\"be|fe\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Disk IO util",
   "type": "timeseries",
   "description": "IO util of Backends.\nHigh means I/O is busy.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 122 },
   "targets": [
    {
     "expr": "starrocks_be_max_disk_io_util_percent{namespace=\"$namespace\", service=~\"be|fe\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Compaction Base",
   "type": "timeseries",
   "description": "Base compaction rate of Backends.\nNormally, base compaction only runs between 20:00 to 4:00 and it is configurable.\nRight Y axes indicates the total base compaction bytes.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "rate(starrocks_be_compaction_bytes_total{type=\"base\", namespace=\"$namespace\", service=~\"be|fe\"}[$interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(starrocks_be_compaction_bytes_total{type=\"base\", namespace=\"$namespace\", service=~\"be|fe\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Compaction Cumulate",
   "type": "timeseries",
   "description": "Cumulative compaction rate of Backends.\nRight Y axes indicates the total cumulative compaction bytes.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 129 },
   "targets": [
    {
     "expr": "rate(starrocks_be_compaction_bytes_total{type=\"cumulative\", namespace=\"$namespace\", service=~\"be|fe\"}[$interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "SUM(starrocks_be_compaction_bytes_total{type=\"cumulative\", namespace=\"$namespace\", service=~\"be|fe\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Push Bytes",
   "type": "timeseries",
   "description": "Loading rate of Backends.\nThis indicates the rate of file downloading in LOADING state of load job(MINI and BROKER load).\nRight Y axes indicates the total rate of file downloading.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "rate(starrocks_be_push_request_write_bytes{namespace=\"$namespace\", service=~\"be|fe\"}[$interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(starrocks_be_push_request_write_bytes{namespace=\"$namespace\", service=~\"be|fe\"}[$interval]))",
     "legendFormat": "Total rate"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Push Rows",
   "type": "timeseries",
   "description": "Loading rows rate of Backends.\nThis indicates the rate of rows loaded in LOADING state of load job. Right Y axes shows the total push rate of cluster.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 134 },
   "targets": [
    {
     "expr": "rate(starrocks_be_push_request_write_rows{namespace=\"$namespace\", service=~\"be|fe\"}[$interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(starrocks_be_push_request_write_rows{namespace=\"$namespace\", service=~\"be|fe\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Scan Bytes",
   "type": "timeseries",
   "description": "Scan rate of Backends.\nThis indicates the read rate when processing queries.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "rate(starrocks_be_query_scan_bytes{namespace=\"$namespace\", service=~\"be|fe\"}[$interval])",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "[$cluster_name] BE/CN Scan Rows",
   "type": "timeseries",
   "description": "Scan rows rate of Backends.\nThis indicates the read rows rate when processing queries.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "expr": "rate(starrocks_be_query_scan_rows{namespace=\"$namespace\", service=~\"be|fe\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Tablet Meta Write",
   "type": "timeseries",
   "description": "Left Y axes shows the write rate of tablet header saved in rocksdb. Right Y axes shows the duration of each write operation.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "irate(starrocks_be_meta_request_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"write\"}[$interval])",
     "legendFormat": "{{instance}}-rate"
    },
    {
     "expr": "starrocks_be_meta_request_duration{namespace=\"$namespace\", service=~\"be|fe\", type=\"write\"} / starrocks_be_meta_request_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"write\"}",
     "legendFormat": "{{instance}}-latency"
    }
   ]
  },
  {
   "title": "[$cluster_name] Tablet Meta Read",
   "type": "timeseries",
   "description": "Left Y axes shows the read rate of tablet header saved in rocksdb. Right Y axes shows the duration of each read operation.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "expr": "irate(starrocks_be_meta_request_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"read\"}[$interval])",
     "legendFormat": "{{instance}}-rate"
    },
    {
     "expr": "starrocks_be_meta_request_duration{namespace=\"$namespace\", service=~\"be|fe\", type=\"read\"} / starrocks_be_meta_request_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"read\"}",
     "legendFormat": "{{instance}}-latency"
    }
   ]
  },
  { "title": "BE/CN tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "[$cluster_name] Tablets Report",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 154 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"report_all_tablets\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"report_all_tablets\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Single Tablet Report",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 154 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"report_tablet\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"report_tablet\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Finish task report",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 154 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"finish_task\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"finish_task\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Push Task",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "sum(starrocks_be_push_requests_total{namespace=\"$namespace\", service=~\"be|fe\", status=\"SUCCESS\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_push_requests_total{namespace=\"$namespace\", service=~\"be|fe\", status=\"FAIL\"}[$interval])",
     "legendFormat": "{{instance}}-failed"
    }
   ]
  },
  {
   "title": "[$cluster_name] Push Task Cost Time",
   "type": "timeseries",
   "description": "The average cost time of push tasks on each Backend.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 160 },
   "targets": [
    {
     "expr": "irate(starrocks_be_push_request_duration_us{namespace=\"$namespace\", service=~\"be|fe\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Delete",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 160 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"delete\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"delete\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Base Compaction",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"base_compaction\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"base_compaction\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Cumulative Compaction",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 166 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"cumulative_compaction\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"cumulative_compaction\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Clone",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 166 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"clone\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"clone\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Create rollup",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 172 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"create_rollup\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"create_rollup\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Schema change",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 172 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"schema_change\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"schema_change\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[$cluster_name] Create tablet",
   "type": "timeseries",
   "description": "Left Y axes indicates the failure rate of specified tasks. Normally, it should be 0.\nRight Y axes indicates the total number of specified tasks in all Backends.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 172 },
   "targets": [
    {
     "expr": "SUM(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"create_tablet\", status=\"total\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "irate(starrocks_be_engine_requests_total{namespace=\"$namespace\", service=~\"be|fe\", type=\"create_tablet\", status=\"failed\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}