apiVersion: apps.kubeblocks.io/v1
kind: ComponentDefinition
metadata:
  name: {{ include "seaweedfs.cmpdName" (dict "root" . "component" "filer") }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
  annotations:
    {{- include "seaweedfs.annotations" . | nindent 4 }}
spec:
  provider: kubeblocks
  description: SeaweedFS filer component.
  serviceKind: seaweedfs
  serviceVersion: {{ .Values.serviceVersion | quote }}
  podManagementPolicy: Parallel
  updateStrategy: Serial
  podUpdatePolicy: ReCreate
  minReadySeconds: 10
  replicasLimit:
    minReplicas: 1
    maxReplicas: 1
  {{- include "seaweedfs.scripts" . | nindent 2 }}
  volumes:
    - name: data
      needSnapshot: false
  configs:
    - name: filer-config
      template: {{ include "seaweedfs.filerConfigName" . }}
      namespace: {{ .Release.Namespace }}
      volumeName: filer-config
      defaultMode: 0444
  services:
    - name: default
      spec:
        ports:
          - name: http
            port: 8888
            targetPort: http
          - name: grpc
            port: 18888
            targetPort: grpc
  vars:
    {{- include "seaweedfs.identityVars" . | nindent 4 }}
    {{- include "seaweedfs.masterVars" . | nindent 4 }}
  runtime:
    {{- include "seaweedfs.podSecurityContext" . | nindent 4 }}
    terminationGracePeriodSeconds: 60
    containers:
      - name: filer
        image: {{ include "seaweedfs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "/scripts/start-filer.sh"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
          - name: http
            containerPort: 8888
          - name: grpc
            containerPort: 18888
        startupProbe:
          tcpSocket:
            port: http
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 90
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          periodSeconds: 10
          timeoutSeconds: 6
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: http
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 6
        volumeMounts:
          - name: scripts
            mountPath: /scripts
            readOnly: true
          - name: data
            mountPath: /data
          - name: filer-config
            mountPath: /etc/seaweedfs
            readOnly: true
