apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seaweedfs.scriptsName" . }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/*.sh").AsConfig | indent 2 }}
