apiVersion: apps.kubeblocks.io/v1
kind: ClusterDefinition
metadata:
  name: hugegraph
  labels:
    {{- include "hugegraph.labels" . | nindent 4 }}
  annotations:
    {{- include "hugegraph.apiVersion" . | nindent 4 }}
spec:
  topologies:
    - name: standalone
      default: true
      components:
        - name: server
          compDef: {{ include "hugegraph.cmpdPattern" . }}
