apiVersion: apps.kubeblocks.io/v1
kind: ComponentDefinition
metadata:
  name: {{ include "hugegraph.serverCmpdName" . }}
  labels:
    {{- include "hugegraph.labels" . | nindent 4 }}
  annotations:
    apps.kubeblocks.io/skip-immutable-check: "true"
    {{- include "hugegraph.annotations" . | nindent 4 }}
spec:
  provider: kubeblocks
  description: Apache HugeGraph 1.7.0 query server on HStore.
  serviceKind: hugegraph
  serviceVersion: {{ .Values.serviceVersion }}
  minReadySeconds: 10
  replicasLimit:
    minReplicas: 1
    maxReplicas: 5
  services:
    - name: default
      spec:
        ports:
          - name: http
            port: 8080
            targetPort: http
          - name: gremlin
            port: 8182
            targetPort: gremlin
  scripts:
    - name: hugegraph-scripts
      template: {{ include "hugegraph.scriptsTemplateName" . }}
      namespace: {{ .Release.Namespace }}
      volumeName: scripts
      defaultMode: 0555
  vars:
    - name: PD_POD_FQDNS
      valueFrom:
        componentVarRef:
          compDef: {{ include "hugegraph.pdCmpdPattern" . }}
          optional: false
          podFQDNs: Required
    - name: STORE_POD_FQDNS
      valueFrom:
        componentVarRef:
          compDef: {{ include "hugegraph.storeCmpdPattern" . }}
          optional: false
          podFQDNs: Required
  runtime:
    containers:
      - name: server
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /bin/bash
          - /scripts/start-server.sh
        ports:
          - name: http
            containerPort: 8080
          - name: gremlin
            containerPort: 8182
        startupProbe:
          httpGet:
            path: /versions
            port: http
          failureThreshold: 72
          periodSeconds: 5
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /versions
            port: http
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /versions
            port: http
          failureThreshold: 6
          periodSeconds: 15
          timeoutSeconds: 3
        volumeMounts:
          - name: scripts
            mountPath: /scripts
