apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hugegraph.scriptsTemplateName" . }}
  labels:
    {{- include "hugegraph.labels" . | nindent 4 }}
data:
  start.sh: |-
    {{- .Files.Get "scripts/start.sh" | nindent 4 }}
