apiVersion: apps.kubeblocks.io/v1
kind: ShardingDefinition
metadata:
  name: falkordb-cluster
  labels:
    {{- include "falkordb.labels" . | nindent 4 }}
  annotations:
    {{- include "falkordb.apiVersion" . | nindent 4 }}
spec:
  template:
    compDef: {{ include "falkordbCluster.cmpdRegexpPattern" . }}
  shardsLimit:
    minShards: 3
    maxShards: 64
  provisionStrategy: Parallel
  updateStrategy: Parallel
  systemAccounts:
    - name: default
      shared: true
  lifecycleActions:
    shardRemove:
      timeoutSeconds: 600
      exec:
        image: {{ include "falkordb4.image" . }}
        container: falkordb-cluster
        command:
          - /bin/bash
          - -c
          - |
            /scripts/falkordb-cluster-manage.sh --pre-terminate > /tmp/pre-terminate.log 2>&1
      retryPolicy:
        maxRetries: 10
