#!/bin/bash
# ClickHouse user password rotation script
# Rotates the password for a named ClickHouse user and updates the Kubernetes Secret.
# Usage: called by the rotate-password-clickhouse OpsDefinition.
#
# Required env vars (injected by OpsDefinition podInfoExtractor):
#   CLICKHOUSE_ADMIN_USER, CLICKHOUSE_ADMIN_PASSWORD, CLICKHOUSE_TCP_PORT
#   ROTATE_USERNAME   - the ClickHouse user to rotate (e.g. "admin")
#   ROTATE_NEW_PASS   - the new password (generated by KubeBlocks credential policy or supplied)
#   KB_SECRET_NAME    - the Kubernetes Secret holding credentials
#   KB_NAMESPACE      - namespace of the Secret
set -eo pipefail

if [[ -n "$CLICKHOUSE_POD_FQDN_LIST" ]]; then
    CLICKHOUSE_HOST="${CLICKHOUSE_POD_FQDN_LIST%%,*}"
    export CLICKHOUSE_HOST
fi

# KubeBlocks injects OpsRequest params directly as env vars using the param name:
#   username → $username, newPassword → $newPassword,
#   secretName → $secretName, secretNamespace → $secretNamespace
ROTATE_USERNAME="${username:-admin}"
ROTATE_NEW_PASS="${newPassword}"
KB_SECRET_NAME="${secretName}"
KB_NAMESPACE="${secretNamespace}"

if [[ -z "${ROTATE_NEW_PASS}" ]]; then
    echo "[ERROR] newPassword param is not set. Aborting."
    exit 1
fi

echo "══════════════════════════════════════════════"
echo "  ClickHouse Password Rotation"
echo "  User: ${ROTATE_USERNAME}  Host: ${CLICKHOUSE_HOST}"
echo "══════════════════════════════════════════════"

# ── 1. Verify current credentials work ────────────────────────
echo ""
echo "▶ [1/3] Verifying current admin connection..."
ch_query "$CLICKHOUSE_HOST" "SELECT 1" > /dev/null
echo "  [OK] Connection successful."

# ── 2. Apply new password in ClickHouse ───────────────────────
echo ""
echo "▶ [2/3] Rotating password for user '${ROTATE_USERNAME}'..."
alter_output=$(ch_query "$CLICKHOUSE_HOST" "ALTER USER \`${ROTATE_USERNAME}\` IDENTIFIED BY '${ROTATE_NEW_PASS}'" 2>&1) && {
    echo "  [OK] Password updated in ClickHouse (SQL user)."
} || {
    if echo "$alter_output" | grep -q "ACCESS_STORAGE_READONLY"; then
        echo "  [INFO] User '${ROTATE_USERNAME}' is defined in users.xml (read-only storage)."
        echo "         SQL ALTER USER is not supported for XML-defined users."
        echo "         The Kubernetes Secret will be updated; KubeBlocks will reconcile the"
        echo "         user config on the next credential sync or component restart."
    else
        echo "$alter_output" >&2
        exit 1
    fi
}

# ── 3. Update the Kubernetes Secret ───────────────────────────
echo ""
echo "▶ [3/3] Updating Kubernetes Secret '${KB_SECRET_NAME}' in namespace '${KB_NAMESPACE}'..."

if [[ -z "${KB_SECRET_NAME}" || -z "${KB_NAMESPACE}" ]]; then
    echo "  [WARN] KB_SECRET_NAME or KB_NAMESPACE not set; skipping Secret update."
    echo "         Update the Secret manually: kubectl patch secret <name> -p '{\"stringData\":{\"password\":\"<new>\"}}'."
    exit 0
fi

NEW_PASS_B64=$(printf '%s' "${ROTATE_NEW_PASS}" | base64 -w0)
# Use the in-cluster Kubernetes API (SA token mounted at /var/run/secrets/kubernetes.io/serviceaccount/)
K8S_API="https://kubernetes.default.svc"
SA_DIR="/var/run/secrets/kubernetes.io/serviceaccount"
TOKEN=$(cat "${SA_DIR}/token")
CACERT="${SA_DIR}/ca.crt"
HTTP_CODE=$(curl -s -o /tmp/patch_response.json -w "%{http_code}" \
    --cacert "${CACERT}" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json-patch+json" \
    -X PATCH \
    "${K8S_API}/api/v1/namespaces/${KB_NAMESPACE}/secrets/${KB_SECRET_NAME}" \
    -d "[{\"op\":\"replace\",\"path\":\"/data/password\",\"value\":\"${NEW_PASS_B64}\"}]")
if [[ "${HTTP_CODE}" -ge 200 && "${HTTP_CODE}" -lt 300 ]]; then
    echo "  [OK] Kubernetes Secret updated (HTTP ${HTTP_CODE})."
else
    echo "  [ERROR] Failed to patch Secret (HTTP ${HTTP_CODE}):" >&2
    cat /tmp/patch_response.json >&2
    exit 1
fi

echo ""
echo "══════════════════════════════════════════════"
echo "  Password rotation complete for user '${ROTATE_USERNAME}'."
echo "══════════════════════════════════════════════"
