{
 "title": "MongoDB Sharded Cluster Summary",
 "tags": [
  "MongoDB_HA",
  "Percona"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(mongodb_up{cluster_role=\"mongos\"},namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up{namespace=~\"$namespace\", cluster_role=\"mongos\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(mongodb_up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"},pod)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "shard",
    "label": "Shard Name",
    "query": {
     "query": "label_values(mongodb_mongos_db_collections_total{app_kubernetes_io_instance=\"$cluster\"},shard)"
    }
   },
   {
    "name": "set",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "mongos_pod",
    "label": "Node",
    "query": "label_values(mongodb_mongos_sharding_shards_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, pod)"
   },
   {
    "name": "cluster_role",
    "query": {
     "query": "label_values(mongodb_up, cluster_role)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(mongodb_up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS of Services in Shard",
   "type": "gauge",
   "description": "Queries per second of all shards + config server replica set",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rs_nm) (rate(mongodb_op_counters_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",type!=\"command\",rs_nm!~\"\"}[$interval]) or irate(mongodb_op_counters_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",type!=\"command\",rs_nm!~\"\"}[5s]))",
     "legendFormat": "{{rs_nm}} "
    }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "description": "A shard contains a subset of sharded data for a sharded cluster. Together, the cluster’s shards hold the entire data set for the cluster.",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Mongos",
   "type": "stat",
   "description": "Number of mongos routers registered as part of the cluster",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by (pod)(mongodb_mongos_sharding_shards_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Draining Shards",
   "type": "stat",
   "description": "When you run removeShard, MongoDB drains the shard by using the balancer to move the shard’s chunks to other shards in the cluster. Once the shard is drained, MongoDB removes the shard from the cluster.",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_draining_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "Draining Total"
    }
   ]
  },
  {
   "title": "DBs",
   "type": "stat",
   "description": "Total number of user-created databases",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_mongos_sharding_databases_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded Collections",
   "type": "stat",
   "description": "Number of collections that are sharded",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (namespace, app_kubernetes_io_instance) (mongodb_ss_shardingStatistics_numShardedCollections{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"} or mongodb_mongos_sharding_collections_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Balancer Enabled",
   "type": "stat",
   "description": "The MongoDB balancer is a background process that monitors the number of chunks on each shard. ",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_balancer_enabled{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Total amount of Chunks",
   "type": "stat",
   "description": "A chunk consists of a subset of sharded data.",
   "gridPos": { "h": 2, "w": 7, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_mongos_sharding_chunks_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Last Election",
   "type": "stat",
   "description": "Time since the most recent election of any member of the cluster",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_election_date{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", set=~\"$set\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Chunks distribution",
   "type": "bargauge",
   "description": "Show the chunk distribution between all the shards involved",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (shard) (last_over_time(mongodb_mongos_sharding_shard_chunks_total{app_kubernetes_io_instance=\"$cluster\"}[1m])) / sum(mongodb_mongos_sharding_shard_chunks_total{app_kubernetes_io_instance=\"$cluster\"})",
     "legendFormat": "{{shard}} "
    }
   ]
  },
  {
   "title": "Command Operations",
   "type": "graph",
   "description": "Ops or Replicated Ops/sec classified by legacy wire protocol type (query, insert, update, delete, getmore). And (from the internal TTL threads) the docs deletes/sec by TTL indexes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, app_kubernetes_io_instance) (rate(mongodb_ss_metrics_ttl_deletedDocuments{namespace=~\"$namespace\", rs_nm=~\"$set\",pod=~\"$pod\",app_kubernetes_io_instance=~\"$cluster\"}[$interval]))",
     "legendFormat": "ttl_delete"
    },
    {
     "expr": "sum by (namespace, app_kubernetes_io_instance, legacy_op_type) (rate(mongodb_ss_opcounters{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\",pod=~\"$pod\",legacy_op_type!=\"command\"}[$interval]))",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Top Hottest Collections by Read",
   "type": "bargauge",
   "description": "Show the 5 collections that are most frequently read.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5,sum by (namespace, app_kubernetes_io_instance,database,collection) ((rate(mongodb_top_queries_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\"})[$interval]) or irate(mongodb_top_queries_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\"})[5s]))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "Query execution times",
   "type": "graph",
   "description": "Average latency of operations (classified by read, write, or (other) command)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (op_type) (rate(mongodb_ss_opLatencies_latency{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$pod\"}[$interval]) / (rate(mongodb_ss_opLatencies_ops{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$pod\"}[$interval]) > 0) or irate(mongodb_ss_opLatencies_latency{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$pod\"}[5m]) / (irate(mongodb_ss_opLatencies_ops{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$pod\"}[5m]) > 0))",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "Top Hottest Collections by Write",
   "type": "bargauge",
   "description": "Show the 5 collections that are most frequently written to.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk (5,sum by (namespace,app_kubernetes_io_instance,database,collection) ((rate(mongodb_top_insert_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\"}+mongodb_top_remove_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\"}+mongodb_top_update_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\"})[$interval]) or irate(mongodb_top_insert_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\"}+mongodb_top_remove_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\"}+mongodb_top_update_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\"})[5m]))",
     "legendFormat": "{{database}}.{{collection}}"
    }
   ]
  },
  {
   "title": "Operations Per Shard",
   "type": "graph",
   "description": "Ops/sec, classified by legacy wire protocol type (query, insert, update, delete, getmore).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(mongodb_op_counters_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\", type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\", type!=\"command\"}[5m])) by (instance) * on (instance) \ngroup_right mongodb_mongod_replset_my_state{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", set=~\"$set\", pod=~\"$pod\"} / mongodb_mongod_replset_my_state{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", set=~\"$set\", pod=~\"$pod\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "MongoDB Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "avg by (pod,mongodb) (mongodb_version_info{pod=~\"$pod\"}) or (avg by (pod,mongodb) (mongodb_version_info)) * on (pod) group_right (mongodb) (avg by (pod) (mongodb_mongos_db_collections_total{app_kubernetes_io_instance=~\"$cluster\"}) / avg by (pod) (mongodb_mongos_db_collections_total{app_kubernetes_io_instance=~\"$cluster\"}))",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  { "title": "Current Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Config Servers",
   "type": "gauge",
   "description": "Config servers store the metadata for a sharded cluster. The metadata reflects state and organization for all data and components within the sharded cluster. The metadata includes the list of chunks on every shard and the ranges that define the chunks.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (member_idx) (mongodb_rs_members_state{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",rs_nm!~\"$shard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongos Routers",
   "type": "stat",
   "description": "Mongos is a routing service for MongoDB shard configurations that processes queries from the application layer, and determines the location of this data in the sharded cluster, in order to complete these operations. From the perspective of the application, a mongos instance behaves identically to any other MongoDB instance.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (mongodb_up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$mongos_pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shard - $shard",
   "type": "state-timeline",
   "description": "A shard contains a subset of sharded data for a sharded cluster. Together, the cluster’s shards hold the entire data set for the cluster.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "repeat": "shard",
   "targets": [
    {
     "expr": "min by (member_idx) (mongodb_rs_members_state{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",rs_nm=~\"$shard\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "$set Node States",
   "type": "state-timeline",
   "description": "ReplSet statuses during the select time range.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
   "repeat": "set",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by (member_idx) (mongodb_rs_members_state{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",rs_nm=~\"$set\",pod=~\"$pod\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Collection Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Size of Collections in Shards",
   "type": "table",
   "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(rs_nm, collection, database) (mongodb_collstats_storageStats_storageSize{app_kubernetes_io_instance=~\"$cluster\", db!~\"admin|config|local\", rs_nm=~\"$set\"})",
     "legendFormat": "{{db}} | {{shard}} | Collections"
    }
   ]
  },
  {
   "title": "Number of Collections in Shards",
   "type": "table",
   "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 64 },
   "targets": [
    {
     "expr": "max by (rs_nm, database) (mongodb_mongod_db_collections_total{app_kubernetes_io_instance=\"$cluster\",database!~\"admin|config|system|local\",rs_nm=~\"$set\"})",
     "legendFormat": "{{db}} | {{rs_nm}} | Collections"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Current Connections Per Shard",
   "type": "graph",
   "description": "TCP connections (Incoming) in mongod processes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (rs_nm) (mongodb_connections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", state=\"current\", rs_nm!=\"\"})",
     "legendFormat": "{{rs_nm}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (set) (avg by (pod,set) (mongodb_connections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", rs_nm=~\"$set\", pod=~\"$pod\", state=\"available\"}) * on (pod) group_right avg by (pod,set) (mongodb_mongod_replset_my_state{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", set=~\"$set\", pod=~\"$pod\"}/ mongodb_mongod_replset_my_state{app_kubernetes_io_instance=\"$cluster\"}))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "Chunks in Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Amount of Chunks in Shards",
   "type": "table",
   "description": "A chunk consists of a subset of sharded data.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "avg by (shard) (mongodb_mongos_sharding_shard_chunks_total{app_kubernetes_io_instance=\"$cluster\",db!~\"admin|config\"})",
     "legendFormat": "{{shard}} | Chunks"
    }
   ]
  },
  {
   "title": "Dynamic of Chunks",
   "type": "graph",
   "description": "The sharding operation creates the initial chunk(s) to cover the entire range of the shard key values. The number of chunks created depends on the configured chunk size. After the initial chunk creation, the balancer migrates these initial chunks across the shards as appropriate as well as manages the chunk distribution going forward.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 88 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "avg by (shard) (rate(mongodb_mongos_sharding_shard_chunks_total{app_kubernetes_io_instance=\"$cluster\"}[$interval]) or irate(mongodb_mongos_sharding_shard_chunks_total{app_kubernetes_io_instance=\"$cluster\"}[5m]))",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Chunks Move Events",
   "type": "graph",
   "description": "MongoDB migrates chunks in a sharded cluster to distribute the chunks of a sharded collection evenly among shards. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (event) (rate(mongodb_mongos_sharding_changelog_10min_total{app_kubernetes_io_instance=\"$cluster\", event=~\".*moveChunk.*\"}[$interval]) or\nirate(mongodb_mongos_sharding_changelog_10min_total{app_kubernetes_io_instance=\"$cluster\", event=~\".*moveChunk.*\"}[5m]))",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Chunks Split Events",
   "type": "graph",
   "description": "MongoDB splits chunks when they grow beyond the configured chunk size. Both inserts and updates can trigger a chunk split.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (event) (rate(mongodb_mongos_sharding_changelog_10min_total{app_kubernetes_io_instance=\"$cluster\", event=~\".*split.*\"}[$interval]) or\nirate(mongodb_mongos_sharding_changelog_10min_total{app_kubernetes_io_instance=\"$cluster\", event=~\".*split.*\"}[5m]))",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Replication Lag by Shard",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (set) (max(max_over_time(mongodb_mongod_replset_member_replication_lag{app_kubernetes_io_instance=\"$cluster\",state!=\"ARBITER\"}[$interval])) by (pod,set) or max(max_over_time(mongodb_mongod_replset_member_replication_lag{app_kubernetes_io_instance=\"$cluster\",state!=\"ARBITER\"}[5m])) by (pod,set))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oplog Range by Shard",
   "type": "graph",
   "description": "Timespan 'window' between oldest and newest ops in the Oplog collection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_replset_oplog_head_timestamp{app_kubernetes_io_instance=\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{app_kubernetes_io_instance=\"$cluster\"}) by (pod) * on (pod) group_right mongodb_mongod_replset_my_state{app_kubernetes_io_instance=\"$cluster\"} / mongodb_mongod_replset_my_state{app_kubernetes_io_instance=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  }
 ]
}