apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qdrant.configTplName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "qdrant.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Files.Get "configs/config.yaml.tpl" | nindent 4 }}
