{{- if and .Values.tls.enabled (eq .Values.tls.issuer "UserProvided") (not .Values.tls.secretName) }}
{{- $clusterName := include "kblib.clusterName" . }}
{{- $namespace := .Release.Namespace }}
{{- $secretName := printf "%s-tls" $clusterName }}
{{- $dnsNames := list
  "localhost"
  (printf "%s-rabbitmq" $clusterName)
  (printf "%s-rabbitmq.%s.svc" $clusterName $namespace)
  (printf "%s-rabbitmq.%s.svc.cluster.local" $clusterName $namespace)
  (printf "*.%s-rabbitmq-headless.%s.svc" $clusterName $namespace)
  (printf "*.%s-rabbitmq-headless.%s.svc.cluster.local" $clusterName $namespace)
}}
{{- $ca := genCA "KubeBlocks" 36500 }}
{{- $cert := genSignedCert "rabbitmq" (list "127.0.0.1" "::1") $dnsNames 36500 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "kblib.clusterLabels" . | nindent 4 }}
  annotations:
    self-signed-cert: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
