apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: hugegraph-start
  namespace: demo
spec:
  clusterName: hugegraph-cluster
  type: Start
  start:
    - componentName: server
