apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: ActionSet
metadata:
  name: mariadb-physical-br
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  env:
    - name: DATA_DIR
      value: /var/lib/mysql
  backupType: Full
  backup:
    backupData:
      image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
      runOnTargetPodNode: true
      command:
        - sh
        - -c
        - |
          set -e;
          export PATH="$PATH:$DP_DATASAFED_BIN_PATH";
          export DATASAFED_BACKEND_BASE_PATH="$DP_BACKUP_BASE_PATH";
          echo "DB_HOST=${DP_DB_HOST} DB_USER=${DP_DB_USER} DB_PASSWORD=${DP_DB_PASSWORD} DATA_DIR=${DATA_DIR} BACKUP_DIR=${DP_BACKUP_DIR} BACKUP_NAME=${DP_BACKUP_NAME}";
          mariadb-backup --backup --safe-slave-backup --slave-info --stream=mbstream --host=${DP_DB_HOST} \
          --user=${DP_DB_USER} --password=${DP_DB_PASSWORD} --datadir=${DATA_DIR} \
          --skip-ssl | datasafed push - "/${DP_BACKUP_NAME}.mbstream";
          TOTAL_SIZE=$(datasafed stat / | grep TotalSize | awk '{print $2}');
          echo "{\"totalSize\":\"${TOTAL_SIZE}\"}" > "${DP_BACKUP_INFO_FILE}"
  restore:
    prepareData:
      image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
      command:
        - sh
        - -c
        - |
          set -e;
          export PATH="$PATH:$DP_DATASAFED_BIN_PATH";
          export DATASAFED_BACKEND_BASE_PATH="$DP_BACKUP_BASE_PATH";
          echo "BACKUP_DIR=${DP_BACKUP_BASE_PATH} BACKUP_NAME=${DP_BACKUP_NAME} DATA_DIR=${DATA_DIR}";
          mkdir -p /tmp/data/ && cd /tmp/data \
          && datasafed pull "${DP_BACKUP_NAME}.mbstream" - | mbstream -x \
          && mariadb-backup --prepare --target-dir=/tmp/data/ \
          && rm -rf ${DATA_DIR}/* \
          && mariadb-backup --copy-back --target-dir=/tmp/data/ --datadir=${DATA_DIR} \
          && rm -rf /tmp/data/ \
          && chown -R mysql:mysql ${DATA_DIR} \
          && chmod -R 750 ${DATA_DIR}