apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-replication-scripts
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  update-parameter.sh: |-
    {{- .Files.Get "reloader/update-parameter.sh" | nindent 4 }}
  replication-roleprobe.sh: |-
    {{- .Files.Get "scripts/replication-roleprobe.sh" | nindent 4 }}
  replication-member-join.sh: |-
    {{- .Files.Get "scripts/replication-member-join.sh" | nindent 4 }}
  replication-switchover.sh: |-
    {{- .Files.Get "scripts/replication-switchover.sh" | nindent 4 }}
