apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  name: mysql
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  annotations:
    {{- include "mysql.apiVersion" . | nindent 4 }}
spec:
  compatibilityRules:
    - compDefs:
        - {{ include "mysql.componentDefName57" . }}
      releases:
        - 5.7.44
    - compDefs:
        - {{ include "mysql.componentDefName80" . }}
      releases:
        - 8.0.45
        - 8.0.46
    - compDefs:
        - {{ include "mysql.componentDefName84" . }}
      releases:
        - 8.4.9
        - 8.4.10
  releases:
    - name: 5.7.44
      serviceVersion: 5.7.44
      images:
        mysql: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:5.7.44
        accountProvision: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:5.7.44
        init-data: {{ .Values.image.registry | default "docker.io" }}/apecloud/mysql_audit_log:5.7.44
        init-xtrabackup: {{ .Values.image.registry | default "docker.io" }}/apecloud/xtrabackup:2.4
        {{- include "mysql.spec.runtime.images" . | nindent 8 }}
    - name: 8.0.45
      serviceVersion: 8.0.45
      images:
        mysql: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.0.45
        accountProvision: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.0.45
        init-data: {{ .Values.image.registry | default "docker.io" }}/apecloud/mysql_audit_log:8.0.33
        init-xtrabackup: {{ .Values.image.registry | default "docker.io" }}/apecloud/xtrabackup-minimal:8.0.35
        {{- include "mysql.spec.runtime.images" . | nindent 8 }}
    - name: 8.0.46
      serviceVersion: 8.0.46
      images:
        mysql: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.0.46
        accountProvision: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.0.46
        init-data: {{ .Values.image.registry | default "docker.io" }}/apecloud/mysql_audit_log:8.0.33
        init-xtrabackup: {{ .Values.image.registry | default "docker.io" }}/apecloud/xtrabackup-minimal:8.0.35
        {{- include "mysql.spec.runtime.images" . | nindent 8 }}
    - name: 8.4.9
      serviceVersion: 8.4.9
      images:
        mysql: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.4.9
        accountProvision: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.4.9
        init-xtrabackup: {{ .Values.image.registry | default "docker.io" }}/apecloud/xtrabackup-minimal:8.4.0
        {{- include "mysql.spec.runtime.images" . | nindent 8 }}
    - name: 8.4.10
      serviceVersion: 8.4.10
      images:
        mysql: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.4.10
        accountProvision: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:8.4.10
        init-xtrabackup: {{ .Values.image.registry | default "docker.io" }}/apecloud/xtrabackup-minimal:8.4.0
        {{- include "mysql.spec.runtime.images" . | nindent 8 }}
