{
 "title": "ClickHouse",
 "description": "ClickHouse internal exporter metrics",
 "tags": [
  "apps",
  "db",
  "clickhouse"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(ClickHouseAsyncMetrics_Uptime,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ClickHouseAsyncMetrics_Uptime{namespace=~\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "label_values(ClickHouseAsyncMetrics_Uptime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"},apps_kubeblocks_io_component_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ClickHouseAsyncMetrics_Uptime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\"}, pod)"
    }
   },
   { "name": "trends", "label": "Show trends", "query": "Yes : 1, No : null" },
   { "name": "peaks", "label": "Show peaks", "query": "Yes : 1, No : null" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_VersionInteger{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}"
    },
    {
     "expr": "ClickHouseMetrics_Revision{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfTables{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_Uptime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfDatabases{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Total amount of memory (bytes) allocated by the server.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of connections to TCP server (clients with native interface), also included server-server distributed query connections. \nNumber of connections to HTTP server",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "tcp - {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "http - {{instance}}"
    }
   ]
  },
  {
   "title": "Read backoff",
   "type": "graph",
   "description": "Number of times the number of query processing threads was lowered due to slow reads.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time((irate(ClickHouseProfileEvents_ReadBackoff{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBackoff{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Slow reads",
   "type": "graph",
   "description": "Number of reads from a file that were slow. This indicate system overload. Thresholds are controlled by read_backoff_* settings.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SlowRead{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SlowRead{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queries",
   "type": "graph",
   "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_Query{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_Query{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "SELECT queries",
   "type": "graph",
   "description": "Same as Queries, but only for SELECT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "INSERT queries",
   "type": "graph",
   "description": "Same as Queries, but only for INSERT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed SELECT queries",
   "type": "graph",
   "description": "Same as Failed queries, but only for SELECT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedSelectQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_FailedSelectQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed queries",
   "type": "graph",
   "description": "Number of failed queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_FailedQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Queries memory limit",
   "type": "graph",
   "description": "Number of times when memory limit exceeded for query.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Query preemted",
   "type": "graph",
   "description": "Number of queries that are stopped and waiting due to 'priority' setting.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseMetrics_QueryPreempted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseMetrics_QueryPreempted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed INSERT queries",
   "type": "graph",
   "description": "Same as Failed queries, but only for INSERT queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedInsertQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_FailedInsertQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Query latencies (avg)",
   "type": "graph",
   "description": "Avg queries latencies",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_QueryTimeMicroseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Query{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) or (increase(ClickHouseProfileEvents_Query{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) == 0) * 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SELECT query latencies (avg)",
   "type": "graph",
   "description": "Avg SELECT queries latencies",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_SelectQueryTimeMicroseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_SelectQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) or (increase(ClickHouseProfileEvents_SelectQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval])==0) * 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "INSERT query latencies (avg)",
   "type": "graph",
   "description": "Avg INSERT queries latencies",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_InsertQueryTimeMicroseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_InsertQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) or (increase(ClickHouseProfileEvents_InsertQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval])==0) * 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Insert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Inserted rows",
     "type": "graph",
     "description": "Number of rows INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedRows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_InsertedRows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Inserted bytes",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) INSERTed to all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_InsertedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Delayed inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DelayedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DelayedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Rejected inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a MergeTree table was rejected with 'Too many parts' exception due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_RejectedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_RejectedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Delayed inserts blocks (avg)",
     "type": "graph",
     "description": "Total number of milliseconds spent while the INSERT of a block to a MergeTree table was throttled due to high number of active data parts for partition.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_DelayedInsertsMilliseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_DelayedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) or (increase(ClickHouseProfileEvents_DelayedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval])==0) * 0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Select",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Parts",
     "type": "graph",
     "description": "Number of data parts selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedParts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedParts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Ranges",
     "type": "graph",
     "description": "Number of (non-adjacent) ranges in all data parts selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRanges{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedRanges{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Marks",
     "type": "graph",
     "description": "Number of marks (index granules) selected to read from a MergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedMarks{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedMarks{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "graph",
     "description": "Number of rows SELECTed from all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedRows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes",
     "type": "graph",
     "description": "Number of bytes (uncompressed; for columns as they stored in memory) SELECTed from all tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_SelectedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "lseek",
     "type": "graph",
     "description": "Number of times the 'lseek' function was called.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Seek{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_Seek{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "graph",
     "description": "Number of files opened",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FileOpen{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_FileOpen{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read from FD",
     "type": "graph",
     "description": "Number of reads (read/pread) from a file descriptor. Does not include sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Write to FD",
     "type": "graph",
     "description": "Number of writes (write/pwrite) to a file descriptor. Does not include sockets.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read from FD failed",
     "type": "graph",
     "description": "Number of times the read (read/pread) from a file descriptor have failed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read from FD failed",
     "type": "graph",
     "description": "Number of times the read (read/pread) from a file descriptor have failed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read bytes from FD",
     "type": "graph",
     "description": "Number of bytes read from file descriptors. If the file is compressed, this will show the compressed data size.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Write bytes to FD",
     "type": "graph",
     "description": "Number of bytes written to file descriptors. If the file is compressed, this will show compressed data size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read compressed bytes",
     "type": "graph",
     "description": "Number of bytes (the number of bytes before decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadCompressedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadCompressedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Read uncompressed bytes",
     "type": "graph",
     "description": "Number of uncompressed bytes (the number of bytes after decompression) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CompressedReadBufferBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Compressed blocks",
     "type": "graph",
     "description": "Number of compressed blocks (the blocks of data that are compressed independent of each other) read from compressed sources (files, network).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CompressedReadBufferBlocks{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBlocks{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Readonly replica",
     "type": "graph",
     "description": "Number of Replicated tables that are currently in readonly state due to re-initialization after ZooKeeper session loss or due to startup without ZooKeeper configured.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ReadonlyReplica{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part failed fetches",
     "type": "graph",
     "description": "Number of times a data part was failed to download from replica of a ReplicatedMergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part fetches",
     "type": "graph",
     "description": "Number of times a data part was downloaded from replica of a ReplicatedMergeTree table.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetches{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetches{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part fetches or merges",
     "type": "graph",
     "description": "Number of times we prefer to download already merged part from replica of ReplicatedMergeTree table instead of performing a merge ourself (usually we prefer doing a merge ourself to save network traffic). This happens when we have not all source parts to perform a merge or when the data part is old enough.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part merges",
     "type": "graph",
     "description": "Number of times data parts of ReplicatedMergeTree tables were successfully merged.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartMerges{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMerges{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Replicated part data loss",
     "type": "graph",
     "description": "Number of times a data part that we wanted doesn't exist on any replica (even on replicas that are offline right now). That data parts are definitely lost. This is normal due to asynchronous replication (if quorum inserts were not enabled), when the replica on which the data part was written was failed and when it became online after fail it doesn't contain that data part.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedDataLoss{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedDataLoss{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Merge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Merge",
     "type": "graph",
     "description": "Number of launched background merges.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Merge{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_Merge{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Merged rows",
     "type": "graph",
     "description": "Rows read for background merges. This is the number of rows before merge.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedRows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergedRows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Merge uncompressed bytes",
     "type": "graph",
     "description": "Uncompressed bytes (for columns as they stored in memory) that was read for background merges. This is the number before merge.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedUncompressedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergedUncompressedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Merge duration (avg)",
     "type": "graph",
     "description": "Avg merge duration",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_MergesTimeMilliseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Merge{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree rows",
     "type": "graph",
     "description": "Number of rows INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterRows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterRows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree blocks",
     "type": "graph",
     "description": "Number of blocks INSERTed to MergeTree tables. Each block forms a data part of level zero.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree uncompressed bytes",
     "type": "graph",
     "description": "Uncompressed bytes (for columns as they stored in memory) INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "MergeTree compressed bytes",
     "type": "graph",
     "description": "Bytes written to filesystem for data INSERTed to MergeTree tables.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Reserved space",
     "type": "graph",
     "description": "Disk space reserved for currently running background merges. It is slightly more than the total size of currently merging parts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DiskSpaceReservedForMerge{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uncompressed Cache Hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_UncompressedCacheHits{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_UncompressedCacheHits{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Uncompressed Cache Misses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_UncompressedCacheMisses{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_UncompressedCacheMisses{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Mark Cache Hits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheHits{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MarkCacheHits{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Mark Cache Misses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheMisses{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MarkCacheMisses{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Temporary",
     "type": "graph",
     "description": "The part is generating now, it is not in data_parts list.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsTemporary{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pre commited",
     "type": "graph",
     "description": "The part is in data_parts, but not used for SELECTs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsPreCommitted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Commited",
     "type": "graph",
     "description": "The part is in data_parts, but not used for SELECTs.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsCommitted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Outdated",
     "type": "graph",
     "description": "Not active data part, but could be used by only current SELECTs, could be deleted after SELECTs finishes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsOutdated{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Deleting",
     "type": "graph",
     "description": "Not active data part with identity refcounter, it is deleting right now by a cleaner.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsDeleting",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Delete on destroy",
     "type": "graph",
     "description": "Part was moved to another disk and should be deleted in own destructor.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsDeleteOnDestroy",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Wide",
     "type": "graph",
     "description": "Wide parts.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsWide{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Compact",
     "type": "graph",
     "description": "Compact parts.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_PartsCompact{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Send",
     "type": "graph",
     "description": "Number of connections to remote servers sending data that was INSERTed into Distributed tables. Both synchronous and asynchronous mode.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DistributedSend{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Files to insert",
     "type": "graph",
     "description": "Number of pending files to process for asynchronous insertion into Distributed tables. Number of files for every shard is summed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_DistributedFilesToInsert{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Distributed delayed inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedDelayedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedDelayedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed rejected inserts",
     "type": "graph",
     "description": "Number of times the INSERT of a block to a Distributed table was rejected with 'Too many bytes' exception due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedRejectedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedRejectedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed delayed inserts blocks (avg)",
     "type": "graph",
     "description": "Total number of milliseconds spent while the INSERT of a block to a Distributed table was throttled due to high number of pending bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_DistributedDelayedInsertsMilliseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_DistributedDelayedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) or (increase(ClickHouseProfileEvents_DistributedDelayedInserts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval])==0) * 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Distributed connection fail try",
     "type": "graph",
     "description": "Total count when distributed connection fails with retry",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedConnectionFailTry{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedConnectionFailTry{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed connection fail at all",
     "type": "graph",
     "description": "Total count when distributed connection fails after all retries finished",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedConnectionFailAtAll{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedConnectionFailAtAll{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Distributed sync insertation timeout",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_DistributedSyncInsertionTimeoutExceeded{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_DistributedSyncInsertionTimeoutExceeded{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "BackgroundPool task",
     "type": "graph",
     "description": "Number of active merges and mutations in an associated background pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundMergesAndMutationsPoolTask",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundFetchesPool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundFetchesPool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundFetchesPoolTask{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundMovePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundProcessingPool for moves",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundMovePoolTask{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundSchedulePool. This pool is used for periodic ReplicatedMergeTree tasks, like cleaning old data parts, altering data parts, replica re-initialization, etc.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundSchedulePoolTask{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundBufferFlushSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundBufferFlushSchedulePool. This pool is used for periodic Buffer flushes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundBufferFlushSchedulePoolTask{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundDistributedSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundDistributedSchedulePool. This pool is used for distributed sends that is done in background.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundDistributedSchedulePoolTask{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "BackgroundMessageBrokerSchedulePool task",
     "type": "graph",
     "description": "Number of active tasks in BackgroundProcessingPool for message streaming",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_BackgroundMessageBrokerSchedulePoolTask{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Init",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperInit{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperInit{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperTransactions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperTransactions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "List",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperList{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperList{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Create",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperCreate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperCreate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Remove",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperRemove{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperRemove{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Exists",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperExists{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperExists{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Get",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperGet{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperGet{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Set",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperSet{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperSet{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Multi",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperMulti{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperMulti{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Check",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperCheck{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperCheck{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Close",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperClose{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperClose{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Watch response",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperWatchResponse{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperWatchResponse{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "User Exceptions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperUserExceptions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperUserExceptions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Hardware Exceptions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperHardwareExceptions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperHardwareExceptions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperBytesReceived{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperBytesReceived{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ZooKeeperBytesSent{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ZooKeeperBytesSent{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "graph",
     "description": "Number of sessions (connections) to ZooKeeper. Should be no more than one, because using more than one connection to ZooKeeper may lead to bugs due to lack of linearizability (stale reads) that ZooKeeper consistency model allows.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ZooKeeperSession",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ephemeral Node",
     "type": "graph",
     "description": "Number of ephemeral nodes hold in ZooKeeper.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_EphemeralNode",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Watches",
     "type": "graph",
     "description": "Number of watches (event subscriptions) in ZooKeeper.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ZooKeeperWatch",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "description": "Number of requests to ZooKeeper in fly.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ClickHouseMetrics_ZooKeeperRequest",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Remove ephemeral node failed",
     "type": "graph",
     "description": "Number of times an error happened while trying to remove ephemeral node. This is not an issue, because our implementation of ZooKeeper library guarantee that the session will expire and the node will be removed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CannotRemoveEphemeralNode{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_CannotRemoveEphemeralNode{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Insights",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Slow Queries (>1s) — 5m rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_SlowQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[5m])",
     "legendFormat": "{{{{pod}}}}"
    }
   ]
  },
  {
   "title": "Query Latency P99 / P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (pod, le) (rate(ClickHouseProfileEvents_QueryTimeMicroseconds_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[5m]))) / 1000",
     "legendFormat": "p99 {{{{pod}}}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (pod, le) (rate(ClickHouseProfileEvents_QueryTimeMicroseconds_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[5m]))) / 1000",
     "legendFormat": "p95 {{{{pod}}}}"
    }
   ]
  },
  {
   "title": "Query Memory Tracking vs Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "query mem tracking {{{{pod}}}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_MemoryResident{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "resident mem {{{{pod}}}}"
    }
   ]
  },
  {
   "title": "Failed Queries — 5m rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_FailedQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[5m])",
     "legendFormat": "failed {{{{pod}}}}"
    },
    {
     "expr": "increase(ClickHouseProfileEvents_FailedSelectQuery{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[5m])",
     "legendFormat": "failed SELECT {{{{pod}}}}"
    }
   ]
  },
  {
   "title": "Keeper Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Keeper Leader Elections — 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_KeeperLeaderElections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[5m])",
     "legendFormat": "leader elections {{{{pod}}}}"
    }
   ]
  },
  {
   "title": "Keeper Request Latency (avg/max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_KeeperAvgLatency{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "avg latency {{{{pod}}}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_KeeperMaxLatency{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "max latency {{{{pod}}}}"
    }
   ]
  },
  {
   "title": "Keeper Connections & Outstanding Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_KeeperAliveConnections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "alive connections {{{{pod}}}}"
    },
    {
     "expr": "ClickHouseMetrics_KeeperOutstandingRequests{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "outstanding requests {{{{pod}}}}"
    }
   ]
  },
  {
   "title": "System Resources (AsyncMetrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 }
  },
  {
   "title": "Resident Memory (Physical RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_MemoryResident{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "RSS {{pod}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_MemoryVirtual{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "Virtual {{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage (default disk)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_DiskUsed_default{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "Used {{{{pod}}}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_DiskTotal_default{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "Total {{{{pod}}}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_DiskAvailable_default{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "Available {{{{pod}}}}"
    }
   ]
  },
  {
   "title": "CPU Usage (User + System Time rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(ClickHouseAsyncMetrics_OSUserTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[5m])",
     "legendFormat": "User CPU {{{{pod}}}}"
    },
    {
     "expr": "rate(ClickHouseAsyncMetrics_OSSystemTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}[5m])",
     "legendFormat": "System CPU {{{{pod}}}}"
    }
   ]
  },
  {
   "title": "MergeTree Tables — Bytes on Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_TotalBytesOfMergeTreeTables{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "Data bytes {{{{pod}}}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_TotalPrimaryKeyBytesInMemory{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", apps_kubeblocks_io_component_name=~\"$component\", pod=~\"$instance\"}",
     "legendFormat": "PK in memory {{{{pod}}}}"
    }
   ]
  }
 ]
}