apiVersion: v1
kind: ConfigMap
metadata:
  name: openviking-config-template-{{ .Values.addonChartVersion }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ov.conf: |-
    {{ .Values.config | toJson }}
