apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: openviking-verticalscaling
  namespace: demo
spec:
  # Specifies the name of the Cluster resource that this operation is targeting.
  clusterName: openviking-cluster
  type: VerticalScaling
  verticalScaling:
    - componentName: openviking
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 4Gi
