apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: openviking-volumeexpansion
  namespace: demo
spec:
  # Specifies the name of the Cluster resource that this operation is targeting.
  clusterName: openviking-cluster
  type: VolumeExpansion
  volumeExpansion:
    - componentName: openviking
      volumeClaimTemplates:
        - name: data
          storage: 50Gi
