apiVersion: apps.kubeblocks.io/v1
kind: ClusterDefinition
metadata:
  name: hadoop
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
  annotations:
    {{- include "hadoop.apiVersion" . | nindent 4 }}
spec:
  topologies:
    - name: standalone
      components:
        - name: namenode
          compDef: {{ include "hadoop.hdfsNamenodeStandaloneCmpdRegexPattern" . }}
        - name: datanode
          compDef: {{ include "hadoop.hdfsDatanodeStandaloneCmpdRegexPattern" . }}
      orders:
        provision:
          - namenode
          - datanode
        terminate:
          - datanode
          - namenode
    - name: cluster
      default: true
      components:
        - name: journalnode
          compDef: {{ include "hadoop.hdfsJournalnodeCmpdRegexPattern" . }}
        - name: namenode
          compDef: {{ include "hadoop.hdfsNamenodeCmpdRegexPattern" . }}
        - name: datanode
          compDef: {{ include "hadoop.hdfsDatanodeCmpdRegexPattern" . }}
      orders:
        provision:
          - journalnode
          - namenode
          - datanode
        terminate:
          - datanode
          - namenode
          - journalnode
