apiVersion: apps.kubeblocks.io/v1
kind: ComponentDefinition
metadata:
  name: hadoop-core
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
  annotations:
    {{- include "hadoop.apiVersion" . | nindent 4 }}
spec:
  provider: kubeblocks
  description: {{ .Chart.Description }}
  serviceKind: hadoop-core
  serviceRefDeclarations:
    - name: hadoopZookeeper
      serviceRefDeclarationSpecs:
        - serviceKind: zookeeper
          serviceVersion: "^*"
  runtime:
    containers:
      - name: hadoop-core
        image: {{ include "hadoop.coreImage" . | quote }}
        imagePullPolicy: {{ .Values.core.image.pullPolicy }}
        env:
          - name: DEBUG_MODEL
            value: {{ .Values.runtime.debug | quote }}
        volumeMounts:
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/core-site.xml
            subPath: core-site.xml
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/log4j.properties
            subPath: log4j.properties
    securityContext:
      runAsGroup: {{ .Values.securityContext.runAsGroup }}
      runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
      runAsUser: {{ .Values.securityContext.runAsUser }}
  updateStrategy: {{ .Values.updateStrategy }}
  vars:
    - name: CLUSTER_NAME
      valueFrom:
        clusterVarRef:
          clusterName: Required
    - name: NAMESPACE
      valueFrom:
        clusterVarRef:
          namespace: Required
    - name: ZOOKEEPER_ENDPOINTS
      valueFrom:
        serviceRefVarRef:
          name: hadoopZookeeper
          endpoint: Required
  configs:
    - name: hadoop-core-config
      template: hadoop-core-config-template
      volumeName: hadoop-core-config
      namespace: {{ .Release.Namespace }}
      defaultMode: {{ .Values.config.defaultMode }}
