apiVersion: apps.kubeblocks.io/v1
kind: ComponentDefinition
metadata:
  name: hdfs-datanode
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
  annotations:
    {{- include "hadoop.apiVersion" . | nindent 4 }}
spec:
  provider: kubeblocks
  description: {{ .Chart.Description }}
  serviceKind: hdfs-datanode
  runtime:
    hostNetwork: {{ .Values.runtime.datanode.hostNetwork }}
    hostPID: {{ .Values.runtime.datanode.hostPID }}
    dnsPolicy: {{ .Values.runtime.datanode.dnsPolicy }}
    terminationGracePeriodSeconds: 300
    initContainers:
      - name: hadoop-common
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: {{ .Values.securityContext.initRunAsUser }}
        command:
          - /bin/bash
        args:
          - -ec
          - |
            cp -r {{ .Values.runtime.hadoopSoftwareDir }}/* {{ .Values.runtime.hadoopHome }}
            mkdir -p {{ .Values.hdfs.paths.datanodeDataDir }}
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} {{ .Values.runtime.hadoopHome }}
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }} {{ .Values.hdfs.paths.datanodeDataDir }}
        volumeMounts:
          - name: hadoop-common
            mountPath: {{ .Values.runtime.hadoopHome }}
          - name: hdfs-data-0
            mountPath: {{ .Values.hdfs.paths.datanodeDataDir }}
            subPath: data0
    containers:
      - name: hdfs-datanode
        image: {{ include "hadoop.dataNodeImage" . | quote }}
        imagePullPolicy: {{ .Values.dataNode.image.pullPolicy }}
        command:
          - /bin/bash
          - {{ .Values.runtime.scriptsDir }}/start-datanode.sh
        env:
          - name: DEBUG_MODEL
            value: {{ .Values.runtime.debug | quote }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_FQDN
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['kubeblocks.io/pod-fqdn']
          - name: HADOOP_HOME
            value: {{ .Values.runtime.hadoopHome }}
          - name: HADOOP_CONF_DIR
            value: {{ .Values.runtime.configDir }}
          - name: HADOOP_LOG_DIR
            value: {{ .Values.runtime.hadoopLogDir }}
        ports:
          - containerPort: {{ .Values.hdfs.ports.datanode.data }}
            name: data
          - containerPort: {{ .Values.hdfs.ports.datanode.ipc }}
            name: ipc
          - containerPort: {{ .Values.hdfs.ports.datanode.http }}
            name: http
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          exec:
            command:
              - /bin/bash
              - {{ .Values.runtime.scriptsDir }}/check-data-status.sh
        livenessProbe:
          failureThreshold: {{ .Values.probes.datanode.liveness.failureThreshold }}
          initialDelaySeconds: {{ .Values.probes.datanode.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.datanode.liveness.periodSeconds }}
          successThreshold: 1
          timeoutSeconds: {{ .Values.probes.datanode.liveness.timeoutSeconds }}
          exec:
            command:
              - /bin/bash
              - {{ .Values.runtime.scriptsDir }}/check-data-status.sh
        readinessProbe:
          failureThreshold: {{ .Values.probes.datanode.readiness.failureThreshold }}
          initialDelaySeconds: {{ .Values.probes.datanode.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.datanode.readiness.periodSeconds }}
          successThreshold: 1
          timeoutSeconds: {{ .Values.probes.datanode.readiness.timeoutSeconds }}
          exec:
            command:
              - /bin/bash
              - {{ .Values.runtime.scriptsDir }}/check-data-status.sh
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - {{ .Values.runtime.scriptsDir }}/datanode-decommission.sh
        volumeMounts:
          - name: hadoop-common
            mountPath: {{ .Values.runtime.hadoopHome }}
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/core-site.xml
            subPath: core-site.xml
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/hadoop-env.sh
            subPath: hadoop-env.sh
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/hadoop-metrics2.properties
            subPath: hadoop-metrics2.properties
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/dfs.include
            subPath: dfs.include
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/dfs.exclude
            subPath: dfs.exclude
          - name: datanode-config
            mountPath: {{ .Values.runtime.configDir }}/hdfs-site.xml
            subPath: hdfs-site.xml
          - name: datanode-config
            mountPath: {{ .Values.runtime.configDir }}/log4j.properties
            subPath: log4j.properties
          - name: hdfs-data-0
            mountPath: {{ .Values.hdfs.paths.datanodeDataDir }}
            subPath: data0
          - name: hadoop-logs
            mountPath: {{ .Values.runtime.hadoopLogDir }}
          - name: scripts
            mountPath: {{ .Values.runtime.scriptsDir }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          privileged: {{ .Values.securityContext.privileged }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          capabilities:
{{ toYaml .Values.securityContext.capabilities | nindent 12 }}
          seccompProfile:
{{ toYaml .Values.securityContext.seccompProfile | nindent 12 }}
    securityContext:
      fsGroupChangePolicy: {{ .Values.securityContext.fsGroupChangePolicy }}
      fsGroup: {{ .Values.securityContext.fsGroup }}
    volumes:
      - name: hadoop-common
        emptyDir: {}
      - name: hadoop-logs
        emptyDir: {}
  updateStrategy: {{ .Values.updateStrategy }}
  vars:
    - name: CLUSTER_NAME
      valueFrom:
        clusterVarRef:
          clusterName: Required
    - name: NAMESPACE
      valueFrom:
        clusterVarRef:
          namespace: Required
    - name: CLUSTER_DOMAIN
      value: {{ .Values.extra.clusterDomain }}
    - name: HDFS_CONF_DIR
      value: {{ .Values.runtime.configDir }}
    - name: NAMENODE_POD_FQDN_LIST
      valueFrom:
        componentVarRef:
          compDef: hdfs-namenode
          optional: false
          podFQDNs: Required
    - name: HDFS_DATANODE_DATA_DIR
      value: {{ .Values.hdfs.paths.datanodeDataDir | quote }}
    - name: HDFS_DATANODE_HANDLER_COUNT
      value: {{ .Values.hdfs.datanode.handlerCount | quote }}
    - name: HDFS_NAMENODE_RPC_PORT
      value: {{ .Values.hdfs.ports.namenode.rpc | quote }}
    - name: HDFS_NAMENODE_HTTP_PORT
      value: {{ .Values.hdfs.ports.namenode.http | quote }}
    - name: HDFS_REPLICATION
      value: {{ .Values.hdfs.replication | quote }}
    - name: HDFS_CLIENT_REPLACE_DATANODE_ON_FAILURE_POLICY
      value: {{ .Values.hdfs.client.replaceDatanodeOnFailurePolicy | quote }}
    - name: HDFS_PERMISSIONS_ENABLED
      value: {{ .Values.hdfs.permissions.enabled | quote }}
    - name: POD_FQDN
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['kubeblocks.io/pod-fqdn']
          apiVersion: v1
  configs:
    - name: datanode-config
      template: datanode-config-template
      volumeName: datanode-config
      namespace: {{ .Release.Namespace }}
      defaultMode: {{ .Values.config.defaultMode }}
  scripts:
    - name: hadoop-scripts
      template: hadoop-scripts
      volumeName: scripts
      namespace: {{ .Release.Namespace }}
      defaultMode: {{ .Values.scripts.defaultMode }}
