apiVersion: apps.kubeblocks.io/v1
kind: ComponentDefinition
metadata:
  name: hadoop-core
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
  annotations:
    {{- include "hadoop.apiVersion" . | nindent 4 }}
spec:
  provider: kubeblocks
  description: {{ .Chart.Description }}
  serviceKind: hadoop-core
  serviceRefDeclarations:
    - name: hadoopZookeeper
      serviceRefDeclarationSpecs:
        - serviceKind: zookeeper
          serviceVersion: "^*"
  runtime:
    containers:
      - name: hadoop-core
        image: {{ include "hadoop.coreImage" . | quote }}
        imagePullPolicy: {{ .Values.core.image.pullPolicy }}
        env:
          - name: DEBUG_MODEL
            value: {{ .Values.runtime.debug | quote }}
        volumeMounts:
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/core-site.xml
            subPath: core-site.xml
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/hadoop-env.sh
            subPath: hadoop-env.sh
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/log4j.properties
            subPath: log4j.properties
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/dfs.include
            subPath: dfs.include
          - name: hadoop-core-config
            mountPath: {{ .Values.runtime.configDir }}/dfs.exclude
            subPath: dfs.exclude
    securityContext:
      runAsGroup: {{ .Values.securityContext.runAsGroup }}
      runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
      runAsUser: {{ .Values.securityContext.runAsUser }}
  updateStrategy: {{ .Values.updateStrategy }}
  vars:
    - name: CLUSTER_NAME
      valueFrom:
        clusterVarRef:
          clusterName: Required
    - name: NAMESPACE
      valueFrom:
        clusterVarRef:
          namespace: Required
    - name: CLUSTER_DOMAIN
      value: {{ .Values.extra.clusterDomain }}
    - name: HDFS_CONF_DIR
      value: {{ .Values.runtime.configDir }}
    - name: ZOOKEEPER_ENDPOINTS
      valueFrom:
        serviceRefVarRef:
          name: hadoopZookeeper
          endpoint: Required
    - name: HDFS_TRASH_INTERVAL
      value: {{ .Values.hdfs.trash.interval | quote }}
    - name: HDFS_HA_ZOOKEEPER_PARENT_ZNODE
      value: {{ .Values.hdfs.ha.zookeeper.parentZnodePrefix | quote }}
    - name: HDFS_HA_ZOOKEEPER_SESSION_TIMEOUT_MS
      value: {{ .Values.hdfs.ha.zookeeper.sessionTimeoutMs | quote }}
    - name: HDFS_IPC_CLIENT_CONNECTION_MAX_IDLE_TIME_MS
      value: {{ .Values.hdfs.ipc.clientConnectionMaxIdleTimeMs | quote }}
    - name: HDFS_IPC_CLIENT_CONNECT_TIMEOUT_MS
      value: {{ .Values.hdfs.ipc.clientConnectTimeoutMs | quote }}
    - name: HDFS_IPC_CLIENT_CONNECTION_POOL_SIZE
      value: {{ .Values.hdfs.ipc.clientConnectionPoolSize | quote }}
    - name: HDFS_IPC_CLIENT_CONNECT_RETRY_INTERVAL_MS
      value: {{ .Values.hdfs.ipc.clientConnectRetryIntervalMs | quote }}
    - name: HDFS_IPC_CLIENT_PING
      value: {{ .Values.hdfs.ipc.clientPing | quote }}
    - name: HDFS_IPC_PING_INTERVAL_MS
      value: {{ .Values.hdfs.ipc.pingIntervalMs | quote }}
    - name: HDFS_NAMENODE_HEAP
      value: {{ .Values.hdfs.jvm.namenodeHeapSize | quote }}
    - name: HDFS_DATANODE_HEAP
      value: {{ .Values.hdfs.jvm.datanodeHeapSize | quote }}
    - name: HDFS_JOURNALNODE_HEAP
      value: {{ .Values.hdfs.jvm.journalnodeHeapSize | quote }}
    - name: HDFS_ZKFC_HEAP
      value: {{ .Values.hdfs.jvm.zkfcHeapSize | quote }}
  configs:
    - name: hadoop-core-config
      template: hadoop-core-config-template
      volumeName: hadoop-core-config
      namespace: {{ .Release.Namespace }}
      defaultMode: {{ .Values.config.defaultMode }}
