apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  name: hadoop-core
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
  annotations:
    {{- include "hadoop.apiVersion" . | nindent 4 }}
spec:
  compatibilityRules:
    - releases:
        - v3.3.4
      compDefs:
        - hadoop-core
  releases:
    - name: v3.3.4
      serviceVersion: v3.3.4
      images:
        hadoop-core: {{ include "hadoop.coreImage" . | quote }}