apiVersion: v1
kind: ConfigMap
metadata:
  name: namenode-standalone-config-template
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
data:
  hdfs-site.xml: |-
    {{- .Files.Get "config/hdfs-namenode-standalone.tpl" | nindent 4 }}
  log4j.properties: |-
    {{- .Files.Get "config/log4j.properties" | nindent 4 }}
