apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-scripts
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
data:
  check-journal-status.sh: |-
    {{- .Files.Get "scripts/check-journal-status.sh" | nindent 4 }}
  check-name-status.sh: |-
    {{- .Files.Get "scripts/check-name-status.sh" | nindent 4 }}
  check-data-status.sh: |-
    {{- .Files.Get "scripts/check-data-status.sh" | nindent 4 }}
  start-namenode.sh: |-
    {{- .Files.Get "scripts/start-namenode.sh" | nindent 4 }}
  start-zkfc.sh: |-
    {{- .Files.Get "scripts/start-zkfc.sh" | nindent 4 }}
  start-journalnode.sh: |-
    {{- .Files.Get "scripts/start-journalnode.sh" | nindent 4 }}
  start-datanode.sh: |-
    {{- .Files.Get "scripts/start-datanode.sh" | nindent 4 }}
  init-namenode-format.sh: |-
    {{- .Files.Get "scripts/init-namenode-format.sh" | nindent 4 }}
  init-zkfc-format.sh: |-
    {{- .Files.Get "scripts/init-zkfc-format.sh" | nindent 4 }}
  init-refresh-nodes.sh: |-
    {{- .Files.Get "scripts/init-refresh-nodes.sh" | nindent 4 }}
  refresh-decommission-state.sh: |-
    {{- .Files.Get "scripts/refresh-decommission-state.sh" | nindent 4 }}
  datanode-decommission.sh: |-
    {{- .Files.Get "scripts/datanode-decommission.sh" | nindent 4 }}
