apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParametersDefinition
metadata:
  name: hdfs-common-standalone-config-constraints
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
spec:
  componentDef: ^hdfs-(namenode|datanode)-standalone$
  templateName: hdfs-common-standalone-config-template
  fileName: core-site.xml
  fileFormatConfig:
    format: xml
  parametersSchema:
    topLevelKey: HDFSCommonParameter
    cue: |-
      {{- .Files.Get "config/hdfs-common-config-constraint.cue" | nindent 6 }}
