apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParamConfigRenderer
metadata:
  name: hadoop-core-config-renderer
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
  annotations:
    {{- include "hadoop.annotations" . | nindent 4 }}
spec:
  componentDef: hadoop-core
  parametersDefs:
    - hadoop-core-config-constraints
  configs:
    - name: core-site.xml
      fileFormatConfig:
        format: xml