apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParamConfigRenderer
metadata:
  name: hdfs-journalnode-config-renderer
  labels:
    {{- include "hadoop.labels" . | nindent 4 }}
  annotations:
    {{- include "hadoop.annotations" . | nindent 4 }}
spec:
  componentDef: hdfs-journalnode
  parametersDefs:
    - hdfs-common-config-constraints
    - journalnode-config-constraints
  configs:
    - name: core-site.xml
      fileFormatConfig:
        format: xml
    - name: hdfs-site.xml
      fileFormatConfig:
        format: xml
