apiVersion: apps.kubeblocks.io/v1
kind: ClusterDefinition
metadata:
  name: clickhouse
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
  annotations:
    {{- include "clickhouse.apiVersion" . | nindent 4 }}
spec:
  topologies:
    - name: standalone
      shardings:
        - name: clickhouse
          shardingDef: clickhouse
    - name: cluster
      components:
        - name: ch-keeper
          compDef: {{ include "clickhouse-keeper.cmpdRegexpPattern" .}}
      shardings:
        - name: clickhouse
          shardingDef: clickhouse
      orders:
        provision:
          - ch-keeper
          - clickhouse
    - name: standalone-with-readonly
      components:
        - name: clickhouse-ro
          compDef: {{ include "clickhouse-readonly.cmpdRegexpPattern" .}}
      shardings:
        - name: clickhouse
          shardingDef: clickhouse
      orders:
        provision:
          - clickhouse
          - clickhouse-ro
    - name: cluster-with-readonly
      components:
        - name: ch-keeper
          compDef: {{ include "clickhouse-keeper.cmpdRegexpPattern" .}}
        - name: clickhouse-ro
          compDef: {{ include "clickhouse-readonly.cmpdRegexpPattern" .}}
      shardings:
        - name: clickhouse
          shardingDef: clickhouse
      orders:
        provision:
          - ch-keeper
          - clickhouse
          - clickhouse-ro
