apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vanilla-postgresql.scriptsTemplate" . }}
  labels:
    {{- include "vanilla-postgresql.labels" . | nindent 4 }}
  annotations:
    {{- include "vanilla-postgresql.annotations" . | nindent 4 }}
data:
  {{- include "vanilla-postgresql.extend.scripts" . | nindent 2 }}
  update-parameter.sh: |-
    {{- .Files.Get "reloader/update-parameter.sh" | nindent 4 }}
