{
 "title": "kubeblocks-controlller-manager",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Resource & Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"kb-system\", job=\"kubeblocks\"}/1024/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"kb-system\", job=\"kubeblocks\"}/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Groutine Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"kb-system\", job=\"kubeblocks\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace='kb-system'}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{namespace=\"kb-system\", job=\"kubeblocks\"}[5m])\n/\nrate(go_gc_duration_seconds_count{namespace=\"kb-system\", job=\"kubeblocks\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controller Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Reconciliation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job='kubeblocks',namespace=\"kb-system\", job=\"kubeblocks\"}[5m])) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{namespace=\"kb-system\", job=\"kubeblocks\"}[5m])) \nby (controller, result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Concurrent Reconciles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_runtime_max_concurrent_reconciles{namespace=\"kb-system\", job=\"kubeblocks\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation Duration (P99)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(controller_runtime_reconcile_time_seconds_bucket{namespace=\"kb-system\", job=\"kubeblocks\"}[5m])) \n  by (le, controller)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Processing Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(workqueue_work_duration_seconds_bucket{namespace=\"kb-system\", job=\"kubeblocks\"}[5m])) \n  by (le, name)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(workqueue_retries_total{namespace=\"kb-system\", job=\"kubeblocks\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unfinished Work",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{namespace=\"kb-system\", job=\"kubeblocks\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "workqueue_depth{namespace=\"kb-system\", job=\"kubeblocks\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}