status = warn
name = HBaseLog4j2Config

property.hbase.log.dir = ${sys:hbase.log.dir:-/var/log/hbase}
property.hbase.log.file = ${sys:hbase.log.file:-hbase.log}

appenders = console, rolling, security, http

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %-5p [%t] %c{2}: %m%n

appender.rolling.type = RollingRandomAccessFile
appender.rolling.name = RollingFileAppender
appender.rolling.fileName = ${hbase.log.dir}/${hbase.log.file}
appender.rolling.filePattern = ${hbase.log.dir}/${hbase.log.file}.%i
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{ISO8601} %-5p [%t] %c{2}: %m%n
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 256MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 20

appender.security.type = RollingRandomAccessFile
appender.security.name = SecurityAppender
appender.security.fileName = ${hbase.log.dir}/security.log
appender.security.filePattern = ${hbase.log.dir}/security.log.%i
appender.security.layout.type = PatternLayout
appender.security.layout.pattern = %d{ISO8601} %p %c: %m%n
appender.security.policies.type = Policies
appender.security.policies.size.type = SizeBasedTriggeringPolicy
appender.security.policies.size.size = 64MB
appender.security.strategy.type = DefaultRolloverStrategy
appender.security.strategy.max = 10

appender.http.type = RollingRandomAccessFile
appender.http.name = HttpAppender
appender.http.fileName = ${hbase.log.dir}/http-access.log
appender.http.filePattern = ${hbase.log.dir}/http-access.log.%i
appender.http.layout.type = PatternLayout
appender.http.layout.pattern = %m%n
appender.http.policies.type = Policies
appender.http.policies.size.type = SizeBasedTriggeringPolicy
appender.http.policies.size.size = 64MB
appender.http.strategy.type = DefaultRolloverStrategy
appender.http.strategy.max = 10

rootLogger.level = info
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.rolling.ref = RollingFileAppender

logger.zookeeper.name = org.apache.zookeeper
logger.zookeeper.level = warn

logger.recoverablezk.name = org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper
logger.recoverablezk.level = warn

logger.zkutil.name = org.apache.hadoop.hbase.zookeeper.ZKUtil
logger.zkutil.level = warn

logger.hbaseconfig.name = org.apache.hadoop.hbase.HBaseConfiguration
logger.hbaseconfig.level = info

logger.security.name = SecurityLogger
logger.security.level = info
logger.security.additivity = false
logger.security.appenderRef.security.ref = SecurityAppender

logger.http.name = http.requests.hbase
logger.http.level = info
logger.http.additivity = false
logger.http.appenderRef.http.ref = HttpAppender
