{
 "title": "Mariadb",
 "tags": [
  "mariadb",
  "db"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(mariadb_up{job=\"$job\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mariadb_up{job=\"$job\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(mariadb_up{job=\"$job\",namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, pod)"
    }
   },
   { "name": "job", "label": "job", "query": "kubeblocks-service,agamotto" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Min Uptime",
   "type": "stat",
   "description": "**Uptime**\n\nThe amount of time since the last restart of the mariadb server process.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "min(sum(mariadb_global_status_uptime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Total QPS",
   "type": "stat",
   "description": "**Current QPS**\n\nBased on the queries reported by mariadb's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(mariadb_global_status_queries{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool",
   "type": "stat",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of mariadb tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "min(sum(mariadb_global_variables_innodb_buffer_pool_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Clusters && Instances",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(mariadb_global_status_uptime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(mariadb_global_status_queries{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "10m",
     "expr": "sum(mariadb_global_variables_innodb_buffer_pool_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mariadb Connections",
   "type": "timeseries",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mariadbd requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmariadbd actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the mariadb server.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mariadb_global_status_threads_connected{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Connections | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mariadb_global_status_max_used_connections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Max Used Connections | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mariadb_global_variables_max_connections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Max Connections | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "mariadb Client Thread Activity",
   "type": "timeseries",
   "description": "**mariadb Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mariadb_global_status_threads_connected{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Peak Threads Connected | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(max_over_time(mariadb_global_status_threads_running{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Peak Threads Running | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(avg_over_time(mariadb_global_status_threads_running{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Avg Threads Running | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "mariadb Thread Cache",
   "type": "timeseries",
   "description": "**mariadb Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in mariadb 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(mariadb_global_variables_thread_cache_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Thread Cache Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(mariadb_global_status_threads_cached{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Threads Cached | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_threads_created{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Threads Created | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "mariadb Aborted Connections",
   "type": "timeseries",
   "description": "**Aborted Connections**\n\nWhen a given host connects to mariadb and the connection is interrupted in the middle (for example due to bad credentials), mariadb keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mariadbd assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_aborted_connects{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Aborted Connects (attempts) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_aborted_clients{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Aborted Clients (timeout) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mariadb Questions",
   "type": "timeseries",
   "description": "**mariadb Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_questions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "mariadb Slow Queries",
   "type": "timeseries",
   "description": "**mariadb Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_slow_queries{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Slow Queries | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "mariadb Select Types",
   "type": "timeseries",
   "description": "**mariadb Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means mariadb scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_select_full_join{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Select Full Join | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_select_full_range_join{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Select Full Range Join | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_select_range{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Select Range | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_select_range_check{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Select Range Check | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_select_scan{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Select Scan | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "mariadb Sort Rows",
   "type": "timeseries",
   "description": "**mariadb Sorts**\n\nDue to a query's structure, order, or other requirements, mariadb sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, mariadb then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_sort_rows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Sort Rows | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_sort_range{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Sort Range | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_sort_merge_passes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Sort Merge Passes | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_sort_scan{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Sort Scan | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "mariadb Temporary Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_created_tmp_tables{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Created Tmp Tables | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_created_tmp_disk_tables{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Created Tmp Disk Tables | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(mariadb_global_status_created_tmp_files{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Created Tmp Files | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Command, Handlers, Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Top Command Counters",
     "type": "timeseries",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mariadb.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mariadb.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mariadb.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mariadb.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(15, rate(mariadb_global_status_commands_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])>0)",
       "legendFormat": "Com_{{ command }} | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "mariadb Handlers",
     "type": "timeseries",
     "description": "**mariadb Handlers**\n\nHandler statistics are internal statistics on how mariadb is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and mariadb.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mariadb_global_status_handlers_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",handler!~\"commit|rollback|savepoint.*|prepare\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod,handler)",
       "legendFormat": "{{ handler }} | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "mariadb Transaction Handlers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mariadb_global_status_handlers_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",handler=~\"commit|rollback|savepoint.*|prepare\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod,handler)",
       "legendFormat": "{{ handler }} | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "**mariadb Network Traffic**\n\nHere we can see how much network traffic is generated by mariadb. Outbound is network traffic sent from mariadb and Inbound is network traffic mariadb has received.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mariadb_global_status_bytes_received{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Inbound | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mariadb_global_status_bytes_sent{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Outbound | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Buffers Pool Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mariadb_global_status_innodb_buffer_pool_read_requests{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Disk Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mariadb_global_status_innodb_buffer_pool_reads{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Buffers Pool Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mariadb_global_status_innodb_buffer_pool_write_requests{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Buffer Pool Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mariadb_global_status_innodb_page_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} * on (namespace,app_kubernetes_io_instance,pod) mariadb_global_status_buffer_pool_pages{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", state=\"data\",job=\"$job\"}",
       "legendFormat": "Data | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "mariadb_global_status_innodb_page_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} * on (namespace,app_kubernetes_io_instance,pod) mariadb_global_status_buffer_pool_pages{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", state=\"free\",job=\"$job\"}",
       "legendFormat": "Free | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "mariadb_global_status_innodb_page_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} * on (namespace,app_kubernetes_io_instance,pod) mariadb_global_status_buffer_pool_pages{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", state=\"dirty\",job=\"$job\"}",
       "legendFormat": "Dirty | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "mariadb_global_status_innodb_page_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} * on (namespace,app_kubernetes_io_instance,pod) mariadb_global_status_buffer_pool_pages{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", state=\"misc\",job=\"$job\"}",
       "legendFormat": "Misc | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "mariadb_global_status_innodb_page_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} * on (namespace,app_kubernetes_io_instance,pod) mariadb_global_status_buffer_pool_dirty_pages{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
       "legendFormat": "Dirty | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Other Buffers Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(mariadb_global_variables_innodb_log_buffer_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "InnoDB Log Buffer Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(mariadb_global_variables_innodb_additional_mem_pool_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "InnoDB Additional Memory Pool Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(mariadb_global_status_innodb_mem_dictionary{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "InnoDB Dictionary Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(mariadb_global_variables_key_buffer_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Key Buffer Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(mariadb_global_variables_query_cache_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Query Cache Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(mariadb_global_status_innodb_mem_adaptive_hash{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Adaptive Hash Index Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(mariadb_global_variables_tokudb_cache_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "TokuDB Cache Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "mariadb Table Locks",
     "type": "timeseries",
     "description": "**Table Locks**\n\nmariadb takes a number of different locks for varying reasons. In this graph we see how many Table level locks mariadb has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mariadb_global_status_table_locks_immediate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Table Locks Immediate | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(rate(mariadb_global_status_table_locks_waited{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Table Locks Waited | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Innodb Row Lock Waits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mariadb_global_status_innodb_row_lock_waits{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Innodb Row Lock Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(mariadb_global_status_innodb_row_lock_time{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod) / sum(rate(mariadb_global_status_innodb_row_lock_waits{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Files and Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "mariadb Open Files",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_global_status_open_files{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Open Files | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_global_variables_open_files_limit{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Open Files Limit | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(mariadb_global_status_innodb_num_open_files{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "InnoDB Open Files | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "mariadb Open Tables",
     "type": "timeseries",
     "description": "**mariadb Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized mariadb 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_global_status_open_tables{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Open Tables | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_global_variables_table_open_cache{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Table Open Cache | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "mariadb Table Definition Cache",
     "type": "timeseries",
     "description": "**mariadb Table Definition Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized mariadb 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_global_status_open_table_definitions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Open Table Definitions | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_global_variables_table_definition_cache{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Table Definitions Cache Size | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(rate(mariadb_global_status_opened_table_definitions{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Opened Table Definitions | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "mariadb Table Open Cache",
     "type": "timeseries",
     "description": "**mariadb Table Open Cache**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized mariadb 5.6 and above (ie: do not set them to any value).",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(mariadb_global_status_table_open_cache_hits{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Hits | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(rate(mariadb_global_status_table_open_cache_misses{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Misses | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "expr": "sum(rate(mariadb_global_status_table_open_cache_overflows{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "Misses due to Overflows | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ApeCloud mariadb Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commit Index",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_info_schema_wesql_consensus_commit_index{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod,instance_role)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{instance_role}}"
      }
     ]
    },
    {
     "title": "Last Log Index",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_info_schema_wesql_consensus_last_log_index{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod,instance_role)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{instance_role}}"
      }
     ]
    },
    {
     "title": "Last Apply Index",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_info_schema_wesql_consensus_last_apply_index{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod,instance_role)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{instance_role}}"
      }
     ]
    },
    {
     "title": "Current Term",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_info_schema_wesql_consensus_current_term{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod,instance_role)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{instance_role}}"
      }
     ]
    },
    {
     "title": "Last Log Term",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mariadb_info_schema_wesql_consensus_last_log_term{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod,instance_role)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{instance_role}}"
      }
     ]
    }
   ]
  }
 ]
}