apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openviking.configTemplate" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openviking.labels" . | nindent 4 }}
  annotations:
    {{- include "openviking.apiVersion" . | nindent 4 }}
data:
  {{ .Values.configFileName }}: |-
    {{- tpl (.Files.Get "config/ov.conf.tpl") . | nindent 4 }}
