apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParamConfigRenderer
metadata:
  name: {{ include "openviking.pcrName" . }}
  labels:
    {{- include "openviking.labels" . | nindent 4 }}
spec:
  componentDef: {{ include "openviking.cmpdName" . }}
  configs:
    - name: {{ .Values.configFileName }}
      templateName: config
      fileFormatConfig:
        format: json
  parametersDefs:
    - {{ include "openviking.paramsDefName" . }}
