apiVersion: apps.kubeblocks.io/v1
kind: ClusterDefinition
metadata:
  name: elasticsearch
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    {{- include "elasticsearch.annotations" . | nindent 4 }}
spec:
  topologies:
  - name: single-node
    components:
    - name: mdit
      compDef: {{ include "elasticsearchMdit.cmpdRegexPattern" . }}
  - name: multi-node
    default: true
    components:
    - name: master
      compDef: {{ include "elasticsearchMaster.cmpdRegexPattern" . }}
    - name: data
      compDef: {{ include "elasticsearchData.cmpdRegexPattern" . }}
    - name: kibana
      compDef: {{ include "kibana.cmpdRegexPattern" . }}
  - name: m-dit
    components:
    - name: master
      compDef: {{ include "elasticsearchMaster.cmpdRegexPattern" . }}
    - name: dit
      compDef: {{ include "elasticsearchData.cmpdRegexPattern" . }}
    - name: kibana
      compDef: {{ include "kibana.cmpdRegexPattern" . }}
  - name: m-d-i-t
    components:
    - name: master
      compDef: {{ include "elasticsearchMaster.cmpdRegexPattern" . }}
    - name: data
      compDef: {{ include "elasticsearchData.cmpdRegexPattern" . }}
    - name: ingest
      compDef: {{ include "elasticsearchIngest.cmpdRegexPattern" . }}
    - name: transform
      compDef: {{ include "elasticsearchTransform.cmpdRegexPattern" . }}
    - name: kibana
      compDef: {{ include "kibana.cmpdRegexPattern" . }}
  - name: mdit
    components:
    - name: mdit
      compDef: {{ include "elasticsearchMdit.cmpdRegexPattern" . }}
