{{- $imageRegistry := .Values.image.registry | default "docker.io" -}}
apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  name: elasticsearch
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    {{- include "elasticsearch.apiVersion" . | nindent 4 }}
spec:
  compatibilityRules:
{{- range .Values.esVersions }}
  - compDefs:
    - {{ .componentDef }}
    - {{ .masterComponentDef }}
    - {{ .dataComponentDef }}
    releases:
{{- range .minors }}
      - {{ index . 0 }}
{{- end }}
{{- end }}
{{- if .Values.es9.enabled }}
  - compDefs:
      - {{ include "elasticsearch9.cmpdRegexPattern" . }}
      - {{ include "elasticsearchMaster9.cmpdRegexPattern" . }}
      - {{ include "elasticsearchData9.cmpdRegexPattern" . }}
    releases:
      - {{ .Values.es9.serviceVersion | quote }}
{{- end }}
  releases:
{{- range .Values.esVersions }}
{{- range .minors }}
{{- if not (index . 3) }}
  - name: {{ index . 0 }}
    serviceVersion: {{ index . 1 }}
    images:
      elasticsearch: {{ $imageRegistry }}/{{ $.Values.image.repository }}:{{ index . 2 }}
      prepare-plugins: {{ $imageRegistry }}/{{ $.Values.image.plugin.repository }}:{{ $.Values.image.plugin.tag }}
      install-plugins: {{ $imageRegistry }}/{{ $.Values.image.repository }}:{{ index . 2 }}
      exporter: {{ $imageRegistry }}/{{ $.Values.image.exporter.repository }}:{{ $.Values.image.exporter.tag }}
      memberleave: {{ $imageRegistry }}/{{ $.Values.image.tools.repository }}:{{ $.Values.image.tools.tag }}
      install-es-agent: {{ $imageRegistry }}/{{ $.Values.image.agent.repository }}:{{ $.Values.image.agent.tag }}
      es-agent: {{ $imageRegistry }}/{{ $.Values.image.repository }}:{{ index . 2 }}
      prepare-custom-plugins: {{ $imageRegistry }}/{{ $.Values.image.customPlugins.repository }}:{{ $.Values.image.customPlugins.tag }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.es9.enabled }}
  - name: {{ .Values.es9.serviceVersion | quote }}
    serviceVersion: {{ .Values.es9.serviceVersion | quote }}
    images:
      elasticsearch: {{ .Values.es9.images.elasticsearch | quote }}
      prepare-plugins: {{ .Values.es9.images.plugin | quote }}
      install-plugins: {{ .Values.es9.images.elasticsearch | quote }}
      exporter: {{ .Values.es9.images.exporter | quote }}
      memberleave: {{ .Values.es9.images.tools | quote }}
      install-es-agent: {{ .Values.es9.images.agent | quote }}
      es-agent: {{ .Values.es9.images.elasticsearch | quote }}
{{- end }}
