apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "doltdb.scriptsTemplate" . }}
  labels:
    {{- include "doltdb.labels" . | nindent 4 }}
  annotations:
    {{- include "doltdb.annotations" . | nindent 4 }}
data:
  doltdb-start.sh: |-
    {{- .Files.Get "scripts/doltdb-start.sh" | nindent 4 }}
  doltdb-sql.sh: |-
    {{- .Files.Get "scripts/doltdb-sql.sh" | nindent 4 }}
  doltdb-sql-probe.sh: |-
    {{- .Files.Get "scripts/doltdb-sql-probe.sh" | nindent 4 }}
  doltdb-mysql-replica-setup.sh: |-
    {{- .Files.Get "scripts/doltdb-mysql-replica-setup.sh" | nindent 4 }}
  doltdb-role-probe.sh: |-
    {{- .Files.Get "scripts/doltdb-role-probe.sh" | nindent 4 }}
  doltdb-switchover.sh: |-
    {{- .Files.Get "scripts/doltdb-switchover.sh" | nindent 4 }}
