auth_enabled: false

{{- $storageType := "local" }}
{{- if index . "storage_type" }}
{{- $storageType =  $.storage_type }}
{{- end }}

{{- $endpoint := "" }}
{{- if eq $storageType "s3" }}
{{/* if schema is not present (e.g. endpoint generated by kubeblocks), loki defaults to https. But we want http. */}}
{{ $endpoint = $.S3_ENDPOINT }}
{{- if not (hasPrefix "http" $endpoint) }}
  {{ $endpoint = printf "http://%s" $endpoint }}
{{- end }}
{{- end }}

server:
  grpc_listen_port: ${SERVER_GRPC_PORT}
  http_listen_port: ${SERVER_HTTP_PORT}
  grpc_server_max_recv_msg_size: 52428800

memberlist:
   bind_addr:
   - ${KB_POD_IP}
   join_members:
   - {{ .KB_CLUSTER_NAME }}-memberlist

common:
  compactor_address: '{{ .KB_CLUSTER_NAME }}-backend'
  {{/* compactor_grpc_address: '{{ printf "%s-backend.%s.svc.%s:9095" .KB_CLUSTER_NAME .KB_NAMESPACE .CLUSTER_DOMAIN }}' */}}
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    {{- if eq $storageType "local" }}
    filesystem:
      chunks_directory: ${LOCAL_CHUNKS_DIR}
      rules_directory: ${LOCAL_RULES_DIR}
    {{- else }}
    s3:
      endpoint: {{ $endpoint }}
      access_key_id: ${ACCESS_KEY_ID}
      secret_access_key: ${SECRET_ACCESS_KEY}
      bucketnames: {{ .s3_bucket }}
      s3forcepathstyle: {{ .s3_use_path_style }}
    {{- end }}

storage_config:
  {{- if eq $storageType "local" }}
  filesystem:
    directory: ${LOCAL_CHUNKS_DIR}
  {{- else }}
  aws:
    endpoint: {{ $endpoint }}
    access_key_id: ${ACCESS_KEY_ID}
    secret_access_key: ${SECRET_ACCESS_KEY}
    bucketnames: {{ .s3_bucket }}
    s3forcepathstyle: {{ .s3_use_path_style }}
  {{- end }}

limits_config:
  ingestion_burst_size_mb: 100
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 168h
  split_queries_by_interval: 2h

querier:
  max_concurrent: 50

schema_config:
  configs:
  - from: "2022-01-11"
    index:
      period: 24h
      prefix: loki_index_
    {{- if eq $storageType "local" }}
    object_store: filesystem
    {{- else }}
    object_store: s3
    {{- end }}
    schema: v12
    store: boltdb-shipper

ruler:
  storage:
    {{- if eq $storageType "local" }}
    local:
      directory: ${LOCAL_RULES_DIR}
    {{- else }}
    s3:
      bucketnames: {{ .s3_bucket }}
    {{- end }}
    {{- if eq $storageType "local" }}
    type: local
    {{- else }}
    type: s3
    {{- end }}

compactor:
  apply_retention_interval: 1h
  compaction_interval: 5m
  retention_delete_worker_count: 500
  retention_enabled: true
  {{- if eq $storageType "local" }}
  shared_store: filesystem
  {{- else }}
  shared_store: s3
  {{- end }}

index_gateway:
  mode: ring

query_range:
  align_queries_with_step: true

tracing:
  enabled: false
