apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParamConfigRenderer
metadata:
  name: {{ include "redisCluster8.pcrName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    {{- include "redis.annotations" . | nindent 4 }}
spec:
  componentDef: {{ include "redisCluster8.cmpdName" . }}
  parametersDefs:
    - {{ include "redisCluster8.paramsDefName" . }}

  configs:
    - name: redis.conf
      fileFormatConfig:
        format: redis
      reRenderResourceTypes:
        - vscale