apiVersion: apps.kubeblocks.io/v1
kind: ShardingDefinition
metadata:
  name: {{ printf "redis-cluster-%s" .Chart.Version }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    {{- include "redis.apiVersion" . | nindent 4 }}
spec:
  template:
    compDef: {{ include "redisCluster.cmpdRegexpPattern" . }}
  shardsLimit:
    minShards: 3
    maxShards: 64
  provisionStrategy: Parallel
  updateStrategy: Parallel
  systemAccounts:
    - name: default
      shared: true
  lifecycleActions:
    shardRemove:
      timeoutSeconds: 50
      exec:
        container: redis-cluster
        command:
          - /bin/bash
          - -c
          - |
            log=/tmp/pre-terminate.log
            if [ "$LEGACY_REDIS" == "true" ]; then
              /scripts/redis-cluster6-manage.sh --pre-terminate >"$log" 2>&1
            else
              /scripts/redis-cluster-manage.sh --pre-terminate >"$log" 2>&1
            fi
            rc=$?
            if [ "$rc" -ne 0 ]; then
              cat "$log" >&2
            fi
            exit "$rc"
      retryPolicy:
        maxRetries: 10
