apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  name: {{ include "oceanbase-ce.componentVersion" . }}
  labels:
    {{- include "oceanbase-ce.labels" . | nindent 4 }}
  annotations:
    {{- include "oceanbase-ce.apiVersion" . | nindent 4 }}
spec:
  compatibilityRules:
  - releases:
      {{- range .Values.versions }}
      - {{ .name }}
      {{- end }}
    compDefs:
      - {{ include "oceanbase-ce.componentDefNamePrefix" . }}
  releases:
  {{- range .Values.versions }}
  - name: {{ .name }}
    serviceVersion: "{{ .serviceVersion }}"
    images:
      observer-container: {{ include "oceanbase-ce.observer.repository" $ }}:{{ .observerTag }}
      metrics: {{ include "oceanbase-ce.metrics.repository" $ }}:{{ .metricsTag }}
      init-obtools: {{ include "oceanbase-ce.obtools.repository" $ }}:{{ .obtoolsTag }}
  {{- end }}
