{{- $pd := .Files.Get "config/oceanbase-config-effect-scope.yaml" | fromYaml }}
apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParametersDefinition
metadata:
  name: {{ include "oceanbase-ce.pdParamName" . }}
  labels:
    {{- include "oceanbase-ce.labels" . | nindent 4 }}
spec:
  componentDef: {{ include "oceanbase-ce.compDefName" . }}
  templateName: oceanbase-config
  fileName: oceanbase.conf
  fileFormatConfig:
    format: properties
  reloadAction:
    shellTrigger:
      sync: true
      command:
        - "update-parameters.sh"
      scriptConfig:
        scriptConfigMapRef: {{ include "oceanbase-ce.scripts.reload" . }}
        namespace: {{ .Release.Namespace }}
  # ConfigurationSchema that impose restrictions on engine parameter's rule
  parametersSchema:
    # top level mysql configuration type
    topLevelKey: OBParameters

    # schemaInJSON: auto generate from cue scripts
    # example: ../../pkg/configuration/testdata/mysql_openapi.json
    cue: |-
      {{- .Files.Get "config/oceanbase-config-constraint.cue" | nindent 6 }}

  ##  require db instance restart
  ## staticParameters
  {{- with get $pd "staticParameters" }}
  staticParameters:
      {{- range . }}
    - {{ . }}
      {{- end }}
  {{- end}}

  {{- with get $pd "dynamicParameters" }}
  dynamicParameters:
      {{- range . }}
    - {{ . }}
      {{- end }}
  {{- end}}

      ## define immutable parameter list, this feature is not currently supported.
  {{- with get $pd "immutableParameters" }}
  immutableParameters:
      {{- range . }}
    - {{ . }}
      {{- end }}
  {{- end}}
