apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: valkey-pod-monitor
  namespace: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: valkey-replication
      apps.kubeblocks.io/component-name: valkey
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
