apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: valkey-scale-out
  namespace: demo
spec:
  clusterName: valkey-replication
  type: HorizontalScaling
  horizontalScaling:
    - componentName: valkey
      scaleOut:
        replicaChanges: 1
