{
 "title": "APPS / ApeCloud MySQL-Proxy",
 "description": "MySQL-Proxy cluster overview",
 "tags": [
  "db",
  "apps",
  "MySQL-Proxy"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(mysql_up, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mysql_up, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(mysql_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query success - vtgate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 \n-\nsum(\n  rate(\n    vtgate_api_error_counts{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[$__rate_interval]\n  ) OR vector(0)\n)\n/\nsum(\n  rate(\n    vtgate_api_count{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[$__rate_interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Query success - vttablet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 \n-\n(\n  sum (\n    sum (rate(vttablet_errors_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[1m]))\n  )\n  /\n  sum (\n    sum (rate(vttablet_query_counts_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[1m]))\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Query latency p99",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "1000 * histogram_quantile(\n  0.99,\n  sum by(namespace, app_kubernetes_io_instance, le)(\n    sum by(le)(rate(vtgate_api_bucket{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\"\n    }[1m]))\n  )\n)\n"
    }
   ]
  },
  {
   "title": "QPS - vtgate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  sum (rate(vtgate_api_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n"
    }
   ]
  },
  {
   "title": "QPS - vttablet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  sum (rate(vttablet_query_counts_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n"
    }
   ]
  },
  {
   "title": "RED (vtgate) - Requests / Error rate / Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, app_kubernetes_io_instance)(\n  sum by (namespace, app_kubernetes_io_instance) (rate(vtgate_api_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Requests"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, app_kubernetes_io_instance)(\n  sum by (namespace, app_kubernetes_io_instance) (rate(vtgate_api_error_counts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m])))\n/\nsum by (namespace, app_kubernetes_io_instance)(\n  sum by (namespace, app_kubernetes_io_instance)(rate(vtgate_api_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m])))\n",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Error rate"
    }
   ]
  },
  {
   "title": "Duration 99th quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by(namespace, app_kubernetes_io_instance,le)(\n    sum by(namespace, app_kubernetes_io_instance,le)(rate(vtgate_api_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n  )\n)\n",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Duration"
    }
   ]
  },
  {
   "title": "RED (vtgate - group by tablet type)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (by db_type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, app_kubernetes_io_instance, db_type)(\n  sum by(namespace, app_kubernetes_io_instance, db_type)(rate(vtgate_api_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{db_type}}"
      }
     ]
    },
    {
     "title": "Error rate (by db_type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, app_kubernetes_io_instance, db_type)(\n  sum by(namespace, app_kubernetes_io_instance, db_type)(rate(vtgate_api_error_counts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n/\nsum by (namespace, app_kubernetes_io_instance, db_type)(\n  sum by(namespace, app_kubernetes_io_instance, db_type)(rate(vtgate_api_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{db_type}}"
      }
     ]
    },
    {
     "title": "Duration 99th quantile (by db_type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (namespace, app_kubernetes_io_instance, db_type, le)(\n    sum by(namespace, app_kubernetes_io_instance, le,db_type)(rate(vtgate_api_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{db_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RED (tablet) - Requests / Error rate / Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum  by (namespace,app_kubernetes_io_instance,pod)(\n  rate(\n    vttablet_query_counts_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,app_kubernetes_io_instance,pod)(\n  rate(\n    vttablet_query_error_counts_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n/\n(\n  sum by (namespace,app_kubernetes_io_instance,pod)(\n    rate(\n      vttablet_query_error_counts_total{\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n  +\n  sum by (namespace,app_kubernetes_io_instance,pod)(\n    rate(\n      vttablet_query_counts_total{\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n)\n",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Duration (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,sum by(namespace,app_kubernetes_io_instance,pod,le)(\n    rate(\n      vttablet_queries_bucket{\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n)\n",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "RED (tablet - group by plan type)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (by plan type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod, plan_type)(\n  rate(\n    vttablet_queries_count{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    } [1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{plan_type}}"
      }
     ]
    },
    {
     "title": "Error rate (by plan type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod, plan)(\n  rate(\n    vttablet_query_error_counts_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n/\n(\n  sum by (namespace,app_kubernetes_io_instance,pod, plan)(\n    rate(\n      vttablet_query_error_counts_total{\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n  +\n  sum by (namespace,app_kubernetes_io_instance,pod, plan)(\n    rate(\n      vttablet_query_counts_total{\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{plan}}"
      }
     ]
    },
    {
     "title": "Duration p99 (by plan type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.99,sum by(namespace,app_kubernetes_io_instance,pod,plan_type,le)(\n    rate(\n      vttablet_queries_bucket{\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{plan_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration (Avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace,app_kubernetes_io_instance)(\n  rate(\n    vtgate_api_sum{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[5m]\n  )\n)\n/\nsum by(namespace,app_kubernetes_io_instance)(\n  rate(\n    vtgate_api_count{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[5m]\n    )\n  )\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Avg Latency (vtgate)"
      },
      {
       "expr": "sum by(namespace,app_kubernetes_io_instance)(\n  rate(\n    vttablet_queries_sum{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[5m]\n  )\n)\n/\nsum by(namespace,app_kubernetes_io_instance)(\n  rate(\n    vttablet_queries_count{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[5m]\n    )\n  )\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Avg Latency (vttablet)"
      }
     ]
    },
    {
     "title": "Duration 50th quantile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by(namespace,app_kubernetes_io_instance,pod,le)(\n    sum by(namespace,app_kubernetes_io_instance,pod,le)(rate(vtgate_api_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Duration p50 (vtgate)"
      },
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by(namespace,app_kubernetes_io_instance,le)(\n    sum by(namespace,app_kubernetes_io_instance,le)(rate(vttablet_queries_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Duration p50 (vttablet)"
      }
     ]
    },
    {
     "title": "Duration 95th quantile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by(namespace,app_kubernetes_io_instance,pod,le)(\n    sum by(namespace,app_kubernetes_io_instance,pod,le)(rate(vtgate_api_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Duration p95 (vtgate)"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by(namespace,app_kubernetes_io_instance,le)(\n    sum by(namespace,app_kubernetes_io_instance,le)(rate(vttablet_queries_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | Duration p95 (vttablet)"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors (vtgate)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors (by code)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod,code)(\n  sum by(namespace,app_kubernetes_io_instance,pod,code)(rate(vtgate_api_error_counts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{code}}"
      }
     ]
    },
    {
     "title": "Errors (by operation)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod,operation)(\n  sum by(namespace,app_kubernetes_io_instance,pod,operation)(rate(vtgate_api_error_counts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{operation}}"
      }
     ]
    },
    {
     "title": "Errors (by db_type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod,db_type)(\n  sum by(namespace,app_kubernetes_io_instance,pod,db_type)(rate(vtgate_api_error_counts{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}[1m]))\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{db_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rows returned",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rows Returned (by table)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod,table) (\n  rate(\n    vttablet_query_rows_returned_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{table}}"
      }
     ]
    },
    {
     "title": "Rows Returned (by plan)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod,plan) (\n  rate(\n    vttablet_query_rows_returned_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{plan}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries/Errors (VtTablet)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries Killed",
     "type": "graph",
     "description": "Kills reports the queries and transactions killed by VTTablet due to timeout.\nIt’s a very important variable to look at during outages.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod,instance)(\n  sum by(namespace,app_kubernetes_io_instance,pod,instance)(rate(vttablet_kills_total{\n    namespace=~\"$namespace\",\n    app_kubernetes_io_instance=~\"$cluster\",\n    pod=~\"$instance\",\n  }[1m]))\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Query errors (by error code)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod,error_code)(\n  sum by(keyspace,shard,instance,error_code)(rate(vttablet_errors_total{\n    namespace=~\"$namespace\",\n    app_kubernetes_io_instance=~\"$cluster\",\n    pod=~\"$instance\",\n  }[1m]))\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | ErrorCode: {{error_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL-Proxy - Query pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Connections",
     "type": "graph",
     "description": "number of available connections in the pool in real-time",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod)(\n  vttablet_conn_pool_available{\n    namespace=~\"$namespace\",\n    app_kubernetes_io_instance=~\"$cluster\",\n    pod=~\"$instance\",\n  }\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "description": "count of in use connections to mysql",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (\n  vttablet_conn_pool_active{\n    namespace=~\"$namespace\",\n    app_kubernetes_io_instance=~\"$cluster\",\n    pod=~\"$instance\",\n  }\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Idle Closed Rate",
     "type": "graph",
     "description": "rate of closing connections due to the idle timeout",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 90 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod)(\n  rate(\n    vttablet_conn_pool_idle_closed_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Wait count",
     "type": "graph",
     "description": "WaitCount will give you how often the transaction pool gets full that causes new transactions to wait.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod)(\n  rate(\n    vttablet_conn_pool_wait_count_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Avg wait time",
     "type": "graph",
     "description": "WaitTime/WaitCount will tell you the average wait time.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 97 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod) (\n  rate(\n    vttablet_conn_pool_wait_time_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n/\nsum by (namespace,app_kubernetes_io_instance,pod) (\n  rate(\n    vttablet_conn_pool_wait_count_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL-Proxy - Transaction pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available Connections",
     "type": "graph",
     "description": "number of available connections in the pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod)(\n  vttablet_transaction_pool_available{\n    namespace=~\"$namespace\",\n    app_kubernetes_io_instance=~\"$cluster\",\n    pod=~\"$instance\",\n  }\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "description": "Number of connections actually open to mysql",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (\n  vttablet_transaction_pool_active{\n    namespace=~\"$namespace\",\n    app_kubernetes_io_instance=~\"$cluster\",\n    pod=~\"$instance\",\n  }\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Idle Closed Rate",
     "type": "graph",
     "description": "Rate of closing connections due to the idle timeout",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 105 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod)(\n  rate(\n    vttablet_transaction_pool_idle_closed_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Wait count",
     "type": "graph",
     "description": "WaitCount will give you how often the transaction pool gets full that causes new transactions to wait.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod)(\n  rate(\n    vttablet_transaction_pool_wait_count_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Avg wait time",
     "type": "graph",
     "description": "WaitTime/WaitCount will tell you the average wait time.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 112 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod) (\n  rate(\n    vttablet_transaction_pool_wait_time_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n/\nsum by (namespace,app_kubernetes_io_instance,pod) (\n  rate(\n    vttablet_transaction_pool_wait_count_total{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL-Proxy Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Duration (avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod)(\n  rate(\n    vttablet_transactions_sum{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n/\nsum by(namespace,app_kubernetes_io_instance,pod)(\n  rate(\n    vttablet_transactions_count{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Transaction Duration (p50)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 120 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,sum by(namespace,app_kubernetes_io_instance,pod,le)(\n    rate(\n      vttablet_transactions_bucket{\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Transaction Duration (p95)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 120 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,sum by(namespace,app_kubernetes_io_instance,pod,le)(\n    rate(\n      vttablet_transactions_bucket{\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "VtGate -> VtTablet Call Time (avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance)(\n  rate(\n    vtgate_vttablet_call_sum{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[1m]\n  )\n)\n/\nsum by (namespace,app_kubernetes_io_instance)(\n  rate(\n    vtgate_vttablet_call_count{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "Query Time Distribution (Heatmap)",
     "type": "heatmap",
     "description": "Shows a heatmap of the histogram bucketing of the time per read query.",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 127 },
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod,le) (\n  rate(\n    vttablet_queries_bucket{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n     }[1m]\n    )\n  )\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL time (avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 142 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,app_kubernetes_io_instance,pod) (\n  rate(\n    vttablet_mysql_sum{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n) \n/\nsum by (namespace,app_kubernetes_io_instance,pod) (\n  rate(\n    vttablet_mysql_count{\n      namespace=~\"$namespace\",\n      app_kubernetes_io_instance=~\"$cluster\",\n      pod=~\"$instance\",\n    }[1m]\n  )\n)\n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "MySQL Exec Time P50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 142 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by (le, namespace,app_kubernetes_io_instance,pod) (\n    rate(\n      vttablet_mysql_bucket{\n        operation=\"Exec\",\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n) \n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "MySQL Exec Time P95",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 142 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le, namespace,app_kubernetes_io_instance,pod) (\n    rate(\n      vttablet_mysql_bucket{\n        operation=\"Exec\",\n        namespace=~\"$namespace\",\n        app_kubernetes_io_instance=~\"$cluster\",\n        pod=~\"$instance\",\n      }[1m]\n    )\n  )\n) \n",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}