apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParametersDefinition
metadata:
  name: {{ include "tidb.tikv.paramName" . }}
  labels:
    {{- include "tidb.labels" . | nindent 4 }}
spec:
  componentDef: {{ include "tidb.tikv7.compDefName" . }}
  templateName: tikv-configuration
  fileName: tikv.toml
  fileFormatConfig:
    format: toml

  parametersSchema:
    topLevelKey: TIKVParameter
    cue: |-
      {{- .Files.Get "config/tikv-config-constraint.cue" | nindent 6 }}
