apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-weaviate-config-template
  namespace: demo
data:
  conf.yaml: |-
    ---
    authentication:
      anonymous_access:
        enabled: true
    authorization:
      admin_list:
        enabled: false
    query_defaults:
      limit: {{ .query_defaults_limit }}
    debug: false
---
apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: weaviate-cluster-with-config
  namespace: demo
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: weaviate
      componentDef: weaviate
      serviceVersion: 1.19.6
      replicas: 1
      configs:
        # The name must match ComponentDefinition.spec.configs[].name.
        - name: weaviate-config-template
          configMap:
            name: custom-weaviate-config-template
          variables:
            query_defaults_limit: "100"
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "0.5"
          memory: 512Mi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
