{
 "title": "nebula",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(taos_cluster_info_version,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(taos_cluster_info_version{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(taos_cluster_info_version{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Number Of Metad Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nebula_metad_count{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number Of Graphd Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nebula_graphd_count{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number Of Storaged Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nebula_storaged_count{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Slow Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nebula_graphd_slow_query_latency_us_avg_5{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    },
    {
     "expr": "nebula_graphd_slow_query_latency_us_p95_5{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nebula_graphd_query_latency_us_avg_5{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    },
    {
     "expr": "nebula_graphd_query_latency_us_p95_5{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Number Query Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_num_query_errors_rate_60{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    },
    {
     "expr": "nebula_graphd_num_query_errors_sum_60{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Number  Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nebula_graphd_num_queries_rate_5{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    },
    {
     "expr": "nebula_graphd_num_queries_sum_5{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Number Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nebula_graphd_num_slow_queries_rate_5{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    },
    {
     "expr": "nebula_graphd_num_slow_queries_sum_5{namespace=\"$namespace\", app_kubernetes_io_instance=~\"$cluster\"}"
    }
   ]
  }
 ]
}