# Common values for cluster charts

## @param monitoring interval, 0 is no monitoring
##
disableExporter: true

## @param terminationPolicy
terminationPolicy: Delete

## @param rbacEnabled 
## Specify whether rbac resources will be created by client, 
## otherwise KubeBlocks server will try to create rbac resources.
rbacEnabled: false
