{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "kblib.clusterName" . }}-dolt-metrics
  namespace: {{ .Release.Namespace }}
  labels:               # this is labels set in `prometheus.spec.podMonitorSelector`
    release: prometheus
    {{- with .Values.prometheus.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: app.kubernetes.io/managed-by
  podTargetLabels:
    - app.kubernetes.io/instance
    - app.kubernetes.io/managed-by
    - apps.kubeblocks.io/component-name
    - apps.kubeblocks.io/pod-name
  podMetricsEndpoints:
    - path: {{ .Values.prometheus.metricsPath | quote }}
      port: metrics
      scheme: http
      {{- with .Values.prometheus.interval }}
      interval: {{ . | quote }}
      {{- end }}
      {{- with .Values.prometheus.scrapeTimeout }}
      scrapeTimeout: {{ . | quote }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "kblib.clusterName" . | quote }}
      app.kubernetes.io/managed-by: kubeblocks
      apps.kubeblocks.io/component-name: dolt
{{- end }}
