'ad hoc distributed queries' = 0
'database mail xps' = 0
'blocked process threshold (s)' = 0
'clr enabled' = 0
'clr strict security' = 0
'cost threshold for parallelism' = 5
'default full-text language' = 1033
'default language' = 0
'filestream access level' = 0
'max degree of parallelism' = 0
'remote query timeout (s)' = 600
'remote login timeout (s)' = 10
'query wait (s)' = -1
'optimize for ad hoc workloads' = 0
'nested triggers' = 1
'max worker threads' = 0
'max text repl size (b)' = 65536
'remote proc trans' = 0
'query governor cost limit' = 0
'recovery interval (min)' = 0
'min memory per query (kb)' = 1024
'in-doubt xact resolution' = 0
