{{- if and .Values.remoteSetting.isStandby .Values.remoteSetting.primarySettings.host .Values.remoteSetting.primarySettings.port }}
apiVersion: apps.kubeblocks.io/v1
kind: ServiceDescriptor
metadata:
  name: {{ include "kblib.clusterName" . }}-remote-desc
  {{- if .Values.remoteSetting.primarySettings.serviceDescriptorNamespace }}
  namespace: {{ .Values.remoteSetting.primarySettings.serviceDescriptorNamespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels: {{ include "kblib.clusterLabels" . | nindent 4 }}
spec:
  serviceKind: elasticsearch
  serviceVersion: {{ .Values.version }}
  host:
    value: "{{ .Values.remoteSetting.primarySettings.host }}"
  port:
    value: "{{ .Values.remoteSetting.primarySettings.port }}"
  {{- if and .Values.remoteSetting.primarySettings.accountSecret.name .Values.remoteSetting.primarySettings.accountSecret.userKey .Values.remoteSetting.primarySettings.accountSecret.passwordKey }}
  auth:
    username:
      valueFrom:
        secretKeyRef:
          key: {{ .Values.remoteSetting.primarySettings.accountSecret.userKey }}
          name: {{ .Values.remoteSetting.primarySettings.accountSecret.name }}
          optional: false
    password:
      valueFrom:
        secretKeyRef:
          key: {{ .Values.remoteSetting.primarySettings.accountSecret.passwordKey }}
          name: {{ .Values.remoteSetting.primarySettings.accountSecret.name }}
          optional: false
  {{- end }}
{{- end }}