common:
  security:
    authorizationEnabled: true
    {{- if eq (index $ "TLS_ENABLED") "true" }}
    tlsMode: 1
    {{- end }}

{{- if eq (index $ "TLS_ENABLED") "true" }}
proxy:
  http:
    # for now milvus do not support config restful on same port with grpc
    # so we set to 8080, grpc will still use 19530
    port: 8080 
tls:
  serverPemPath: /etc/pki/tls/cert.pem
  serverKeyPath: /etc/pki/tls/key.pem
  caPemPath: /etc/pki/tls/ca.pem
{{- end }}

etcd:
  endpoints:
    - {{ .ETCD_ENDPOINT }}
  rootPath: {{ .CLUSTER_NAME }}
messageQueue: pulsar
minio:
  address: {{ .MINIO_HOST }}
  port: {{ .MINIO_PORT }}
  {{- if eq .MINIO_PORT "443" }}
  useSSL: true
  {{- else }}
  useSSL: false
  {{- end }}
  accessKeyID: MINIO_ACCESS_KEY
  secretAccessKey: MINIO_SECRET_KEY
  bucketName: {{ .minio_bucket }}
  rootPath: {{ .minio_root_path }}
  {{- if eq .minio_use_path_style "true" }}
  cloudProvider: aws
  {{- else }}
  cloudProvider: aliyun
  {{- end }}
mq:
  type: {{ .mq_type }}
msgChannel:
  chanNamePrefix:
    cluster: {{ .CLUSTER_NAME }}
{{- if eq .mq_type "pulsar" }}
pulsar:
  address: {{ .LOG_SERVICE_SERVER }}
  port: {{ .LOG_SERVICE_PORT }}
{{- else if eq .mq_type "kafka" }}
kafka:
  brokerList: {{ .LOG_SERVICE_PORT }}
{{- end }}
