apiVersion: parameters.kubeblocks.io/v1alpha1
kind: ParametersDefinition
metadata:
  name: {{ include "zookeeper.paramsDefName" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  componentDef: {{ include "zookeeper.cmpdName" . }}
  templateName: zookeeper-dynamic-config
  fileName: zoo.cfg.dynamic
  fileFormatConfig:
    format: props-plus
  reloadAction:
    autoTrigger:
      processName: zookeeper

  dynamicParameters:
    - server.1
    - server.2
    - server.3
    - server.4
    - server.5
