{
 "title": "MogDB",
 "description": "This dashboard works with opengauss_exporter for prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(pg_up,kubernetes_pod_name)"
    }
   },
   {
    "name": "podname",
    "query": {
     "query": "label_values(pg_up{pod=~\"$hostname\"},kubernetes_pod_name)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   { "name": "total", "query": { "query": "query_result(count(pg_up))" } }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Host Overview【Total: $total】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "pg_up" },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"mogdb\"}[1m])) without (cpu)"
    },
    {
     "expr": "container_memory_usage_bytes{container=\"mogdb\"}"
    },
    { "expr": "pg_run_times_run_time" },
    {
     "expr": "pg_settings_max_process_memory_bytes"
    },
    { "expr": "pg_settings_max_connections" },
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$datname\"}[5m])) by(kubernetes_pod_name) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$datname\"}[5m])) by(kubernetes_pod_name)"
    },
    {
     "expr": "sum(pg_connections_used_conn{}) by(kubernetes_pod_name) / sum(pg_setting_max_connections{}) by(kubernetes_pod_name) * 100"
    },
    {
     "expr": "sum(og_memory_info_memorymbytes{memorytype=\"dynamic_used_memory\"}) by(kubernetes_pod_name) / sum(og_memory_info_memorymbytes{memorytype=\"max_dynamic_memory\"}) by(kubernetes_pod_name) * 100"
    },
    {
     "expr": "sum(pg_stat_database_tup_fetched{datname=~\"$datname\"}) by(kubernetes_pod_name)"
    },
    {
     "expr": "sum(pg_stat_database_tup_inserted{datname=~\"$datname\"}) by(kubernetes_pod_name)"
    },
    {
     "expr": "sum(pg_stat_database_tup_updated{datname=~\"$datname\"}) by(kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "General Information【$podname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Instance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_up{pod=~\"$podname\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_version{pod=~\"$podname\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "DB Runtimes",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_run_times_run_time{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Exporter",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_exporter_up{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Exporter Runtimes",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_exporter_uptime{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Role",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_run_times_db_role{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Cluster Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_database_size_bytes{pod=~\"$podname\"})"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "stat",
     "description": "当前事务数,统计提交和回滚xact_commit+xact_rollback",
     "gridPos": { "h": 6, "w": 16, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$datname\", pod=~\"$podname\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$datname\", pod=~\"$podname\"}[5m]))"
      }
     ]
    },
    {
     "title": "Downstreams",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_downstream_count{pod=~\"$podname\", state=\"Streaming\"})"
      }
     ]
    },
    {
     "title": "Max Process Memory",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_process_memory_bytes{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_connections_used_conn{pod=~\"$podname\"}) / sum(pg_setting_max_connections{pod=~\"$podname\"}) * 100"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(og_memory_info_memorymbytes{memorytype=\"process_used_memory\",pod=~\"$podname\"}) / sum(og_memory_info_memorymbytes{memorytype=\"max_process_memory\",pod=~\"$podname\"}) * 100"
      }
     ]
    },
    {
     "title": "Dynamic Memory",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(og_memory_info_memorymbytes{memorytype=\"dynamic_used_memory\",pod=~\"$podname\"}) / sum(og_memory_info_memorymbytes{memorytype=\"max_dynamic_memory\",pod=~\"$podname\"}) * 100"
      }
     ]
    },
    {
     "title": "Slot Rate",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pg_replication_slots_active{pod=~\"$podname\"}) / sum(pg_setting_max_replication_slots{pod=~\"$podname\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory【$podname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "og_memory_info_memorymbytes{memorytype=~\"max_process_memory|process_used_memory|shared_used_memory|dynamic_used_memory\",pod=~\"$podname\"}",
       "legendFormat": "{{memorytype}}"
      }
     ]
    },
    {
     "title": "Memory Used Rate",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "og_memory_info_memorymbytes{memorytype=~\"backend_used_memory|cstore_used_memory|dynamic_used_memory|dynamic_used_shrctx|gpu_dynamic_used_memory|other_used_memory|pooler_conn_memory|pooler_freeconn_memory|sctpcomm_used_memory|shared_used_memory\",pod=~\"$podname\"}",
       "legendFormat": "{{memorytype}}"
      }
     ]
    },
    {
     "title": "Memory Peak Rate",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "og_memory_info_memorymbytes{memorytype=~\"dynamic_peak_memory|dynamic_peak_shrctx|gpu_dynamic_peak_memory|sctpcomm_peak_memory\",pod=~\"$podname\"}",
       "legendFormat": "{{memorytype}}"
      }
     ]
    },
    {
     "title": "Session State Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "og_state_memory_totalsize{pod=~\"$podname\"}",
       "legendFormat": "{{state}}_totalsize"
      }
     ]
    },
    {
     "title": "Context Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "og_context_memory_totalsize{pod=~\"$podname\"}",
       "legendFormat": "{{contextname}}_totalsize"
      },
      {
       "expr": "og_context_memory_usedsize{pod=~\"$podname\"}",
       "legendFormat": "{{contextname}}_usedsize"
      }
     ]
    },
    {
     "title": "Session Memory Totalsize",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "og_session_memory_totalsize{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Session Memory Usedsize",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "og_session_memory_usedsize{pod=~\"$podname\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections【$podname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_connections_max_conn{pod=~\"$podname\"}",
       "legendFormat": "max_connections"
      },
      {
       "expr": "pg_connections_used_conn{pod=~\"$podname\"}",
       "legendFormat": "used_connections"
      },
      {
       "expr": "pg_connections_res_for_normal{pod=~\"$podname\"}",
       "legendFormat": "free_connections"
      }
     ]
    },
    {
     "title": "Active",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", pod=~\"$podname\",state=~\"active\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Idle in transaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", pod=~\"$podname\", state=~\"idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Idle",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\",pod=~\"$podname\", state=~\"idle\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Session State Rate",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", pod=~\"$podname\"}",
       "legendFormat": "{{datname}}_{{state}}"
      }
     ]
    },
    {
     "title": "sessions_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pg_session_connection_count{pod=~\"$podname\"})by(client_addr)",
       "legendFormat": "{{client_addr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replications【$podname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Max Slots",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_replication_slots{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Replication Informations",
     "type": "table",
     "gridPos": { "h": 7, "w": 13, "x": 4, "y": 4 },
     "targets": [
      {
       "expr": "pg_replication_backend_uptime{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Replication Delay",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pg_replication_replay_diff{pod=~\"$podname\"}",
       "legendFormat": "{{instance}}_replay_diff"
      },
      {
       "expr": "pg_replication_write_diff{pod=~\"$podname\"}",
       "legendFormat": "{{instance}}_write_diff"
      },
      {
       "expr": "pg_replication_flush_diff{pod=~\"$podname\"}",
       "legendFormat": "{{instance}}_flush_diff"
      }
     ]
    },
    {
     "title": "Slot Rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(pg_replication_slots_active{pod=~\"$podname\"}) / sum(pg_setting_max_replication_slots{pod=~\"$podname\"}) * 100"
      }
     ]
    },
    {
     "title": "Slot Informations",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "pg_replication_slots_active{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Slots Delay",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "pg_replication_slots_delay_lsn{pod=~\"$podname\"}",
       "legendFormat": "{{instance}}_delay_lsn"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks & Wait Events【$podname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Locker Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pg_locker_count{pod=~\"$podname\"}",
       "legendFormat": "{{query}}"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (pg_lock_count{pod=~\"$podname\"})",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{pod=~\"$podname\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{pod=~\"$podname\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Lock Detail",
     "type": "table",
     "description": "会话",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "pg_lock_detail_locked_times{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Wait Event Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(pg_wait_events_wait{pod=~\"$podname\"}[1m]) != 0",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Wait Event Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(pg_wait_events_wait{pod=~\"$podname\"}[1m]) != 0",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Wait Event Times",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(pg_wait_events_total_wait_time{pod=~\"$podname\",event !=\"wait cmd\"}[1m]) != 0",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Wait Event Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 29 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "irate(pg_wait_events_total_wait_time{pod=~\"$podname\"}[1m]) != 0",
       "legendFormat": "{{event}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Statistics【$podname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current fetch data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", pod=~\"$podname\"})"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 4, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{pod=~\"$podname\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{pod=~\"$podname\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_returned{datname=~\"$datname\", pod=~\"$podname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Fetch data (SELECT)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_fetched{datname=~\"$datname\", pod=~\"$podname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", pod=~\"$podname\"})"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", pod=~\"$podname\"})"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_inserted{datname=~\"$datname\", pod=~\"$podname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_updated{datname=~\"$datname\", pod=~\"$podname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_deleted{datname=~\"$datname\", pod=~\"$podname\"}[1m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend{pod=~\"$podname\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc{pod=~\"$podname\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{pod=~\"$podname\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{pod=~\"$podname\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean{pod=~\"$podname\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{pod=~\"$podname\", datname=~\"$datname\"} / (pg_stat_database_blks_read{pod=~\"$podname\", datname=~\"$datname\"} + pg_stat_database_blks_hit{pod=~\"$podname\", datname=~\"$datname\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{pod=~\"$podname\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{pod=~\"$podname\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    }
   ]
  },
  {
   "title": "Query【$podname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Session",
     "type": "table",
     "description": "会话",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "pg_active_slowsql_query_runtime{datname=~\"$datname\", pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "CPU Times",
     "type": "table",
     "description": "会话",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "pg_sql_history_cpu_time{pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Calls",
     "type": "table",
     "description": "会话",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "pg_sql_history_n_calls{pod=~\"$podname\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables and Indexes【$podname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Table Size",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "pg_tables_size_bytes{datname=~\"$datname\", pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Index Size",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "pg_indexes_size_index_size{datname=~\"$datname\", pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Table Expansion Rate",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "pg_tables_expansion_rate_dead_rate{datname=~\"$datname\", pod=~\"$podname\"}"
      }
     ]
    },
    {
     "title": "Never Used Indexes",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "pg_never_used_indexes_index_size{datname=~\"$datname\", pod=~\"$podname\"}"
      }
     ]
    }
   ]
  }
 ]
}