apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  generateName: milvus-standalone-minio-credential-
  namespace: demo
spec:
  clusterName: milvus-standalone
  type: Upgrade
  upgrade:
    components:
      - componentName: minio
        componentDefinitionName: milvus-minio-1.2.0-alpha.1
      - componentName: milvus
        componentDefinitionName: milvus-standalone-1.2.0-alpha.1
