apiVersion: apps.kubeblocks.io/v1
kind: ShardingDefinition
metadata:
  name: {{ include "mongodbShard.compDefName" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    {{- include "mongodb.annotations" . | nindent 4 }}
spec:
  template:
    compDef: {{ include "mongodbShard.compDefName" . }}
  shardsLimit:
    minShards: 1
    maxShards: 128
  provisionStrategy: Parallel
  updateStrategy: Parallel
  lifecycleActions:
    shardRemove:
      exec:
        container: mongodb
        command:
          - /bin/bash
          - -c
          - /scripts/mongodb-shard-manage.sh --pre-terminate >> /tmp/pre-terminate.log 2>&1
        targetPodSelector: Role
        matchingKey: primary
      retryPolicy:
        maxRetries: 10

