{
 "title": "tidb-pd",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(pd_cluster_status{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pd_cluster_metadata{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metadata",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pd_cluster_metadata{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Normal stores",
   "type": "stat",
   "description": "The count of healthy stores",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pd_cluster_status{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", type=\"store_up_count\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region health",
   "type": "timeseries",
   "description": "It records the unusual Regions' count which may include pending peers, down peers, extra peers, offline peers, missing peers or learner peers",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "max(pd_regions_status{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"}) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current TSO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pd_cluster_tso{type=\"tso\", dc=\"global\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PD server TSO handle time",
   "type": "timeseries",
   "description": "The time consumed of handling TiDB TSO requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(pd_server_handle_tso_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"}[30s])) by (type, le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pd_server_handle_tso_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"}[30s])) by (type, le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(pd_server_handle_tso_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"}[30s])) by (type, le))",
     "legendFormat": "99.9%"
    }
   ]
  },
  {
   "title": "Goroutine Count",
   "type": "timeseries",
   "description": "PD process current goroutines count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", kubeblocks_component_name=\"tidb-pd\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Schedule operator create",
   "type": "timeseries",
   "description": "The number of different operators that are newly created",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(delta(pd_schedule_operators_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", event=\"create\"}[1m])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator finish duration",
   "type": "timeseries",
   "description": "The time consumed when the operator is finished in .99",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pd_schedule_finish_operators_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"}[5m])) by (type, le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}