{
 "title": "tidb",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(pd_cluster_status{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tidb_config_status{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Query Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "TiDB query durations by histogram buckets with different percents.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type!=\"internal\"}[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type!=\"internal\"}[1m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "sum(rate(tidb_server_handle_query_duration_seconds_sum{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type!=\"internal\"}[30s])) / sum(rate(tidb_server_handle_query_duration_seconds_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", sql_type!=\"internal\"}[30s]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Failed Query OPS",
   "type": "timeseries",
   "description": "TiDB failed query statistics by query type.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(tidb_server_execute_error_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m])) by (type, pod)",
     "legendFormat": "{{type}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Command Per Second",
   "type": "timeseries",
   "description": "MySQL command processing numbers per second. See https://dev.mysql.com/doc/internals/en/text-protocol.html and https://dev.mysql.com/doc/internals/en/prepared-statements.html",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tidb_server_query_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m])) by (result)",
     "legendFormat": "query {{result}}"
    }
   ]
  },
  {
   "title": "CPS By Instance",
   "type": "timeseries",
   "description": "TiDB query total statistics including both successful and failed ones.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tidb_server_query_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m])) by (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "TiDB statement statistics.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tidb_executor_statement_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(tidb_executor_statement_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "CPS by CMD",
   "type": "timeseries",
   "description": "MySQL command statistics by command type. See https://dev.mysql.com/doc/internals/en/text-protocol.html and https://dev.mysql.com/doc/internals/en/prepared-statements.html",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tidb_server_query_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Query Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Parse Duration",
   "type": "timeseries",
   "description": "The time cost of parsing SQL to AST",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_session_parse_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_session_parse_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le))",
     "legendFormat": "95"
    }
   ]
  },
  {
   "title": "Compile Duration",
   "type": "timeseries",
   "description": "The time cost of building the query plan",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_session_compile_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_session_compile_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le))",
     "legendFormat": "95"
    }
   ]
  },
  {
   "title": "Execution Duration",
   "type": "timeseries",
   "description": "The time cost of executing the SQL which does not include the time to get the results of the query.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_session_execute_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_session_execute_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le))",
     "legendFormat": "95"
    }
   ]
  },
  {
   "title": "Queries Using Plan Cache OPS",
   "type": "timeseries",
   "description": "TiDB plan cache hit total.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tidb_server_plan_cache_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "TiDB transaction processing counts by type.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tidb_session_transaction_duration_seconds_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m])) by (type, txn_mode)",
     "legendFormat": "{{type}}-{{txn_mode}}"
    }
   ]
  },
  {
   "title": "Transaction Duration",
   "type": "timeseries",
   "description": "Bucketed histogram of transaction execution durations, including retry.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le, txn_mode))",
     "legendFormat": "99-{{txn_mode}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tidb_session_transaction_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le, txn_mode))",
     "legendFormat": "95-{{txn_mode}}"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", sql_type=\"general\"}[1m])) by (le, txn_mode))",
     "legendFormat": "80-{{txn_mode}}"
    }
   ]
  },
  {
   "title": "Max Transaction Statement Num",
   "type": "timeseries",
   "description": "The max TiDB statements numbers within one transaction.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tidb_session_transaction_statement_num_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Max Transaction Retry Num",
   "type": "timeseries",
   "description": "The max TiDB transaction retry count.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(tidb_session_retry_num_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "max"
    }
   ]
  }
 ]
}