{
 "title": "tikv",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(pd_cluster_status{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tikv_store_size_bytes{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Store size",
   "type": "timeseries",
   "description": "The storage size per TiKV instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(tikv_store_size_bytes{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", type=\"used\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "R/W",
   "type": "timeseries",
   "description": "The total bytes of read and write in each TiKV instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", db=\"kv\", type=\"wal_file_bytes\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-write"
    },
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", db=\"kv\", type=~\"bytes_read|iter_bytes_read\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-read"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "The QPS of different kinds of commands in each TiKV instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", type!=\"kv_gc\"}[1m])) by (pod,type)",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "Errps",
   "type": "timeseries",
   "description": "The total number of the gRPC message failures",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_fail_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", type!=\"kv_gc\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}-grpc-msg-fail"
    },
    {
     "expr": "sum(delta(tikv_pd_heartbeat_message_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", type=\"noop\"}[1m])) by (pod) < 1",
     "legendFormat": "{{pod}}-pd-heartbeat"
    },
    {
     "expr": "sum(rate(tikv_critical_error_total{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}[1m])) by (pod, type)",
     "legendFormat": "{{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "timeseries",
   "description": "The number of leaders per TiKV instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(tikv_raftstore_region_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", type=\"leader\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Region",
   "type": "timeseries",
   "description": "The number of Regions on each TiKV instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(tikv_raftstore_region_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", type=\"region\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region size",
   "type": "timeseries",
   "description": "The approximate Region size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(tikv_raftstore_region_size_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(tikv_raftstore_region_size_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "sum(tikv_raftstore_region_size_sum{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}) / sum(tikv_raftstore_region_size_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\"}) ",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "99% gRPC message duration",
   "type": "timeseries",
   "description": "The gRPC message duration per message type (P99)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_grpc_msg_duration_seconds_bucket{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\", pod=~\"$instance\", type!=\"kv_gc\"}[1m])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}