{
 "title": "Hive MetaStore",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(metrics_pools_Metaspace_usage_Value,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(metrics_pools_Metaspace_usage_Value{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(metrics_pools_Metaspace_usage_Value{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - java_lang_Runtime_StartTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}/1000"
      }
     ]
    },
    {
     "title": "Available CPUs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_Runtime_StartTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "JVM Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 407 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_join(jvm_runtime_info{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
      }
     ]
    },
    {
     "title": "CPU load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 411 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemCpuLoad{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-system"
      },
      {
       "expr": "java_lang_OperatingSystem_ProcessCpuLoad{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-process"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 411 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Physical memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 419 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-total"
      },
      {
       "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-committed-vm"
      },
      {
       "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-free"
      }
     ]
    },
    {
     "title": "Process memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 419 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-virtual-mem"
      },
      {
       "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-resident-mem"
      }
     ]
    },
    {
     "title": "JVM Memory(Heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 427 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_Memory_HeapMemoryUsage_max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "java_lang_Memory_HeapMemoryUsage_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-used"
      }
     ]
    },
    {
     "title": "JVM memory(NonHeap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 427 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_Memory_NonHeapMemoryUsage_max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "java_lang_Memory_NonHeapMemoryUsage_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-used"
      }
     ]
    },
    {
     "title": "JVM Memory(Committed)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 435 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{area}}"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Code Cache]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 435 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Compressed Class Spacee]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 445 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Eden Space]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 445 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Eden Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Eden Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Eden Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Eden Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Metaspace]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 455 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Survivor Space]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 455 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Survivor Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Survivor Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Survivor Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Survivor Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Tenured Gen]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 465 },
     "repeat": "mempool",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Tenured Gen\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Tenured Gen\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Tenured Gen\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Tenured Gen\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "GC time Sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 475 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
       "legendFormat": "{{pod}}-{{gc}}"
      }
     ]
    },
    {
     "title": "GC count increase",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 475 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
       "legendFormat": "{{pod}}-{{gc}}"
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 484 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-loaded"
      }
     ]
    },
    {
     "title": "Threads used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 484 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_current{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-current threads"
      },
      {
       "expr": "jvm_threads_daemon{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-deadlocked threads"
      }
     ]
    }
   ]
  },
  {
   "title": "MetaStore Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "Alter Table Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_alter_table_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Alter Table AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_alter_table_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_alter_table_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_alter_table_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_alter_table_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-threads"
    },
    {
     "expr": "metrics_daemon_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-daemon-threads"
    },
    {
     "expr": "metrics_deadlock_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-deadlock-threads"
    },
    {
     "expr": "metrics_new_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-new-threads"
    },
    {
     "expr": "metrics_threads_timed_waiting_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-terminated-threads"
    },
    {
     "expr": "metrics_runnable_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-runnable-threads"
    },
    {
     "expr": "metrics_timed_waiting_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-timed-waiting-threads"
    },
    {
     "expr": "metrics_waiting_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-waiting-threads"
    }
   ]
  },
  {
   "title": "Get Table Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_table_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get Table AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_get_table_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_table_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_table_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_table_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Alter Table With Environment  Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_alter_table_with_environment_context_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_alter_table_with_environment_context_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneMinute"
    },
    {
     "expr": "metrics_api_alter_table_with_environment_context_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveMinute"
    },
    {
     "expr": "metrics_api_alter_table_with_environment_context_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenMinute"
    }
   ]
  },
  {
   "title": "Get Table REQ  Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_get_table_req_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_get_table_req_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneMinute"
    },
    {
     "expr": "metrics_api_get_table_req_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveMinute"
    },
    {
     "expr": "metrics_api_get_table_req_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenMinute"
    }
   ]
  },
  {
   "title": "Get Table REQ AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_get_table_req_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_table_req_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_table_req_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_table_req_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Alter Table With Environment Context AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_alter_table_with_environment_context_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_alter_table_with_environment_context_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_alter_table_with_environment_context_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_alter_table_with_environment_context_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get Databases Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_database_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get databases AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_get_database_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_database_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_database_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_database_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get Check COnstraints Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_check_constraints_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get Foreign Keys Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_foreign_keys_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get Foreign Keys AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_get_foreign_keys_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_foreign_keys_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_foreign_keys_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_foreign_keys_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get check Constraints Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_get_check_constraints_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_check_constraints_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_check_constraints_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_check_constraints_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get Not Null Constraints Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_not_null_constraints_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get Not Null Constraints AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_get_not_null_constraints_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_not_null_constraints_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_not_null_constraints_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_not_null_constraints_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get Materialized views for rewriting Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_materialized_views_for_rewriting_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get Primary Keys Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_primary_keys_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get Primary Keys AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_get_primary_keys_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_primary_keys_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_primary_keys_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_primary_keys_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get Materialized views for Rewriting AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_primary_keys_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_materialized_views_for_rewriting_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_materialized_views_for_rewriting_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_materialized_views_for_rewriting_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Delete/Create partitions Total Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_delete_total_count_partitions_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-delete"
    },
    {
     "expr": "metrics_create_total_count_partitions_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-create"
    }
   ]
  },
  {
   "title": "Create /Delete Table Total Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_create_total_count_tables_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-create"
    },
    {
     "expr": "metrics_delete_total_count_tables_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-delete"
    }
   ]
  },
  {
   "title": "Get UniqueConstraints Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_active_calls_get_unique_constraints_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush Cache Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_flushCache_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_flushCache_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneMinute"
    },
    {
     "expr": "metrics_api_flushCache_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveMinute"
    },
    {
     "expr": "metrics_api_flushCache_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenMinute"
    }
   ]
  },
  {
   "title": "Flush Cache AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_flushCache_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_flushCache_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_flushCache_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_flushCache_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get Unique Constraints AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_get_unique_constraints_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_get_unique_constraints_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_get_unique_constraints_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_get_unique_constraints_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Set  Aggr Stats For Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_set_aggr_stats_for_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_set_aggr_stats_for_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneMinute"
    },
    {
     "expr": "metrics_api_set_aggr_stats_for_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveMinute"
    },
    {
     "expr": "metrics_api_set_aggr_stats_for_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenMinute"
    }
   ]
  },
  {
   "title": "Set Aggr Stats For AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_set_aggr_stats_for_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_set_aggr_stats_for_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_set_aggr_stats_for_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_set_aggr_stats_for_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Set Ugi Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_set_ugi_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_set_ugi_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneMinute"
    },
    {
     "expr": "metrics_api_set_ugi_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveMinute"
    },
    {
     "expr": "metrics_api_set_ugi_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenMinute"
    }
   ]
  },
  {
   "title": "Set UGI AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_set_ugi_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_set_ugi_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_set_ugi_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_set_ugi_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  }
 ]
}