{
 "title": "Hive Server2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(metrics_active_calls_api_Driver_run_Count,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(metrics_active_calls_api_Driver_run_Count{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(metrics_active_calls_api_Driver_run_Count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - java_lang_Runtime_StartTime{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}/1000"
      }
     ]
    },
    {
     "title": "Available CPUs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_Runtime_StartTime{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "JVM Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_join({__name__=~\"jvm_runtime_info|jvm_runtime\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"},\"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
      }
     ]
    },
    {
     "title": "CPU load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 294 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemCpuLoad{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-system"
      },
      {
       "expr": "java_lang_OperatingSystem_ProcessCpuLoad{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-process"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 294 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Physical memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-total"
      },
      {
       "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-committed-vm"
      },
      {
       "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-free"
      }
     ]
    },
    {
     "title": "Process memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-virtual-mem"
      },
      {
       "expr": "process_resident_memory_bytes{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-resident-mem"
      }
     ]
    },
    {
     "title": "JVM Memory(Heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 310 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_Memory_HeapMemoryUsage_max{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "java_lang_Memory_HeapMemoryUsage_used{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-used"
      }
     ]
    },
    {
     "title": "JVM memory(NonHeap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 310 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_Memory_NonHeapMemoryUsage_max{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "java_lang_Memory_NonHeapMemoryUsage_used{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-used"
      }
     ]
    },
    {
     "title": "JVM Memory(Committed)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 318 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{area}}"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Code Cache]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 318 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Compressed Class Spacee]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Eden Space]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Metaspace]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 338 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Survivor Space]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 338 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Tenured Gen]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 348 },
     "repeat": "mempool",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "GC time Sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 358 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
       "legendFormat": "{{pod}}-{{gc}}"
      }
     ]
    },
    {
     "title": "GC count increase",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 358 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
       "legendFormat": "{{pod}}-{{gc}}"
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 367 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_total{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-loaded"
      }
     ]
    },
    {
     "title": "Threads used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 367 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_current{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-current threads"
      },
      {
       "expr": "jvm_threads_daemon{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"server2\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-deadlocked threads"
      }
     ]
    }
   ]
  },
  {
   "title": "Hs2 Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(metrics_cumulative_connection_count_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_open_connections_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-active"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_hs2_active_sessions_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-active"
      },
      {
       "expr": "metrics_hs2_open_sessions_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-open"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_threads_daemon_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-daemon-threads"
      },
      {
       "expr": "metrics_threads_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-threads"
      },
      {
       "expr": "metrics_threads_deadlock_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-deadlock-threads"
      },
      {
       "expr": "metrics_threads_new_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-new-threads"
      },
      {
       "expr": "metrics_threads_runnable_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-runnable-threads"
      },
      {
       "expr": "metrics_threads_terminated_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-terminated-threads"
      },
      {
       "expr": "metrics_threads_timed_waiting_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-timed_waiting-threads"
      },
      {
       "expr": "metrics_threads_waiting_count_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-waiting-threads"
      }
     ]
    },
    {
     "title": "Cumulative Mapred Tasks",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_hive_mapred_tasks_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-active"
      }
     ]
    },
    {
     "title": "Completed SQL Ops Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(metrics_hs2_completed_sql_operation_FINISHED_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Compiling queries rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_hs2_compiling_queries_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_hs2_compiling_queries_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-oneminute"
      },
      {
       "expr": "metrics_hs2_compiling_queries_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fiveminute"
      },
      {
       "expr": "metrics_hs2_compiling_queries_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fifteenminute"
      }
     ]
    },
    {
     "title": "Compiling queries Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_hs2_compiling_queries_Mean{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_hs2_compiling_queries_Max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "metrics_hs2_compiling_queries_Min{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-min"
      }
     ]
    },
    {
     "title": "Compiling queries Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_hs2_compiling_queries_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-50thPercentile"
      },
      {
       "expr": "metrics_hs2_compiling_queries_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-75thPercentile"
      },
      {
       "expr": "metrics_hs2_compiling_queries_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-95thPercentile"
      },
      {
       "expr": "metrics_hs2_compiling_queries_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-99thPercentile"
      }
     ]
    },
    {
     "title": "Executing queries rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_hs2_executing_queries_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_hs2_executing_queries_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-oneminute"
      },
      {
       "expr": "metrics_hs2_executing_queries_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fiveminute"
      },
      {
       "expr": "metrics_hs2_executing_queries_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fifteenminute"
      }
     ]
    },
    {
     "title": "Executing queries Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_hs2_executing_queries_Mean{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_hs2_executing_queries_Max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "metrics_hs2_executing_queries_Min{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-min"
      }
     ]
    },
    {
     "title": "Executing queries Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_hs2_executing_queries_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-50thPercentile"
      },
      {
       "expr": "metrics_hs2_executing_queries_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-75thPercentile"
      },
      {
       "expr": "metrics_hs2_executing_queries_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-95thPercentile"
      },
      {
       "expr": "metrics_hs2_executing_queries_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-99thPercentile"
      }
     ]
    },
    {
     "title": "Submitted queries rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_hs2_executing_submitted_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_hs2_submitted_queries_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-oneminute"
      },
      {
       "expr": "metrics_hs2_submitted_queries_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fiveminute"
      },
      {
       "expr": "metrics_hs2_submitted_queries_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fifteenminute"
      }
     ]
    },
    {
     "title": "Submitted queries Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_hs2_submitted_queries_Mean{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_hs2_submitted_queries_Max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "metrics_hs2_submitted_queries_Min{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-min"
      }
     ]
    },
    {
     "title": "Executing queries AVG time(Percentile)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_hs2_submitted_queries_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-50thPercentile"
      },
      {
       "expr": "metrics_hs2_submitted_queries_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-75thPercentile"
      },
      {
       "expr": "metrics_hs2_submitted_queries_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-95thPercentile"
      },
      {
       "expr": "metrics_hs2_submitted_queries_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-99thPercentile"
      }
     ]
    },
    {
     "title": "Succeeded queries rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_hs2_succeeded_submitted_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_hs2_succeeded_queries_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-oneminute"
      },
      {
       "expr": "metrics_hs2_succeeded_queries_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fiveminute"
      },
      {
       "expr": "metrics_hs2_succeeded_queries_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fifteenminute"
      }
     ]
    },
    {
     "title": "Active Session AVG Tme",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_hs2_avg_active_session_time_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      }
     ]
    },
    {
     "title": "Active Session AVG Tme",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_hs2_avg_active_session_time_Value{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      }
     ]
    }
   ]
  },
  { "title": "hs2 API Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Running SQL AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_hs2_operation_RUNNING_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_hs2_operation_RUNNING_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_hs2_operation_RUNNING_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_hs2_operation_RUNNING_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Running SQL Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_hs2_operation_RUNNING_Mean{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_hs2_operation_RUNNING_Max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "metrics_api_hs2_operation_RUNNING_Min{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-min"
    }
   ]
  },
  {
   "title": "Running SQL rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_hs2_operation_RUNNING_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_hs2_operation_RUNNING_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_hs2_operation_RUNNING_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_hs2_operation_RUNNING_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Pending SQL AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_hs2_operation_PENDING_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_hs2_operation_PENDING_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_hs2_operation_PENDING_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_hs2_operation_PENDING_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Pengding SQL Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_hs2_operation_PENDING_Mean{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_hs2_operation_PENDING_Max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "metrics_api_hs2_operation_PENDING_Min{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-min"
    }
   ]
  },
  {
   "title": "Pending SQL rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_hs2_operation_PENDING_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_hs2_operation_PENDING_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_hs2_operation_PENDING_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_hs2_operation_PENDING_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Run Task  AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_runTasks_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_runTasks_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_runTasks_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_runTasks_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Run Task rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_runTasks_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_runTasks_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_runTasks_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_runTasks_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Wait Compile AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_waitCompile_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_waitCompile_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_waitCompile_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_waitCompile_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Serialize Plan AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_serializePlan_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_serializePlan_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_serializePlan_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_serializePlan_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Serialize Plan rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_serializePlan_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_serializePlan_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_serializePlan_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_serializePlan_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Wait Compile rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_waitCompile_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_waitCompile_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_waitCompile_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_waitCompile_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Semantic Analyze AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_semanticAnalyze_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_semanticAnalyze_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_semanticAnalyze_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_semanticAnalyze_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Semantic Analyze rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_semanticAnalyze_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_semanticAnalyze_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_semanticAnalyze_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_semanticAnalyze_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Release Locks AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_releaseLocks_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_releaseLocks_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_releaseLocks_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_releaseLocks_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Partition Retrieving AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_partition_retrieving_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_partition_retrieving_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_partition_retrieving_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_partition_retrieving_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Partition Retrieving rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_partition_retrieving_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_partition_retrieving_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_partition_retrieving_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_partition_retrieving_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Release Locks rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_releaseLocks_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_releaseLocks_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_releaseLocks_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_releaseLocks_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Parse  AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_parse_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_parse_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_parse_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_parse_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Parse rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_parse_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_parse_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_parse_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_parse_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Optimizer Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_optimizer_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_optimizer_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_optimizer_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_optimizer_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get Splits  AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_getSplits_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_getSplits_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_getSplits_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_getSplits_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "Get Splits rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_getSplits_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_getSplits_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_getSplits_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_getSplits_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Optimizer rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_optimizer_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_optimizer_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_optimizer_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_optimizer_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Compile AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_compile_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_compile_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_compile_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_compile_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "compile rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_compile_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_compile_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_compile_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_compile_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "RenameOrMoveFiles Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_RenameOrMoveFiles_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_RenameOrMoveFiles_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_RenameOrMoveFiles_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_RenameOrMoveFiles_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "RemoveTempOrDuplicateFiles AVG Time(Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "metrics_api_RemoveTempOrDuplicateFiles_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-50thPercentile"
    },
    {
     "expr": "metrics_api_RemoveTempOrDuplicateFiles_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-75thPercentile"
    },
    {
     "expr": "metrics_api_RemoveTempOrDuplicateFiles95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-95thPercentile"
    },
    {
     "expr": "metrics_api_RemoveTempOrDuplicateFiles_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-99thPercentile"
    }
   ]
  },
  {
   "title": "RemoveTempOrDuplicateFiles rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_RemoveTempOrDuplicateFiles_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_RemoveTempOrDuplicateFiles_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_RemoveTempOrDuplicateFiles_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_RemoveTempOrDuplicateFiles_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "RenameOrMoveFiles rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_api_RenameOrMoveFiles_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-mean"
    },
    {
     "expr": "metrics_api_RenameOrMoveFiles_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-oneminute"
    },
    {
     "expr": "metrics_api_RenameOrMoveFiles_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fiveminute"
    },
    {
     "expr": "metrics_api_RenameOrMoveFiles_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-fifteenminute"
    }
   ]
  },
  {
   "title": "Driver Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Ops Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_active_calls_api_Driver_run_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-run"
      },
      {
       "expr": "metrics_active_calls_api_Driver_execute_Count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-execute"
      }
     ]
    },
    {
     "title": "Driver Run Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_api_Driver_run_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean-rate"
      },
      {
       "expr": "metrics_api_Driver_run_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-onemiute"
      },
      {
       "expr": "metrics_api_Driver_run_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fiveminute"
      },
      {
       "expr": "metrics_api_Driver_run_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fifteenminute"
      }
     ]
    },
    {
     "title": "Driver execute Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "metrics_api_Driver_execute_MeanRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean-rate"
      },
      {
       "expr": "metrics_api_Driver_execute_OneMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-onemiute"
      },
      {
       "expr": "metrics_api_Driver_execute_FiveMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fiveminute"
      },
      {
       "expr": "metrics_api_Driver_execute_FifteenMinuteRate{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-fifteenminute"
      }
     ]
    },
    {
     "title": "Driver Run Times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_api_Driver_run_Max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "metrics_api_Driver_run_Mean{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_api_Driver_run_Min{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-min"
      }
     ]
    },
    {
     "title": "Driver execute Times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_api_Driver_execute_Max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "metrics_api_Driver_execute_Mean{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-mean"
      },
      {
       "expr": "metrics_api_Driver_execute_Min{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-min"
      }
     ]
    },
    {
     "title": "Driver Run AVG Time(Percentile)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_api_Driver_run_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-50thPercentile"
      },
      {
       "expr": "metrics_api_Driver_run_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-75thPercentile"
      },
      {
       "expr": "metrics_api_Driver_run_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-95thPercentile"
      },
      {
       "expr": "metrics_api_Driver_run_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-99thPercentile"
      }
     ]
    },
    {
     "title": "Driver Execute AVG Time (Percentile)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "metrics_api_Driver_execute_50thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-50thPercentile"
      },
      {
       "expr": "metrics_api_Driver_execute_75thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-75thPercentile"
      },
      {
       "expr": "metrics_api_Driver_execute_95thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-95thPercentile"
      },
      {
       "expr": "metrics_api_Driver_execute_99thPercentile{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-99thPercentile"
      }
     ]
    }
   ]
  }
 ]
}