apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: ActionSet
metadata:
  name: rustfs-s3-full-br
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  backupType: Full
  env:
    - name: RUSTFS_API_PORT
      value: {{ .Values.rustfsAPIPort | quote }}
    - name: RUSTFS_BACKUP_FORMAT_VERSION
      value: "rustfs-s3-full.v1"
    - name: RUSTFS_MC_IMAGE
      value: {{ include "rustfs.mcImage" . | quote }}
  backup:
    backupData:
      image: {{ include "rustfs.mcImage" . }}
      syncProgress:
        enabled: true
        intervalSeconds: 5
      command:
        - sh
        - -c
        - |
          {{- .Files.Get "dataprotection/common.sh" | nindent 10 }}
          {{- .Files.Get "dataprotection/backup.sh" | nindent 10 }}
  restore:
    postReady:
      - job:
          image: {{ include "rustfs.mcImage" . }}
          command:
            - sh
            - -c
            - |
              {{- .Files.Get "dataprotection/common.sh" | nindent 14 }}
              {{- .Files.Get "dataprotection/restore.sh" | nindent 14 }}
