apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rustfs.configTplName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
data:
  RUSTFS_REPLICAS: "{{ "{{" }} .RUSTFS_COMP_REPLICAS {{ "}}" }}"
