{
 "title": "PolarDB-X Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(polardbx_up, namespace)"
    }
   },
   {
    "name": "polardbx",
    "query": {
     "query": "label_values(polardbx_up{namespace=\"$namespace\"}, app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS (Logical)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(polardbx_stats_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Logical"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(polardbx_stats_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "QPS (Logical)"
    },
    {
     "expr": "sum(irate(polardbx_stats_physical_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "QPS (Physical)"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stats_best_effort_transaction_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) +\n\nsum(rate(polardbx_stats_xa_transaction_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) +\n\nsum(rate(polardbx_stats_tso_transaction_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) ",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Connections/Threads",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(polardbx_stats_active_connections{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(polardbx_stats_running_count{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "Threads (Running)"
    }
   ]
  },
  {
   "title": "Response Time (Logical)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(polardbx_stats_request_time_cost_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) / (sum(delta (polardbx_stats_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) + 1) / 1000",
     "legendFormat": "Logical"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(polardbx_stats_request_time_cost_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) / (sum(delta (polardbx_stats_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) + 1) / 1000",
     "legendFormat": "RT (Logical)"
    },
    {
     "expr": "sum(delta(polardbx_stats_physical_request_time_cost_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) / (sum(delta (polardbx_stats_physical_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) + 1) / 1000",
     "legendFormat": "RT (Physical)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stats_error_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Topology",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_instance, pod, apps_kubeblocks_io_component_name, apps_kubeblocks_io_component_name) (mysql_up{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\", apps_kubeblocks_io_component_name=\"gms\"})\nor\nsum by (app_kubernetes_io_instance, pod, apps_kubeblocks_io_component_name, apps_kubeblocks_io_component_name) (polardbx_up{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"})\nor \nsum by (app_kubernetes_io_instance, pod, apps_kubeblocks_io_component_name, apps_kubeblocks_io_component_name) (mysql_up{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\", apps_kubeblocks_io_component_name=~\"dn-.*\"})\nor \nsum by (app_kubernetes_io_instance, pod, apps_kubeblocks_io_component_name, apps_kubeblocks_io_component_name) (polardbx_cdc_up{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"})\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Global Meta Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_queries{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "qps (physical)"
    }
   ]
  },
  {
   "title": "Connections/Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_threads_connected{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(mysql_global_status_threads_running{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"})",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"})",
     "legendFormat": "buffer pool size"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (GMS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "Buffer Pool Dirty/Flush (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_buffer_pool_dirty_pages{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"})",
     "legendFormat": "dirty"
    },
    {
     "expr": "sum(rate(mysql_global_status_buffer_pool_page_changes_total{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "flush"
    }
   ]
  },
  {
   "title": "Row Lock Current Wait (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_row_lock_current_waits{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"})",
     "legendFormat": "current wait"
    }
   ]
  },
  {
   "title": "Logical Reads/Writes (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_buffer_pool_read_requests{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_buffer_pool_write_requests{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "IOPS (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_log_writes{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\",  namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log writes"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_reads{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data reads"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_fsyncs{polardbx_name=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", kubeblocks_io_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data fsyncs"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_os_log_fsyncs{polardbx_name=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", kubeblocks_io_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log fsyncs"
    }
   ]
  },
  {
   "title": "IO Throughput (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_written{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data written/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_read{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data read/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_os_log_written{polardbx_name=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", kubeblocks_io_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log writtern/s"
    }
   ]
  },
  {
   "title": "Network (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_bytes_received{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "received/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_bytes_sent{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=\"gms\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "sent/s"
    }
   ]
  },
  {
   "title": "Compute Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stats_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "qps (logical)"
    },
    {
     "expr": "sum(rate(polardbx_stats_physical_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "qps (physical)"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(delta(polardbx_stats_request_time_cost_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) / (sum(delta (polardbx_stats_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) + 1) / 1000",
     "legendFormat": "rt (logical)"
    },
    {
     "expr": "sum(delta(polardbx_stats_physical_request_time_cost_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[30s])) / (sum(delta (polardbx_stats_physical_request_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[30s])) + 1) / 1000",
     "legendFormat": "rt (physical)"
    }
   ]
  },
  {
   "title": "Connections / Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(polardbx_stats_active_connections{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(polardbx_stats_running_count{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "threads (running)"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(idelta(polardbx_jvmstats_gc_collector_invocation_count{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m])) by (type)",
     "legendFormat": "count - {{ type }}"
    },
    {
     "expr": "sum(idelta(polardbx_jvmstats_gc_collector_time_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]) / (idelta(polardbx_jvmstats_gc_collector_invocation_count{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]) + 1)) by (type)",
     "legendFormat": "time - {{ type }}"
    }
   ]
  },
  {
   "title": "Connection Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stc_connection_error_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "connection error"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stats_best_effort_transaction_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "best effort"
    },
    {
     "expr": "sum(rate(polardbx_stats_xa_transaction_count_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "xa"
    },
    {
     "expr": "sum(rate(polardbx_stats_tso_transaction_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "tso"
    }
   ]
  },
  {
   "title": "Processing Time (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk(5, sum by (schema) (\n    label_replace(\n      rate(polardbx_stc_request_time_cost_total{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\", appname!~\"__.*__@.*|information_schema@.*|polardbx@.*\"}[1m]),\n      \"schema\",\n      \"$1\",\n      \"appname\",\n      \"(.*)@.*\"\n    )\n  )\n) by (schema)",
     "legendFormat": "{{ schema }}"
    }
   ]
  },
  {
   "title": "Physical Connection (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum by (schema) (\n    label_replace(\n      rate(polardbx_stc_active_physical_connection_count{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\", appname!~\"__.*__@.*|information_schema@.*|polardbx@.*\"}[1m]),\n      \"schema\",\n      \"$1\",\n      \"appname\",\n      \"(.*)@.*\"\n    )\n  )\n) by (schema)",
     "legendFormat": "active - {{ schema }}"
    },
    {
     "expr": "topk(5, sum by (schema) (\n    label_replace(\n      rate(polardbx_stc_pooling_physical_connection_count{polardbx_name=\"$polardbx\", namespace=\"$namespace\", appname!~\"__.*__@.*|information_schema@.*|polardbx@.*\"}[1m]),\n      \"schema\",\n      \"$1\",\n      \"appname\",\n      \"(.*)@.*\"\n    )\n  )\n) by (schema)",
     "legendFormat": "pooling - {{ schema }}"
    }
   ]
  },
  {
   "title": "Data Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_queries{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "qps (physical)"
    }
   ]
  },
  {
   "title": "Connections/Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_threads_connected{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(mysql_global_status_threads_running{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"})",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"})",
     "legendFormat": "buffer pool size"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "Buffer Pool Dirty/Flush (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_buffer_pool_dirty_pages{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"})",
     "legendFormat": "dirty"
    },
    {
     "expr": "sum(rate(mysql_global_status_buffer_pool_page_changes_total{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "flush"
    }
   ]
  },
  {
   "title": "Row Lock Current Wait (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_row_lock_current_waits{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"})",
     "legendFormat": "current wait"
    }
   ]
  },
  {
   "title": "Logical Reads/Writes (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_buffer_pool_read_requests{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_buffer_pool_write_requests{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "IOPS (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_log_writes{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\",  namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log writes"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_reads{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data reads"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_fsyncs{polardbx_name=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", kubeblocks_io_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data fsyncs"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_os_log_fsyncs{polardbx_name=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", kubeblocks_io_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log fsyncs"
    }
   ]
  },
  {
   "title": "IO Throughput (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_written{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data written/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_read{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data read/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_os_log_written{polardbx_name=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", kubeblocks_io_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log writtern/s"
    }
   ]
  },
  {
   "title": "Network (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_bytes_received{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "received/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_bytes_sent{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "sent/s"
    }
   ]
  },
  {
   "title": "XA Transactions (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\", command=~\"xa_.*\"}[1m])) by (command)",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Transactions (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{app_kubernetes_io_instance=\"$polardbx\", apps_kubeblocks_io_component_name=~\"dn-.*\", namespace=\"$namespace\", command=~\"begin|commit|rollback\"}[1m])) by (command)",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "CDC Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Delay(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "polardbx_cdc_dumper_delay_in_millisecond{namespace=\"$namespace\"}\n* on(namespace,pod)\ngroup_left() polardbx_cdc_up{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\", apps_kubeblocks_io_component_name=\"cdc\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Dumper Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "polardbx_cdc_dumper_jvm_heap_usage{namespace=\"$namespace\"}\n* on(namespace,pod)\ngroup_left() polardbx_cdc_up{app_kubernetes_io_instance=\"$polardbx\", namespace=\"$namespace\", apps_kubeblocks_io_component_name=\"cdc\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}