## Kubernetes cluster domain
clusterDomain: cluster.local

nameOverride: ""
fullnameOverride: ""

image:
  registry: docker.io
  repository: rustfs/rustfs
  pullPolicy: IfNotPresent
  mc:
    repository: minio/mc
    tag: latest
    digest: sha256:a7fe349ef4bd8521fb8497f55c6042871b2ae640607cf99d9bede5e9bdf11727

## @param versions RustFS versions configuration
versions:
  - version: "1.0.0-beta.8"
    tag: "1.0.0-beta.8"
    serviceVersion: "1.0.0-beta.8"
    isDefault: true

## Internal port number for RustFS S3 API
rustfsAPIPort: "9000"

## Internal port number for RustFS Console
rustfsConsolePort: "9001"

## TLS certificate path
certsPath: "/etc/rustfs/certs/"

## kblib required values
extra:
  keepResource: false
