apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: seaweedfs-dist
  namespace: demo
spec:
  clusterDef: seaweedfs
  topology: distributed
  terminationPolicy: DoNotTerminate
  componentSpecs:
  - name: master
    serviceVersion: 4.47.0
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    schedulingPolicy:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: seaweedfs-dist
                apps.kubeblocks.io/component-name: master
  - name: volume
    serviceVersion: 4.47.0
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    schedulingPolicy:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: seaweedfs-dist
                apps.kubeblocks.io/component-name: volume
  - name: filer
    serviceVersion: 4.47.0
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: s3
    serviceVersion: 4.47.0
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi
  - name: admin
    serviceVersion: "4.47.0"
    replicas: 1
    resources:
      requests: {cpu: "100m", memory: "256Mi"}
      limits: {cpu: "1", memory: "1Gi"}
    volumeClaimTemplates:
      - name: data
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
