apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: seaweedfs
  namespace: demo
spec:
  clusterDef: seaweedfs
  topology: standalone
  terminationPolicy: DoNotTerminate
  componentSpecs:
  - name: master
    serviceVersion: 4.47.0
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: volume
    serviceVersion: 4.47.0
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  - name: filer
    serviceVersion: 4.47.0
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: s3
    serviceVersion: 4.47.0
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: '1'
        memory: 1Gi
  - name: admin
    serviceVersion: "4.47.0"
    replicas: 1
    resources:
      requests: {cpu: "100m", memory: "256Mi"}
      limits: {cpu: "1", memory: "1Gi"}
    volumeClaimTemplates:
      - name: data
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
