apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: seaweedfs-restart
  namespace: demo
spec:
  clusterName: seaweedfs
  type: Restart
  restart:
  - componentName: master
  - componentName: volume
  - componentName: filer
  - componentName: s3
