apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: seaweedfs-s3-scale-in
  namespace: demo
spec:
  clusterName: seaweedfs
  type: HorizontalScaling
  horizontalScaling:
  - componentName: s3
    scaleIn:
      replicaChanges: 1
