apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orioledb.scriptsTemplate" . }}
  labels:
    {{- include "orioledb.labels" . | nindent 4 }}
data:
  {{- include "orioledb.extend.scripts" . | nindent 2 }}
  update-parameter.sh: |-
    {{- .Files.Get "reloader/update-parameter.sh" | nindent 4 }}
