apiVersion: apps.kubeblocks.io/v1
kind: ClusterDefinition
metadata:
  name: hbase
  labels:
    {{- include "hbase.labels" . | nindent 4 }}
  annotations:
    {{- include "hbase.apiVersion" . | nindent 4 }}
spec:
  topologies:
    - name: cluster
      default: true
      components:
        - name: hmaster
          compDef: {{ include "hbase.hmasterCmpdRegexPattern" . }}
        - name: hregionserver
          compDef: {{ include "hbase.hregionserverCmpdRegexPattern" . }}
      orders:
        provision:
          - hmaster
          - hregionserver
        terminate:
          - hregionserver
          - hmaster
        update:
          - hregionserver
          - hmaster
    - name: standalone
      components:
        - name: hbase-standalone
          compDef: {{ include "hbase.hbaseStandaloneCmpdRegexPattern" . }}
