apiVersion: apps.kubeblocks.io/v1
kind: ComponentDefinition
metadata:
  name: hbase-hregionserver-2.5
  labels:
    {{- include "hbase.labels" . | nindent 4 }}
  annotations:
    {{- include "hbase.apiVersion" . | nindent 4 }}
spec:
  provider: kubeblocks
  description: {{ .Chart.Description }}
  serviceKind: hbase-hregionserver
  serviceVersion: 2.5.6
  updateStrategy: BestEffortParallel
  services:
    - name: default
      spec:
        ports:
          - name: hregionserver
            port: 16020
  serviceRefDeclarations:
    - name: hbase-zookeeper
      serviceRefDeclarationSpecs:
        - serviceKind: zookeeper
          serviceVersion: "^*"
    - name: hadoop-namenode
      serviceRefDeclarationSpecs:
        - serviceKind: hdfs-namenode
          serviceVersion: "^*"
  runtime:
    initContainers:
      - name: init-regionserver
        imagePullPolicy: {{ default "IfNotPresent" .Values.init.image.pullPolicy }}
        command: [ "/hbase/scripts/hbase-config-setup.sh" ]
        env:
          - name: KB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KB_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KB_CLUSTER_COMP_NAME
            value: hregionserver
          - name: CLUSTER_DOMAIN
            value: {{ .Values.extra.clusterDomain | default "cluster.local" }}
          - name: HADOOP_CLUSTER_NAME
            value: {{ .Values.hadoopClusterName | quote }}
          - name: HBASE_ROOT_DIR
            value: {{ .Values.hbaseRootDir | default "hbase" | quote }}
          - name: HBASE_ZK_PARENT
            value: {{ .Values.hbaseZkParent | default "/hbase" | quote }}
        securityContext:
          runAsUser: 10000
          runAsGroup: 1000
        volumeMounts:
          - name: hbase-orig-conf
            mountPath: /hbase/origconf/hbase-site.xml
            subPath: hbase-site.xml
          - name: hbase-orig-conf
            mountPath: /hbase/origconf/log4j.properties
            subPath: log4j.properties
          - name: hadoop-core-config
            mountPath: /hadoop/conf/core-site.xml
            subPath: core-site.xml
          - name: hadoop-hdfs-config
            mountPath: /hadoop/conf/hdfs-site.xml
            subPath: hdfs-site.xml
          - name: hbase-scripts
            mountPath: /hbase/scripts
          - name: hbase-conf
            mountPath: /hbase/conf
    containers:
      - name: hbase-hregionserver
        imagePullPolicy: {{ default "IfNotPresent" .Values.hregionserver.image.pullPolicy }}
        ports:
          - containerPort: 16020
            name: hregionserver
        env:
          - name: DEBUG_MODEL
            value: "false"
          - name: HBASE_CONF_DIR
            value: /hbase/conf
          - name: HADOOP_CONF_DIR
            value: /hadoop/conf
          - name: HBASE_CLASSPATH
            value: /hadoop/conf
          - name: CURRENT_POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: hbase-orig-conf
            mountPath: /hbase/origconf/hbase-site.xml
            subPath: hbase-site.xml
          - name: hbase-orig-conf
            mountPath: /hbase/origconf/log4j.properties
            subPath: log4j.properties
          - name: hadoop-core-config
            mountPath: /hadoop/conf/core-site.xml
            subPath: core-site.xml
          - name: hadoop-hdfs-config
            mountPath: /hadoop/conf/hdfs-site.xml
            subPath: hdfs-site.xml
          - name: hbase-scripts
            mountPath: /hbase/scripts
          - name: hbase-conf
            mountPath: /hbase/conf
          - name: hbase-temp-data
            mountPath: /hbase/temp
        securityContext:
          runAsUser: 10000
          runAsGroup: 1000
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
          seccompProfile:
            type: "RuntimeDefault"
    securityContext:
      fsGroupChangePolicy: Always
      fsGroup: 1000
    volumes:
      - name: hbase-conf
        emptyDir: {}
  vars:
    - name: ZOOKEEPER_HOST
      valueFrom:
        serviceRefVarRef:
          name: hbase-zookeeper
          host: Required
          optional: true
    - name: HADOOP_NAMENODE_ENDPOINTS
      valueFrom:
        serviceRefVarRef:
          name: hadoop-namenode
          endpoint: Required
          optional: true
  configs:
    - name: hbase-orig-conf
      template: hbase-config-template
      volumeName: hbase-orig-conf
      namespace: {{ .Release.Namespace }}
      defaultMode: 0755
  scripts:
    - name: hbase-scripts
      template: hbase-scripts
      volumeName: hbase-scripts
      namespace: {{ .Release.Namespace }}
      defaultMode: 0755