apiVersion: apps.kubeblocks.io/v1
kind: ComponentVersion
metadata:
  name: hbase-hregionserver
  labels:
    {{- include "hbase.labels" . | nindent 4 }}
  annotations:
    {{- include "hbase.apiVersion" . | nindent 4 }}
spec:
  compatibilityRules:
    - compDefs:
        - hbase-hregionserver-2.5
      releases:
        - 2.5.6
  releases:
    - name: 2.5.6
      serviceVersion: 2.5.6
      images:
        hbase-hregionserver: {{ include "hbase.hregionserverImage" . | quote }}
        jmx-exporter: {{ include "hbase.jmxExporterImage" . | quote }}
