apiVersion: v1
kind: ConfigMap
metadata:
  name: hbase-scripts
  labels:
    {{- include "hbase.labels" . | nindent 4 }}
data:
  start-hmaster.sh: |-
    {{- .Files.Get "scripts/start-hmaster.sh" | nindent 4 }}
  start-hregionserver.sh: |-
    {{- .Files.Get "scripts/start-hregionserver.sh" | nindent 4 }}
  init-hdfs-root-layout.sh: |-
    {{- .Files.Get "scripts/init-hdfs-root-layout.sh" | nindent 4 }}
  check-hmaster-live.sh: |-
    {{- .Files.Get "scripts/check-hmaster-live.sh" | nindent 4 }}
  check-hmaster-ready.sh: |-
    {{- .Files.Get "scripts/check-hmaster-ready.sh" | nindent 4 }}
  check-hregionserver-live.sh: |-
    {{- .Files.Get "scripts/check-hregionserver-live.sh" | nindent 4 }}
  check-hregionserver-ready.sh: |-
    {{- .Files.Get "scripts/check-hregionserver-ready.sh" | nindent 4 }}
  check-hmaster-status.sh: |-
    {{- .Files.Get "scripts/check-hmaster-status.sh" | nindent 4 }}
  check-hregionserver-status.sh: |-
    {{- .Files.Get "scripts/check-hregionserver-status.sh" | nindent 4 }}
