apiVersion: v1
kind: ConfigMap
metadata:
  name: hbase-cluster-config-template
  labels:
    {{- include "hbase.labels" . | nindent 4 }}
data:
  hbase-site.xml: |-
    {{- .Files.Get "config/hbase-site-cluster.tpl" | nindent 4 }}
  core-site.xml: |-
    {{- .Files.Get "config/hdfs-common-site.tpl" | nindent 4 }}
  hdfs-site.xml: |-
    {{- .Files.Get "config/hdfs-client-site.tpl" | nindent 4 }}
  hbase-env.sh: |-
    {{- .Files.Get "config/hbase-env.sh.tpl" | nindent 4 }}
  hadoop-metrics2-hbase.properties: |-
    {{- .Files.Get "config/hadoop-metrics2-hbase.properties.tpl" | nindent 4 }}
  log4j.properties: |-
    {{- .Files.Get "config/log4j.properties" | nindent 4 }}
