{
 "title": "TDengine for 3.x",
 "description": "Metrics display for TDengine database for 3.x",
 "tags": [
  "TDengine1",
  "Prometheus",
  "TaosKeeper"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(taos_cluster_info_version,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(taos_cluster_info_version{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(taos_cluster_info_version{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "First EP",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "taos_cluster_info_first_ep{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "formatType": "Time series",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "taos_cluster_info_version{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "formatType": "Time series",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Master Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(taos_cluster_info_master_uptime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
       "formatType": "Time series",
       "legendFormat": "{{pod}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Expire Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(taos_grants_info_expire_time{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
       "formatType": "Time series",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Databases",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "expr": "max(taos_cluster_info_dbs_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
       "formatType": "Time series",
       "legendFormat": "databases",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Super Tables",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "expr": "max(taos_cluster_info_stbs_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
       "formatType": "Time series",
       "legendFormat": "databases",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "expr": "max(taos_cluster_info_tbs_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
       "formatType": "Time series",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Streams",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "expr": "max(taos_cluster_info_streams_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
       "formatType": "Time series",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Topics",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 67 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "dnodes",
       "expr": "max(taos_cluster_info_topics_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
       "formatType": "Time series",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "DNodes/MNodes/VNodes",
     "type": "table",
     "description": "当前TDengine集群DNode数量，Alive 为存活，Total 为所有",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "taos_cluster_info_dnodes_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "taos_cluster_info_mnodes_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "taos_cluster_info_vnodes_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "taos_cluster_info_vgroups_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "taos_cluster_info_connections_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "formatType": "Time series",
       "legendFormat": "{{pod}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Measuring Points Used Percent Alert",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "taos_grants_info_timeseries_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} / taos_grants_info_timeseries_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "formatType": "Time series",
       "legendFormat": "{{pod}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Dnode Thread Used Disk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(taos_dnodes_info_disk_engine{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_ep) / avg(taos_dnodes_info_disk_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VNodes Alive Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "taos_cluster_info_vnodes_alive{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} / taos_cluster_info_vnodes_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "formatType": "Time series",
       "legendFormat": "{{pod}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "DNodes Alive Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "taos_cluster_info_dnodes_alive / taos_cluster_info_dnodes_total",
       "formatType": "Time series",
       "legendFormat": "{{pod}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VGroups Alive Percent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "taos_cluster_info_vgroups_alive / taos_cluster_info_vgroups_total",
       "formatType": "Time series",
       "legendFormat": "{{pod}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Grants Expire Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "taos_grants_info_expire_time",
       "formatType": "Time series",
       "legendFormat": "{{pod}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "MNodes Alive Percent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "taos_cluster_info_mnodes_alive / taos_cluster_info_mnodes_total",
       "formatType": "Time series",
       "legendFormat": "{{pod}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "DNode Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "fqdn",
   "collapsed": true,
   "panels": [
    {
     "title": "DNode Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_dnodes_info_has_mnode{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_dnodes_info_cpu_cores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_ep)",
       "legendFormat": "{{dnode_ep}}"
      },
      {
       "expr": "max(taos_dnodes_info_vnodes_num{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_ep)",
       "legendFormat": "{{dnode_ep}}"
      },
      {
       "expr": "max(taos_dnodes_info_masters{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_ep)",
       "legendFormat": "{{dnode_ep}}"
      },
      {
       "expr": "max(taos_dnodes_info_has_qnode{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_dnodes_info_has_snode{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "MNode Role",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_m_info_role{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (mnode_ep,value)",
       "formatType": "Time series",
       "legendFormat": "{{mnode_ep}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "VGroup Status",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_taosd_vgroups_info_status{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (database_name,vgroup_id)",
       "formatType": "Time series",
       "legendFormat": "{{database_name}}",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_taosd_vgroups_info_tables_num{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (database_name,vgroup_id)",
       "formatType": "Time series",
       "legendFormat": "{{database_name}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "DNode  Status",
     "type": "table",
     "description": "当前TDengine集群DNode数量，Alive 为存活，Total 为所有",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "taos_d_info_status{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "taos_dnodes_info_uptime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Vgroup Role",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_taosd_vnodes_info_role{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (dnode_id,value, vgroup_id,database_name)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_id}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "max(avg_over_time(taos_dnodes_info_mem_engine{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-taosd",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(avg_over_time(taos_dnodes_info_mem_system{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-system",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "CPU 资源占用情况。",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(avg_over_time(taos_dnodes_info_cpu_engine{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-taosd",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(avg_over_time(taos_dnodes_info_cpu_system{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-system",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Data Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(avg_over_time(taos_taosd_dnodes_data_dirs_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}_used",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(avg_over_time(taos_taosd_dnodes_data_dirs_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}_total",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Data Disk Used Increasing Rate per Minute",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "level0",
       "expr": "max(deriv(rate(taos_taosd_dnodes_data_dirs_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[1m])[5m:1s])  * 1024) by (dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max(avg_over_time(taos_dnodes_info_io_write_disk{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[1m])) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-io_write_disk",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(avg_over_time(taos_dnodes_info_io_read_disk{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[1m])) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-io_read_disk",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Net",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max(avg_over_time(taos_dnodes_info_net_in{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[1m])) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-net_in",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(avg_over_time(taos_dnodes_info_net_out{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[1m])) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-net_out",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Logs Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max(avg_over_time(taos_taosd_dnodes_log_dirs_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[1m])) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-used",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(avg_over_time(taos_taosd_dnodes_log_dirs_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[1m])) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-total",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Select",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1360 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(max(taos_taosd_sql_req_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",sql_type=~\"select\",result=\"Success\"}) by(dnode_ep,vgroup_id)) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "sum(max(taos_taosd_sql_req_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",sql_type=~\"select\",result=\"Failed\"}) by(dnode_ep,vgroup_id)) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-failed",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Insert",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1360 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(max(taos_taosd_sql_req_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",sql_type=~\"insert\",result=\"Success\"}) by(dnode_ep,vgroup_id)) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "sum(max(taos_taosd_sql_req_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",sql_type=~\"insert\",result=\"Failed\"}) by(dnode_ep,vgroup_id)) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-failed",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Inserted Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1368 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(max(taos_taosd_sql_req_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",sql_type=~\"inserted_rows\",result=\"Success\"}) by(dnode_ep,vgroup_id)) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "sum(max(taos_taosd_sql_req_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",sql_type=~\"inserted_rows\",result=\"Failed\"}) by(dnode_ep,vgroup_id)) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-failed",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Delete",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1368 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(max(taos_taosd_sql_req_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",sql_type=~\"delete\",result=\"Success\"}) by(dnode_ep,vgroup_id)) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "sum(max(taos_taosd_sql_req_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",sql_type=~\"delete\",result=\"Failed\"}) by(dnode_ep,vgroup_id)) by(dnode_ep)",
       "formatType": "Time series",
       "legendFormat": "{{dnode_ep}}-failed",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "Adapter Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests HTTP",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_adapter_requests_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-total",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_success{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_fail{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-fail",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_in_process{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-inprocess",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Requests WebSocket",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 437 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_adapter_requests_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-total",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_success{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_fail{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-fail",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_in_process{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-inprocess",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Query Requests HTTP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 446 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_adapter_requests_query{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-total",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_query_success{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_query_fail{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-fail",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_query_in_process{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-inprocess",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Query Requests WebScoket",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 446 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_adapter_requests_query{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-total",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_query_success{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_query_fail{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-fail",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_query_in_process{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-inprocess",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Write Requests HTTP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_adapter_requests_write{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-total",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_write_success{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_write_fail{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-fail",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_write_in_process{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-inprocess",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Write Requests WebSocket",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_adapter_requests_write{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-total",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_write_success{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_write_fail{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-fail",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_write_in_process{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-inprocess",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Other Requests HTTP",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 466 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_adapter_requests_other{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-total",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_other_success{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_other_fail{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"0\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-fail",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Other Requests WebSocket",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 466 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(taos_adapter_requests_other{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-total",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_other_success{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-success",
       "target": "select metric",
       "type": "timeserie"
      },
      {
       "expr": "max(taos_adapter_requests_other_fail{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",req_type=~\"1\"}) by(pod)",
       "formatType": "Time series",
       "legendFormat": "{{pod}}-fail",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "Keeper Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 438 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(taos_keeper_monitor_cpu{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by(identify)",
       "formatType": "Time series",
       "legendFormat": "{{identify}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 438 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(taos_keeper_monitor_mem{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by(identify)",
       "formatType": "Time series",
       "legendFormat": "{{identify}}",
       "target": "select metric",
       "type": "timeserie"
      }
     ]
    }
   ]
  }
 ]
}