{
 "title": "HALO Exporter Copy",
 "description": "Halo Exporter Dashboard ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "label_values(node)" }
  ]
 },
 "panels": [
  {
   "title": "Postgres Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_error_count{node=\"$node\"}[20s])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Exporter Up Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_exporter_uptime{node=\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_exporter_server_scrape_duration{node=\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Scrape Per Minute",
   "type": "graph",
   "description": "Scrape Count",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(pg_exporter_server_scrape_total_count{node=\"$node\"}[1m])",
     "legendFormat": "Scrape"
    },
    {
     "expr": "increase(pg_exporter_server_scrape_error_count{node=\"$node\"}[1m])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_duration{node=\"$node\"}[1m]) / increase(pg_exporter_query_scrape_total_count{node=\"$node\"}[1m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Metrics Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_exporter_query_scrape_metric_count{node=\"$node\"}",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_hit_count{node=\"$node\"}[5m]) / increase(pg_exporter_query_scrape_total_count{node=\"$node\"}[5m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Pgbouncer Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(pgbouncer_exporter_query_scrape_error_count{node=\"$node\"}[20s])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Exporter Up Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_exporter_uptime{node=\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_exporter_server_scrape_duration{node=\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Scrape Per Minute",
   "type": "graph",
   "description": "Scrape Count",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(pgbouncer_exporter_server_scrape_total_count{node=\"$node\"}[1m])",
     "legendFormat": "Scrape"
    },
    {
     "expr": "increase(pgbouncer_exporter_server_scrape_error_count{node=\"$node\"}[1m])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "graph",
   "gridPos": { "h": 21, "w": 15, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(pgbouncer_exporter_query_scrape_duration{node=\"$node\"}[1m]) / increase(pgbouncer_exporter_query_scrape_total_count{node=\"$node\"}[1m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Metrics Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_exporter_query_scrape_metric_count{node=\"$node\"}",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(pgbouncer_exporter_query_scrape_hit_count{node=\"$node\"}[5m]) / increase(pgbouncer_exporter_query_scrape_total_count{node=\"$node\"}[5m])",
     "legendFormat": "{{query}}"
    }
   ]
  }
 ]
}