{
 "title": "HDFS-NameNode",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Active_NameNode",
    "label": "Active_NameNode",
    "query": "query_result(avg(hadoop_hdfs_namenode_fsname_system_hastate == 1) by (_target))"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(hadoop_hdfs_namenode_nninfo_total, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NameNode Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_hastate{cluster = \"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "Number of datanode in each state",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_fsname_system_state_num_decom_live_data_nodes{cluster = \"$cluster\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_last_contact",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_nninfo_live_nodes_last_contact{_target=\"$Active_NameNode\", cluster=\"$cluster\"}",
     "legendFormat": "{{_target}} <-- {{datanode}}"
    }
   ]
  },
  {
   "title": "fsname_system_state_fsstate",
   "type": "stat",
   "description": "\"FSState\": \"Current state of the file system: 0 (for Safemode) or 1(Operational)\"",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_state_fsstate{_target=\"$Active_NameNode\"}"
    }
   ]
  },
  {
   "title": "fsname_system_capacity_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_fsname_system_capacity_bytes{cluster=\"$cluster\"}) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_nninfo_live_nodes_capacity{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_nninfo_live_nodes_used{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_remaining",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_nninfo_live_nodes_remaining{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_block_pool_used_percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_nninfo_live_nodes_block_pool_used_percent{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_block_pool_used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_nninfo_live_nodes_block_pool_used{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_block_scheduled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_hdfs_namenode_nninfo_live_nodes_block_scheduled{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "fsname_system_num_files_under_construction",
   "type": "graph",
   "description": " \"NumFilesUnderConstruction\": \"Current number of files under construction\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_num_files_under_construction{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "fsname_system_num_active_clients",
   "type": "graph",
   "description": "\"NumActiveClients\": \"Current number of active clients holding lease\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_num_active_clients{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "namenode_rpc_num_open_connections",
   "type": "graph",
   "description": "Current number of open connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_rpc_num_open_connections{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}} {{tag}}"
    }
   ]
  },
  {
   "title": "namenode_rpc_slow_calls",
   "type": "graph",
   "description": "Total number of RPC slow calls",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_rpc_slow_calls{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}} {{tag}}"
    }
   ]
  },
  {
   "title": "namenode_nnactivity_operations_total_rate",
   "type": "graph",
   "description": "Total rate of each operation.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(hadoop_hdfs_namenode_nnactivity_operations_total{cluster=\"$cluster\", _target=\"$Active_NameNode\"}[2m])) by (_target, method)",
     "legendFormat": "{{_target}}  {{method}}"
    }
   ]
  },
  {
   "title": "fsname_system_total_load",
   "type": "graph",
   "description": " \"TotalLoad\": \"Current number of connections\",",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_total_load{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  { "title": "统计数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "fsname_system_files_total",
   "type": "graph",
   "description": "\"FilesTotal\": \"Current number of files and directories\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_files_total{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "fsname_system_blocks_total",
   "type": "graph",
   "description": "\"BlocksTotal\": \"Current number of allocated blocks in the system\",",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_blocks_total{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "fsname_system_state_volume_failures_total",
   "type": "graph",
   "description": "\"VolumeFailuresTotal\": \"Total number of volume failures across all Datanodes\"",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_state_volume_failures_total{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_volfails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (hadoop_hdfs_namenode_nninfo_live_nodes_volfails{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "namenode_nninfo_corrupt_file_count",
   "type": "graph",
   "description": "Corrupt file count",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_nninfo_corrupt_file_count{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "fsname_system_corrupt_blocks",
   "type": "graph",
   "description": "\"CorruptBlocks\": \"Current number of blocks with corrupt replicas.\"",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_corrupt_blocks{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_num_blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (hadoop_hdfs_namenode_nninfo_live_nodes_num_blocks{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "fsname_system_pending_replication_blocks",
   "type": "graph",
   "description": "\"PendingReplicationBlocks\": \"Current number of blocks pending to be replicated\",",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_pending_replication_blocks{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "fsname_system_missing_blocks",
   "type": "graph",
   "description": "\"MissingBlocks\": \"Current number of missing blocks\",",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_missing_blocks{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "fsname_system_under_replicated_blocks",
   "type": "graph",
   "description": "\"UnderReplicatedBlocks\": \"Current number of blocks under replicated\",",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_under_replicated_blocks",
     "legendFormat": "{{cluster}} {{_target}}"
    }
   ]
  },
  {
   "title": "nninfo_live_nodes_non_dfs_used_space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_nninfo_live_nodes_non_dfs_used_space{cluster=\"$cluster\"}) by (datanode)",
     "legendFormat": "{{datanode}}"
    }
   ]
  },
  {
   "title": "fsname_system_stale_data_nodes",
   "type": "graph",
   "description": "\"StaleDataNodes\": \"Current number of DataNodes marked stale due to delayed heartbeat\"",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_stale_data_nodes{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  { "title": "NameNode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "namenode_jvm_gc_exceeded_threshold_total_rate",
   "type": "graph",
   "description": "Rate that the GC threshold is exceeded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_namenode_jvm_gc_exceeded_threshold_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "{{_target}} {{type}}"
    }
   ]
  },
  {
   "title": "hadoop_hdfs_namenode_jvm_gc_count",
   "type": "graph",
   "description": "GC count of each type GC.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_jvm_gc_count{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}} {{type}}"
    }
   ]
  },
  {
   "title": "namenode_jvm_gc_time_milliseconds",
   "type": "graph",
   "description": "Each type GC time in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_jvm_gc_time_milliseconds{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}_{{type}}"
    }
   ]
  },
  {
   "title": "namenode_jvm_gc_total_extra_sleep_time",
   "type": "graph",
   "description": "Total GC extra sleep time in msec.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_jvm_gc_total_extra_sleep_time{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "namenode_rpc_method_called_total_rate",
   "type": "graph",
   "description": "Total rate of the times the method is called.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(hadoop_hdfs_namenode_rpc_method_called_total{cluster=\"$cluster\"}[2m])",
     "legendFormat": "{{_target}}_{{method}}_{{tag}}"
    }
   ]
  },
  {
   "title": "namenode_rpc_method_avg_time_milliseconds",
   "type": "graph",
   "description": "Average turn around time of the method in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_rpc_method_avg_time_milliseconds{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}_{{method}}_{{tag}}"
    }
   ]
  },
  {
   "title": "namenode_rpc_detailed_method_called_rate",
   "type": "graph",
   "description": "Total  rate the method is called",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(hadoop_hdfs_namenode_rpc_detailed_method_called_total{cluster=\"$cluster\"}[2m])) by (_target, method, tag)",
     "legendFormat": "{{_target}}_{{method}}_{{tag}}"
    }
   ]
  },
  {
   "title": "namenode_rpc_detailed_method_avg_time_milliseconds",
   "type": "graph",
   "description": "Average turn around time of the method in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_rpc_detailed_method_avg_time_milliseconds{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}_{{method}}_{{tag}}"
    }
   ]
  },
  {
   "title": "namenode_nnactivity_method_ops_rate",
   "type": "graph",
   "description": "Total rate the method is called.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(hadoop_hdfs_namenode_nnactivity_method_ops_total{cluster=\"$cluster\"}[2m]))by (method,_target)",
     "legendFormat": "{{_target}} {{method}}"
    }
   ]
  },
  {
   "title": "namenode_nnactivity_method_avg_time_milliseconds",
   "type": "graph",
   "description": "Average turn around time of the method in milliseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(hadoop_hdfs_namenode_nnactivity_method_avg_time_milliseconds{cluster=\"$cluster\"}) by (_target, method)",
     "legendFormat": "{{_target}}  {{method}}"
    }
   ]
  },
  {
   "title": "namenode_rpc_call_queue_length",
   "type": "graph",
   "description": "Current length of the call queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_rpc_call_queue_length{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}_{{tag}}"
    }
   ]
  },
  {
   "title": "namenode_rpc_client_backoff",
   "type": "graph",
   "description": "Total number of RPC client back off",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_rpc_client_backoff{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}_{{tag}}"
    }
   ]
  },
  {
   "title": "namenode_fsname_system_lock_queue_length",
   "type": "graph",
   "description": "Number of threads waiting to acquire FSNameSystem lock",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_lock_queue_length{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "namenode_fsname_system_transactions_since_last_checkpoint",
   "type": "graph",
   "description": "Total number of transactions since last checkpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_transactions_since_last_checkpoint{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "namenode_fsname_system_transactions_since_last_log_roll",
   "type": "graph",
   "description": "Total number of transactions since last edit log roll",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_transactions_since_last_log_roll{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "namenode_jvm_threads_state_total",
   "type": "graph",
   "description": "Current number of different threads.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_jvm_threads_state_total{cluster=\"$cluster\"}",
     "legendFormat": "{{_target}}_{{state}}"
    }
   ]
  },
  {
   "title": "namenode_fsname_system_expired_heartbeats",
   "type": "graph",
   "description": "Total number of expired heartbeats",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "hadoop_hdfs_namenode_fsname_system_expired_heartbeats{cluster=\"$cluster\"}",
     "legendFormat": " {{_target}}"
    }
   ]
  }
 ]
}