{
 "title": "Hadoop HDFS DataNode",
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(Hadoop_DataNode_MemMaxM,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(Hadoop_DataNode_MemMaxM{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(Hadoop_DataNode_MemMaxM{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - Hadoop_DataNode_DNStartedTimeInMillis{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}/1000"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_DNStartedTimeInMillis{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join({__name__=~\"jvm_runtime_info|jvm_runtime\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"},\"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-system"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-process"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-total"
    },
    {
     "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-committed-vm"
    },
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-free"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-virtual-mem"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-resident-mem"
    }
   ]
  },
  {
   "title": "JVM Memory(Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-used"
    }
   ]
  },
  {
   "title": "JVM memory(NonHeap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_max{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-used"
    }
   ]
  },
  {
   "title": "JVM Memory(Committed)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-{{area}}"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Code Cache]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Compressed Class Spacee]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Eden Space]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Metaspace]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Survivor Space]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Tenured Gen]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", apps_kubeblocks_io_component_name=\"datanode\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "GC time Sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
     "legendFormat": "{{pod}}-{{gc}}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
     "legendFormat": "{{pod}}-{{gc}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-loaded"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=~\"$namespace\",apps_kubeblocks_io_component_name=\"datanode\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-deadlocked threads"
    }
   ]
  },
  {
   "title": "DataNode FSDataSet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "DataNode Capacity",
     "type": "timeseries",
     "description": "Current raw capacity of DataNode in bytes",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_Capacity{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "DFS Used",
     "type": "timeseries",
     "description": "Current space used by DataNodes for DFS purposes in bytes",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_Remaining{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "DataNode Remaing",
     "type": "timeseries",
     "description": "Current remaining capacity in bytes",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_Remaining{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Failed Volumes",
     "type": "timeseries",
     "description": "Total number of failed volumes",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_NumFailedVolumes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Estimated Capacity Lost Total ",
     "type": "timeseries",
     "description": "An estimate of the total capacity lost due to volume failures",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 271 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_EstimatedCapacityLostTotal{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Cached Capacity/Used",
     "type": "timeseries",
     "description": "Current raw capacity/used of cache in bytes",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 271 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_CacheCapacity{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",name=\"FSDatasetState\"}",
       "legendFormat": "{{pod}}-{{name}}"
      },
      {
       "expr": "Hadoop_DataNode_CacheUsed{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",name=\"FSDatasetState\"}",
       "legendFormat": "{{pod}}-{{name}}-used"
      }
     ]
    },
    {
     "title": "Num Blocks Cached",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 271 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(Hadoop_DataNode_NumBlocksCached{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",name=\"FSDatasetState\"}[2m])",
       "legendFormat": "{{pod}}-{{total}}"
      },
      {
       "expr": "rate(Hadoop_DataNode_NumBlocksFailedToCache{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",name=\"FSDatasetState\"}[2m])",
       "legendFormat": "{{pod}}-failed-cache"
      },
      {
       "expr": "rate(Hadoop_DataNode_NumBlocksFailedToUnCache{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",name=\"FSDatasetState\"}[2m])",
       "legendFormat": "{{pod}}-failed-uncache"
      }
     ]
    }
   ]
  },
  { "title": "DataNode Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Read/Written Bytes Rate",
   "type": "timeseries",
   "description": "Total rate of bytes written/read to DataNode",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_BytesWritten{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-write"
    },
    {
     "expr": "rate(Hadoop_DataNode_BytesRead{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-read"
    }
   ]
  },
  {
   "title": "Read/Write Operation Spent(milliseconds)",
   "type": "timeseries",
   "description": "Total number of milliseconds spent on read/write operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_TotalWriteTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-write"
    },
    {
     "expr": "rate(Hadoop_DataNode_TotalReadTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-read"
    }
   ]
  },
  {
   "title": "Read Count Rate From Client",
   "type": "timeseries",
   "description": "Total Reads number of each operations from different client",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_ReadsFromRemoteClient{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-local"
    },
    {
     "expr": "rate(Hadoop_DataNode_ReadsFromRemoteClient{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-remote"
    }
   ]
  },
  {
   "title": "Write Rate Count From Client",
   "type": "timeseries",
   "description": "Total Write number of each operations from different client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_WritesFromRemoteClient{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-local"
    },
    {
     "expr": "rate(Hadoop_DataNode_WritesFromRemoteClient{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-remote"
    }
   ]
  },
  {
   "title": "Operation Blocks Count Rate",
   "type": "timeseries",
   "description": "Total number of blocks in different operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_ReadBlockOpNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-read"
    },
    {
     "expr": "rate(Hadoop_DataNode_WriteBlockOpNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-write"
    },
    {
     "expr": "rate(Hadoop_DataNode_CopyBlockOpNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-copy"
    },
    {
     "expr": "rate(Hadoop_DataNode_ReplaceBlockOpNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-replace"
    }
   ]
  },
  {
   "title": "Operation Blocks AVG Time",
   "type": "timeseries",
   "description": "Total number of blocks in different operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_ReadBlockOpAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-read"
    },
    {
     "expr": "Hadoop_DataNode_WriteBlockOpAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-write"
    },
    {
     "expr": "Hadoop_DataNode_CopyBlockOpAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-copy"
    },
    {
     "expr": "Hadoop_DataNode_ReplaceBlockOpAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-replace"
    }
   ]
  },
  {
   "title": "Send Data packets Rate",
   "type": "timeseries",
   "description": "Total rate of sending packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_SendDataPacketTransferNanosNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Send Data Packet Transfer Avg Time",
   "type": "timeseries",
   "description": "Average transfer time of sending packets in nanoseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_SendDataPacketTransferNanosAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Send data Packet Blocked On Network Rate",
   "type": "timeseries",
   "description": "Total number of sending packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_SendDataPacketBlockedOnNetworkNanosNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Send Data Packet Blocked On Network AVG Time",
   "type": "timeseries",
   "description": "Average waiting time of sending packets in nanoseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_SendDataPacketBlockedOnNetworkNanosAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fsync Operations Number",
   "type": "timeseries",
   "description": "Total number of fsync",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_FsyncNanosNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fsync AVG Time",
   "type": "timeseries",
   "description": "Average fsync time in nanoseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_FsyncNanosAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush Operations Number",
   "type": "timeseries",
   "description": "Total number of Flush",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_FlushNanosNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush AVG Time",
   "type": "timeseries",
   "description": "Average fsync time in nanoseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_FlushNanosAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM DISK Operations Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_RamDiskBlocksWrite{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-blocks-write"
    },
    {
     "expr": "rate(Hadoop_DataNode_RamDiskBlocksEvicted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-blocks-evicted"
    },
    {
     "expr": "rate(Hadoop_DataNode_RamDiskBlocksReadHits{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-blocks-read-hits"
    },
    {
     "expr": "rate(Hadoop_DataNode_RamDiskBlocksWriteFallback{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-blocks-write-fallback"
    },
    {
     "expr": "rate(Hadoop_DataNode_RamDiskBlocksLazyPersisted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-blocks-lazy-persisted"
    }
   ]
  },
  {
   "title": "RAM DISK Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_RamDiskBytesLazyPersisted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-lazy-persisted"
    },
    {
     "expr": "rate(Hadoop_DataNode_RamDiskBytesWrite{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}-blocks-write"
    }
   ]
  },
  {
   "title": "Network Errors Rate",
   "type": "timeseries",
   "description": "Total rate of datanode network error",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_DatanodeNetworkErrors{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fsync Count",
   "type": "timeseries",
   "description": "Total number of fsync",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_FsyncCount{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total GC Count",
   "type": "timeseries",
   "description": "GC count of each type GC.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_GcCount{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total GC Extra Sleep time",
   "type": "timeseries",
   "description": "Total GC extra sleep time in msec.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_GcTotalExtraSleepTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Threshold Exceeded",
   "type": "timeseries",
   "description": "Number of times that the GC threshold is exceeded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_GcNumInfoThresholdExceeded{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total GC Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_GcTimeMillis{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}