{
 "title": "Hadoop HDFS NodeManager",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(Hadoop_NodeManager_AllocatedGB,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(Hadoop_NodeManager_AllocatedGB{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(Hadoop_NodeManager_AllocatedGB{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "System Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - java_lang_Runtime_StartTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}/1000"
      }
     ]
    },
    {
     "title": "Available CPUs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_Runtime_StartTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "JVM Version",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_join(jvm_runtime_info{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
      }
     ]
    },
    {
     "title": "CPU load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemCpuLoad{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-system"
      },
      {
       "expr": "java_lang_OperatingSystem_ProcessCpuLoad{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-process"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Physical memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-total"
      },
      {
       "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-committed-vm"
      },
      {
       "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-free"
      }
     ]
    },
    {
     "title": "Process memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-virtual-mem"
      },
      {
       "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-resident-mem"
      }
     ]
    },
    {
     "title": "JVM Memory(Heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_Memory_HeapMemoryUsage_max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "java_lang_Memory_HeapMemoryUsage_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-used"
      }
     ]
    },
    {
     "title": "JVM memory(NonHeap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_Memory_NonHeapMemoryUsage_max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "java_lang_Memory_NonHeapMemoryUsage_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-used"
      }
     ]
    },
    {
     "title": "JVM Memory(Committed)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{area}}"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Code Cache]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Compressed Class Spacee]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Eden Space]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Eden Space|PS Eden Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Metaspace]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Survivor Space]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Survivor Space|PS Survivor Space\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "JVM Memory pool [Tenured Gen]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
     "repeat": "mempool",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
       "legendFormat": "{{pod}}-max"
      },
      {
       "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
       "legendFormat": "{{pod}}-used"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
       "legendFormat": "{{pod}}-committed"
      },
      {
       "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=~\"Tenured Gen|PS Old Gen\"}",
       "legendFormat": "{{pod}}-init"
      }
     ]
    },
    {
     "title": "GC time Sum",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
       "legendFormat": "{{pod}}-{{gc}}"
      }
     ]
    },
    {
     "title": "GC count increase",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
       "legendFormat": "{{pod}}-{{gc}}"
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_loaded_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-loaded"
      }
     ]
    },
    {
     "title": "Threads used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_current{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-current threads"
      },
      {
       "expr": "jvm_threads_daemon{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-daemon threads"
      },
      {
       "expr": "jvm_threads_deadlocked{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-deadlocked threads"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Running Applications",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ApplicationsRunning{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Containers Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ContainersLaunched{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-launched"
    },
    {
     "expr": "Hadoop_NodeManager_ContainersCompleted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-completed"
    },
    {
     "expr": "Hadoop_NodeManager_ContainersFailed{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-failed"
    },
    {
     "expr": "Hadoop_NodeManager_ContainersKilled{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-killed"
    },
    {
     "expr": "Hadoop_NodeManager_ContainersRunning{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-running"
    },
    {
     "expr": "Hadoop_NodeManager_ContainersIniting{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-initing"
    },
    {
     "expr": "Hadoop_NodeManager_ContainersPaused{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-Paused"
    }
   ]
  },
  {
   "title": "Allocated Containers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_AllocatedContainers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-launched"
    }
   ]
  },
  {
   "title": "Allocated GB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_AllocatedGB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Available GB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_AvailableGB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Available VCPU Cores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_AllocatedVCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Available VCores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_AvailableVCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bad Local Dirs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_BadLocalDirs{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bad Log Dirs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_BadLogDirs{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Launch Duration Avg Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ContainerLaunchDurationAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Used Mem GB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ContainerUsedMemGB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Used Virtual Mem GB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ContainerUsedVMemGB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Shuffle Output Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ShuffleOutputBytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Shuffle Output Failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ShuffleOutputsFailed{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Shuffle Output Succeed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ShuffleOutputsOK{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Shuffle Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_ShuffleConnections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Requests PerSecond",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NodeManager_TotalRequestsPerSecond{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-{{name}}"
    }
   ]
  }
 ]
}