{
 "title": "Hadoop HDFS ResourceManager",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(Hadoop_ResourceManager_NumActiveNMs,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(Hadoop_ResourceManager_NumActiveNMs{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(Hadoop_ResourceManager_NumActiveNMs{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - java_lang_Runtime_StartTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}/1000"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_runtime_info{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-system"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-process"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-total"
    },
    {
     "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-committed-vm"
    },
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-free"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-virtual-mem"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-resident-mem"
    }
   ]
  },
  {
   "title": "JVM Memory(Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-used"
    }
   ]
  },
  {
   "title": "JVM memory(NonHeap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_max{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-used"
    }
   ]
  },
  {
   "title": "JVM Memory(Committed)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-{{area}}"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Code Cache]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Code Cache\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Compressed Class Spacee]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Compressed Class Space\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Eden Space]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Eden Space\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Eden Space\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Eden Space\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Eden Space\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Metaspace]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Metaspace\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Survivor Space]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Survivor Space\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Survivor Space\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Survivor Space\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_init_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Survivor Space\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "JVM Memory pool [Tenured Gen]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}-max"
    },
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "jvm_memory_pool_committed_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",pool=\"Tenured Gen\"}",
     "legendFormat": "{{pod}}-init"
    }
   ]
  },
  {
   "title": "GC time Sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
     "legendFormat": "{{pod}}-{{gc}}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])",
     "legendFormat": "{{pod}}-{{gc}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-loaded"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{pod}}-deadlocked threads"
    }
   ]
  },
  {
   "title": "Cluster Info(AM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Name Node Info",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 576 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_NumActiveNMs{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "active"
      },
      {
       "expr": "Hadoop_ResourceManager_NumDecommissionedNMs{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "decommissioned"
      },
      {
       "expr": "Hadoop_ResourceManager_NumLostNMs{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "lost"
      },
      {
       "expr": "Hadoop_ResourceManager_NumUnhealthyNMs{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "unhealthy"
      },
      {
       "expr": "Hadoop_ResourceManager_NumRebootedNMs{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "rebooted"
      },
      {
       "expr": "Hadoop_ResourceManager_NumShutdownNMs{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "shutdown"
      }
     ]
    },
    {
     "title": "Memory Info(MiB)",
     "type": "timeseries",
     "description": "Memory Capability",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 576 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_CapabilityMB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-capacity"
      },
      {
       "expr": "Hadoop_ResourceManager_UtilizedMB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-utilized"
      }
     ]
    },
    {
     "title": "Virtual CPU Cores",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 576 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_CapabilityVirtualCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-capacity"
      },
      {
       "expr": "Hadoop_ResourceManager_UtilizedVirtualCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-utilized"
      }
     ]
    },
    {
     "title": "AM Launch Delay Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 584 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(Hadoop_ResourceManager_AMLaunchDelayNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "AM Container Allocation Delay Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 584 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(Hadoop_ResourceManager_AMContainerAllocationDelayNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "AM Container Allocation Delay Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 584 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AMContainerAllocationDelayAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "AM Register Delay Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 592 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(Hadoop_ResourceManager_AMRegisterDelayNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "AM Launch Delay AvgTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 592 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AMLaunchDelayAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "AM Register Delay Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 592 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AMRegisterDelayAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Used AM Resource MB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 600 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_UsedAMResourceMB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Used AM Resource CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 600 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_UsedAMResourceVCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Used Memory Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 600 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_UsedCapacity{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} * 100",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Total Requests PerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 608 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_TotalRequestsPerSecond{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} * 100",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Rpc Lock WaitTime AvgTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 608 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_RpcLockWaitTimeAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} * 100",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Rpc Lock WaitTime Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 608 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(Hadoop_ResourceManager_RpcLockWaitTimeNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Rpc Processing AvgTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 616 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_RpcProcessingTimeAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} * 100",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Rpc Processing Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 616 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(Hadoop_ResourceManager_RpcProcessingTimeNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Rpc Queue Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 616 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(Hadoop_ResourceManager_RpcQueueTimeNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Rpc Queue AvgTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 624 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_RpcQueueTimeAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} * 100",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Deferred Rpc Processing AvgTime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 624 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_DeferredRpcProcessingTimeAvgTime{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} * 100",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    },
    {
     "title": "Deferred Rpc Processing Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 624 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(Hadoop_ResourceManager_DeferredRpcProcessingTimeNumOps{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[2m])",
       "legendFormat": "{{pod}}-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Containers ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 633 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AllocatedContainers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Allocated CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 633 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AllocatedVCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Allocated Memory(Mib)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 633 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AllocatedMB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Pending Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 673 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_PendingContainers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Pending CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 673 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_PendingVCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Pending Memory(Mib)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 673 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_PendingMB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Reserved Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 681 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_ReservedContainers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Reserved CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 681 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_ReservedVCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Reserved Memory(Mib)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 681 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_ReservedMB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Allocated Aggregate Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 689 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AggregateContainersAllocated{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Preempted Aggregate Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 689 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AggregateContainersPreempted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Released Aggregate Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 689 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AggregateContainersReleased{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Alivable MB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 697 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AvailableMB{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Alivable CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 697 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AvailableVCores{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 602 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AppsRunning{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Pending Applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 602 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AppsPending{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Completed Applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 602 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AppsCompleted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Submitted Applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 610 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AppsSubmitted{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Killed Applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 610 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AppsKilled{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Failed Applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 610 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_AppsFailed{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Active Applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 618 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_ActiveApplications{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Running Apps Less Than 60 Mins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 618 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_running_0{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Running Apps ([60,300]) min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 618 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_running_60{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Running Apps([300,1440]) Mins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 626 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_running_300{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Running Apps More Than 1440 mins",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 626 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_running_1440{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    },
    {
     "title": "Active Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 626 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "Hadoop_ResourceManager_ActiveUsers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\", name=\"QueueMetrics\"}",
       "legendFormat": "{{pod}}-{{q0}}/{{q1}}/{{q2}}"
      }
     ]
    }
   ]
  }
 ]
}