{
 "title": "FalkorDB",
 "description": "Dashboards for FalkorDB managed by KubeBlocks",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(redis_up{job=\"$job\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(redis_up{job=\"$job\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(redis_up{job=\"$job\",namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, pod)"
    }
   },
   { "name": "job", "label": "job", "query": "kubeblocks" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(namespace)(redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count by(redis_version)(redis_instance_info{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Cluster Instances",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by(namespace,app_kubernetes_io_instance,node,pod) (redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "calculatedInterval": "10m",
     "expr": "avg by(namespace,app_kubernetes_io_instance,pod) (redis_uptime_in_seconds{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(pod,redis_version)(redis_instance_info{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(namespace,app_kubernetes_io_instance)(redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(namespace,pod)(redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top5 Memory Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_mem_util * on (iid) group_right redis_up or (100 * (redis_memory_used_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} / redis_memory_max_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top5 User CPU Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(redis_cpu_user_seconds_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bottom5 Hits Ratio",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(irate(redis_keyspace_hits_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m]) / (irate(redis_keyspace_misses_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[1m]) + irate(redis_keyspace_hits_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m])))  by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_cpu_util * on (iid) group_right redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_mem_util * on (iid) group_right redis_up or (100 * (redis_memory_used_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} / redis_memory_max_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(redis_connected_clients{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_commands_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} [2m])) by(namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_uptime_in_seconds{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} / 3600 - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(irate(redis_keyspace_hits_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m]) / (irate(redis_keyspace_misses_total[1m]) + irate(redis_keyspace_hits_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m]))) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_net_input_bytes_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_net_output_bytes_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connection And CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} |  connected_clients"
    },
    {
     "expr": "redis_blocked_clients{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | blocked_clients"
    }
   ]
  },
  {
   "title": "Used Connections Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (redis_connected_clients{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) / on(namespace,app_kubernetes_io_instance,pod) redis_config_maxclients{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Average Ratio",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_cpu_user_seconds_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m]) * 100",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | cpu_user"
    },
    {
     "expr": "rate(redis_cpu_sys_seconds_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[2m]) * 100",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} |  cpu_sys"
    }
   ]
  },
  { "title": "Memory And Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "description": "Total taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | Used Memory"
    },
    {
     "expr": "sum(redis_memory_max_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | MaxMemory"
    },
    {
     "expr": "sum(redis_memory_used_rss_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} |  Used RSS Memory"
    },
    {
     "expr": "sum(redis_memory_used_lua_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} |  Used Memory Lua"
    }
   ]
  },
  {
   "title": "Memory Usage Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (redis_memory_used_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) / on(namespace,app_kubernetes_io_instance,pod) redis_memory_max_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio per instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Expiring / Not-Expiring / Evicted Keys",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (redis_db_keys{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) - sum by(namespace,app_kubernetes_io_instance,pod) (redis_db_keys_expiring{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) ",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | Not-Expiring"
    },
    {
     "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (redis_db_keys_expiring{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | Expiring"
    },
    {
     "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (redis_evicted_keys_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | Evicted"
    }
   ]
  },
  {
   "title": "Key evictions per second per instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_evicted_keys_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace,app_kubernetes_io_instance,pod,db)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{ db }}"
    }
   ]
  },
  {
   "title": "Commands per second",
   "type": "timeseries",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} [$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod,cmd)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{cmd}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Command latency per second",
   "type": "timeseries",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod, cmd)\n  /\navg(irate(redis_commands_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod, cmd)\n",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{ cmd }}"
    }
   ]
  },
  {
   "title": "Hit ratio per instance",
   "type": "timeseries",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_hits_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval]) / (irate(redis_keyspace_misses_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval]) + irate(redis_keyspace_hits_total{pod=~\"$instance\"}[$__rate_interval]))) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod, cmd) != 0",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}  | {{ cmd }}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Connected slaves by instance",
   "type": "timeseries",
   "description": "This metric will only be non-zero if the instance is a master",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
    }
   ]
  },
  {
   "title": "Slave Repl Offset",
   "type": "timeseries",
   "description": "This metric will only be non-zero if the instance is a master",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_slave_repl_offset{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
    }
   ]
  },
  {
   "title": "Time since last master connection",
   "type": "timeseries",
   "description": "This metric is only exported if the instance is a slave.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
    }
   ]
  }
 ]
}