apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: doltdb-cluster
  namespace: demo
spec:
  terminationPolicy: Delete
  clusterDef: doltdb
  topology: standalone
  componentSpecs:
    - name: doltdb
      serviceVersion: "2.1.10"
      replicas: 1
      env:
        - name: DOLT_DATABASE
          value: testdb
      tls: true
      issuer:
        name: KubeBlocks
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "1"
          memory: 1Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: ""
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
