apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  name: doltdb-verticalscale
  namespace: demo
spec:
  clusterName: doltdb-cluster
  type: VerticalScaling
  verticalScaling:
    - componentName: doltdb
      requests:
        cpu: "2"
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 2Gi
