{
 "title": "APPS / Kafka",
 "tags": [
  "kafka",
  "apps",
  "db"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_activebrokercount_value,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_activebrokercount_value,app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_activebrokercount_value{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"},pod)"
    }
   },
   {
    "name": "request",
    "label": "request",
    "query": {
     "query": "label_values(kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},request)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{namespace=\"$namespace\", app_kubernetes_instance=\"$cluster\", topic!=\"__consumer_offsets\", topic=\"--kafka\"},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_activecontrollercount_value{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Global Topics Per Controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount_value{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_offlinepartitionscount_value{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}) by (namespace, app_kubernetes_io_instance)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Brokers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kafka_controller_kafkacontroller_activebrokercount_value{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Leader Partitions Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_leadercount_value{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Offline Replicas Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_offlinereplicacount_value{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}) by (namespace, instance, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemloadaverage{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Request Per-Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestspersec_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", request=~\"$request\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_server_socket_server_metrics_connection_count{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}) by (namespace, app_kubernetes_io_instance,pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes-In Per-Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_total_bytesinpersec_count{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes-out Per-Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Last AppliedRecord Lag Per Controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_lastappliedrecordlagms_value{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Kafka Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Message in per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", topic=~\"$topic\"}[1m])) by (topic, instance)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", topic=~\"$topic\"}) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{namespace=~\"$namespace\",  app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  }
 ]
}