{
 "title": "Microsoft SQL Server",
 "description": "Works with and awaragi/prometheus-mssql-exporter",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(mssql_up,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mssql_up{namespace=\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(mssql_up{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"},pod)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(mssql_connections,database)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Job：Server resource overview",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mssql_instance_local_time{pod=~\"$instance\"}*1000"
    },
    {
     "expr": "mssql_total_physical_memory_kb{pod=~\"$instance\"}-0"
    },
    {
     "expr": "mssql_available_physical_memory_kb{pod=~\"$instance\"}-0"
    },
    {
     "expr": "mssql_total_page_file_kb{pod=~\"$instance\"}-0"
    },
    {
     "expr": "mssql_available_page_file_kb{pod=~\"$instance\"}-0"
    },
    {
     "expr": "mssql_page_fault_count{pod=~\"$instance\"}-0",
     "legendFormat": "Total page faults"
    },
    {
     "expr": "mssql_batch_requests{pod=~\"$instance\"}-0"
    },
    {
     "expr": "mssql_page_life_expectancy{pod=~\"$instance\"}-0"
    },
    {
     "expr": "mssql_deadlocks{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_user_errors{job=~\"$Job\"}-0"
    },
    {
     "expr": "mssql_kill_connection_errors{job=~\"$Job\"}-0"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current database connections",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mssql_connections{}", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "DB Log growth since last restart",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mssql_log_growths", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "Total wait time of I/O stall",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall_total{job=~\"$Job\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Database I/O wait of stall detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database ${database} wait by I/O stall ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "repeat": "database",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall{database=~\"^$database\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}